### ISSUE TITLE
HTML (Django) is not working 

### ISSUE THREAD

**Issue by Ahmad-Dukhan** [facelessuser/BracketHighlighter#121]
Hi, 

Adding HTML (Django) to the settings doesn't work maybe because it relies on Djaneiro plugin (maybe not) I am not sure. 

But it would be wonderful if we get it to work on HTML (Django) 

Note: Global enable would allow matching {} "" '' & [] but not HTML tags 

Thanks

**Comment by pirate** [comment]
How do I get `HTML (Django)` tag highlighting working in the most recent version?  These line numbers are no longer up-to-date: "Tried to add "HTML (Django)" to the arrays at lines 214 & 448 on my bh_core.sublime-settings"

**Comment by facelessuser** [comment]
@pirate I don't know what "Django" package you are using, but you need to add the file name of the syntax highlighting file (the actual name on disk minus the extension).

**Comment by pirate** [comment]
@facelessuser Thanks, I got it working, see my PR's https://github.com/facelessuser/BracketHighlighter/pull/272 for the code.
