### ISSUE TITLE
BracketHighlighter-BH25T3和Main.sublime-menu中路径名不一致导致程序包无效

### ISSUE THREAD

**Issue by youryida** [facelessuser/BracketHighlighter#155]
英文不好，原谅我要用中文了。
BH2ST3这个版本的，下载到本地Packages后，文件夹的名字是BracketHighlighter-BH25T3，但是Main.sublime-menu这个文件里，文件夹路径用的是BracketHighlighter，（193行 "args": {"file": "${packages}/BracketHighlighter/bh_core.sublime-settings"}）。
这样会导致程序包无效。

我是小白，不知道这个是不是bug，最简单的修正方法为把下载下来的文件夹名字由BracketHighlighter-BH25T3改为BracketHighlighter。

**Comment by iam0005** [comment]
> 英文不好，原谅我要用中文了。
> BH2ST3这个版本的，下载到本地Packages后，文件夹的名字是BracketHighlighter-BH25T3，但是Main.sublime-menu这个文件里，文件夹路径用的是BracketHighlighter，（193行 "args": {"file": "${packages}/BracketHighlighter/bh_core.sublime-settings"}）。
> 这样会导致程序包无效。
> 
> 我是小白，不知道这个是不是bug，最简单的修正方法为把下载下来的文件夹名字由BracketHighlighter-BH25T3改为BracketHighlighter。

兄弟，这是正常的，重命名文件夹是对的，大多插件都要重命名为插件名字而不是带版本号的名字！
