### ISSUE TITLE
Not working on HTML tags?

### ISSUE THREAD

**Issue by lombardi-gux** [facelessuser/BracketHighlighter#166]
"tags" are not highlighte or shown in gutter when the file type is set to "HTML (Angular.js)".  They show for regular HTML.  

What can I copy into the syntax for Angular.js package?

**Comment by js-d-coder** [comment]
@facelessuser Hi, thanks for this package, very useful.
I have a question, if this package has built-in support for Angular HTML, then how come it does not work when I open Angular HTML template (error.component.html) as just HTML. Screen shot below. thanks again.
![Screenshot_20190529_153643](https://user-images.githubusercontent.com/23054879/58548807-b7c53180-8227-11e9-89d9-89b709615f0a.png)

**Comment by facelessuser** [comment]
The committed changes may enable HTML tag highlighting support in Angular, but it still only supports valid HTML syntax. Attributes with square brackets are not supported.

**Comment by js-d-coder** [comment]
@facelessuser thanks for reply, can we expect it in future?

**Comment by facelessuser** [comment]
It's possible maybe via a pull request, but I don't use Angular JS, so there is currently no motivation for me to do so officially. I don't know the nuances of the language, and don't have the time to learn it.
