### ISSUE TITLE
Request: minimal tag outlining

### ISSUE THREAD

**Issue by titoBouzout** [facelessuser/BracketHighlighter#171]
As discussed in http://www.sublimetext.com/forum/viewtopic.php?f=5&t=3327&start=170 

I would like to minimize the feedback caused by tag outlining . Is that some big opening tags cause things like this:

![](https://dl.dropboxusercontent.com/u/9303546/SublimeText/Bracket/tags.png)

I appreciate everything is configurable, but I have a hard time trying to simplify the outlining. Help needed! 

I suggest to go with a simple approach of highlighting just the tag name. Highlighting the brackets may be another approach but I would prefer the tag name as I can get attention directly in the portion that matters. With underline instead of outline it would look even better. Thanks in advanced!

[edits, edits]

**Comment by facelessuser** [comment]
I am reopening this issue as I think I willing to tackle tag name underlining now.  I imagine I will just add a bh_plugin hook that can alter the highlighting after all other plugin modifications to selections and regions have been completed.

**Comment by facelessuser** [comment]
So a `highlighting` hook as been added on the main/dev branch (https://github.com/facelessuser/BracketHighlighter/commit/8c01c8c6b03671be96c9f16f785a0648fa400d93).  Tag is now utilizing it to highlight only the tag name.

![screenshot 2015-01-24 21 46 58](https://cloud.githubusercontent.com/assets/1055125/5890314/ba43425a-a412-11e4-9cb4-e9d4149746ab.png)

A bit of testing still needs to be done before I push it to the ST3 branch officially.  But so far it is looking good.  Hopefully I will have it pushed out officially sometime soon.

**Comment by facelessuser** [comment]
This has been merged to the ST3 branch.
