### ISSUE TITLE
Not matching correctly in PHP combined with HTML

### ISSUE THREAD

**Issue by TheDutchCoder** [facelessuser/BracketHighlighter#191]
Hi there,

Love the plugin, but it seems to struggle with PHP that is intertwined with HTML.

An example:

``` php
<?php

if ($foo) {

  ?>
  <p>foo</p>
  <?php

}

?>
```

Will fail to match either bracket to each other, quite possibly because we go out of PHP and back in at some other point, though this should be relatively easy to circumvent by something like reg ex replacing "<?[non greedy reg ex here]?>" with (white)space.

**Comment by arnisjuraga** [comment]
This is awesome! Saved my day to find a missing closing "}" bracket for mixed PHP + HTML file!
