### ISSUE TITLE
please also handle matching <  >  

### ISSUE THREAD

**Issue by scottstensland** [facelessuser/BracketHighlighter#196]
For languages like c++ would be nice to also handle matching  <   >

**Comment by conundrumer** [comment]
bumping because it's common to do stuff like this in Rust: `Vec<Rc<RefCell<Box<Trait>>>>`

here's my take on matching templates/generics:

```json
{
    "name": "generic_angle",
    "open": "(<)",
    "close": "(>)",
    "style": "angle",
    "scope_exclude": ["string", "comment", "keyword.operator", "punctuation.separator", "meta.tag"],
    "language_filter": "whitelist",
    "language_list": ["C++", "Java", "Rust", "TypeScript"],
    "enabled": true
}
```

I haven't searched/tested for other languages with angle bracket generics but wanted to put this somewhere

**Comment by facelessuser** [comment]
@conundrumer, If you are proposing these changes, a better place is pull requests.  Since you made this a whitelist instead of enabling it globally, there is a good chance we can merge it as long as the enabled languages were well tested.
