### ISSUE TITLE
change color of bracket on highlight instead of background color

### ISSUE THREAD

**Issue by helgatheviking** [facelessuser/BracketHighlighter#21]
would it be possible to change the color of the brackets themselves when highlighted instead of highlighting via background color?  i find it hard to see the actual bracket text when it is highlighted currently.  plus the fact that the brackets turn red is probably my favorite feature from notepad++

**Comment by dotku** [comment]
![thin underscore?](https://camo.githubusercontent.com/caaf2ebdb5bb552023ff4d6707d83257af43e004/687474703a2f2f692e696d6775722e636f6d2f31417270446e752e706e67)

My question is, why my underscore is thin little one?
I'm using spacegray theme, it seems there is another setting for curly braket highlight?(thre are two underscore tegether with one white underline and other red underline)

**Comment by facelessuser** [comment]
You have the ST bracket matcher still enabled along with BracketHighlighter's.   You need to disable the ST matcher in Preferences.sublime-settings: http://facelessuser.github.io/BracketHighlighter/usage/#suggested-user-settings.

**Comment by dotku** [comment]
@facelessuser Great！It works~!
