### ISSUE TITLE
Customize settings without overwriting everything

### ISSUE THREAD

**Issue by denis-sokolov** [facelessuser/BracketHighlighter#211]
I want to customize settings in a very minor way, for example, disable single and double quote brackets.
To do that, I want to modify `scope_brackets/single_quote/enabled` key, but the only way to do is to overwrite the entire `scope_brackets` in my User settings file and miss future updates to the main file.
It's even worse with `brackets` key, where there's a lot of functionality and regular expressions that are very likely to improve with time.
As a result I now need to manually merge updated default settings and my modifications that I need to keep noted in comments.
This almost defeats the purpose of having two settings files.
I think a feature to resolve this would be gladly appreciated.

**Comment by facelessuser** [comment]
Documentation has been updated with instructions https://github.com/facelessuser/BracketHighlighter/commit/11e6e1537a2c6700950061453797a8327a06c7d0.
