### ISSUE TITLE
Prioritize SublimeLint

### ISSUE THREAD

**Issue by techdev5521** [facelessuser/BracketHighlighter#214]
When working in a line of code where the brackets are on the same line, the indication of the current bracket overrides the gutter linting icons. Is there a while to prioritize Sublimelint over BH?
![screen shot 2014-12-22 at 2 38 58 pm](https://cloud.githubusercontent.com/assets/9014440/5529953/56012756-89e8-11e4-8c8a-29152de92d5b.png)
![screen shot 2014-12-22 at 2 39 13 pm](https://cloud.githubusercontent.com/assets/9014440/5529954/56028a06-89e8-11e4-8a6f-bd39dbe27dd4.png)

**Comment by pkmital** [comment]
Follow up, how can I entirely disable the gutter icons for BracketHighlighter so that another plugin may use the gutter?

**Comment by facelessuser** [comment]
This is covered in the docs: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style.
