### ISSUE TITLE
BH Doesn't Work with ST3 3070+ Build? Yes it Does.

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/BracketHighlighter#226]
A new public beta for Sublime should be coming out soon. Some recent changes had been made to Sublime on the dev releases that were incompatible with BH causing freezing or crashing. BH has since been patched, but Jon wanted to minimize bug reports when the new beta is released, so he contacted me and we worked out a way for him to exclude older BH versions that don't have the fix.

In the new 2.4.0 release, I added a dummy file that can be checked by Sublime. The latest 2.4.0 release should work with the new 3070+ builds when the new Sublime beta drops, all BH releases before the 2.4.0 release will not work on 3070+ builds of Sublime. My advice is to upgrade via Package Control or update manually for those who still haven't gotten on the Package Control wagon.

**Comment by reagle** [comment]
I'm new to trying BH and I'm using ST3 3070. I just installed BH from package control and it is very nifty but isn't working for single and double quotes. Is there debug info I can provide to help with this?

**Comment by facelessuser** [comment]
Your's is a different issue than this.  With that said, can you be more specific?  What language are you having trouble in?

**Comment by reagle** [comment]
I suspect this is because I'm a newbie. In python files I will get the buffer icon within a quote but ctrl-m and ctrl-shift-m don't work for moving/selection within the quotes. In markdown, I don't get the buffer icon either.

**Comment by facelessuser** [comment]
@reagle <kbd>ctrl-shift-m</kbd> is the native `jump between brackets`.  If you want to tap into BH's `jump between bracket` feature, you will have to define your shortcut as outlined in the [example keymap](https://github.com/facelessuser/BracketHighlighter/blob/master/Example.sublime-keymap#L16) file (you can even override the built-in one if you like).

**Comment by facelessuser** [comment]
> In markdown, I don't get the buffer icon either.

The quote rule works based on scopes to find quotes as regex is not sufficient to tell a starting `"` from a closing `"`.  If markdown doesn't scope a string as a `string` scope, then BH is not going to find it.

**Comment by reagle** [comment]
That's too bad, but reading the "Additional Info" on https://github.com/int3h/SublimeSelectQuoted (and trying it) I think I understand now. Thank you for the quick help.

**Comment by facelessuser** [comment]
It's just how things are.  Without context, there is no way someone could tell you which of the following quotes is the opening or closing `"hello, " this is a string"` BH isn't always looking at the entire file when scanning for brackets, and though it may be easy for a human to look at the screen and go `obviously the string starts there`, it is a bit trickier to do it programmatically with code.

**Comment by facelessuser** [comment]
I think it is probably safe to close this notice.

**Comment by facelessuser** [comment]
Reopen for people who haven't seen this yet.

**Comment by facelessuser** [comment]
Okay, I think it has really been long enough to close this for good.
