### ISSUE TITLE
RE: "high_visibility_color"

### ISSUE THREAD

**Issue by iBEASTMODE** [facelessuser/BracketHighlighter#227]
how can you change this?

@ bh_core, I have tried:

"high_visibility_color": "brackethighlighter.square", (from your personal example of other colors)
"high_visibility_color": "#ff0000",

is it possible to directly apply a color (as in the second instance)?

**Comment by facelessuser** [comment]
Please read https://github.com/facelessuser/BracketHighlighter#configuring-highlight-style as it explains how to set colors.  The Sublime API does not allow me to directly set a color, but it must be done through indirection via scopes.  If you want a custom color, please follow the guide.

**Comment by facelessuser** [comment]
Though I have closed the issue, please feel free to continue the conversation if you are confused (after reading the guide of course :wink:).
