### ISSUE TITLE
RE: RE: "high_visibility_color"

### ISSUE THREAD

**Issue by iBEASTMODE** [facelessuser/BracketHighlighter#228]
thanks for the quick response on the last one,  missed it while scanning the instrux :-p

so I have it working now, but I did run into an issue.

the first time I set the color, it changed immediately upon saving the theme.
however, now any time I change the color, it loads the previously saved color.

IE:
[1] Save color as #FF0000
[2] Color has not changed
[3] Save color as #00FF00
[4] Color is now #FF0000
[5] Save color as #0000FF
[6] Color is now #00FF00
etc.

This effect continues even after re-saving all files involved, toggling high visibility, or even restarting sublime text.

The workaround is easy enough (name FF0001 + save, then name FF00000 + save), but I wanted to let you know of the issue.

Thanks again for your help! : )

**Comment by facelessuser** [comment]
I'm afraid this is not an issue with BH.  BH just sets a region with the scope, I don't do anything directly with the colorscheme.  I don't load it; I don't reload it; nothing.  Whatever colorscheme at the time that is loaded with that scope is what will determine the color.  So I would suspect that you changed your colorscheme, but for whatever reason, Sublime did not reload that theme yet.

Now keep in mind if you use a plugin like SublimeLinter, it will take your current theme copy it appending (ST) to it because it injects its own color stuff into it.  So if you modify your original color scheme, SublimeLinter won't re-copy the color scheme and reapply it until you physically re-apply the **original** color scheme.  That is the one thing that really annoys me about SublimeLInter.

**Comment by iBEASTMODE** [comment]
Yes, I've also now experienced it with non-BH color settings after a few hours of tweaking theme/style related settings.  Must be my color preview plugin or something else...

Is it possible to change the text & border colors when high visibility is enabled?  I've tried using:

<key>fontStyle</key>
<string></string>
<key>foreground</key>
<string>#FE0101</string>

in a variety of nested <dict> arrangements and have been unable to get it to work. Also blew out my theme a few times... :-X

**Comment by iBEASTMODE** [comment]
Also, I found a thread where you mentioned the ST API:
https://www.sublimetext.com/forum/viewtopic.php?f=5&t=3327&start=10

& saw that it mentions "sublime.HIDE_ON_MINIMAP"

is there a way to enable BH on the Minimap?

**Comment by facelessuser** [comment]
I believe sublime picks the border color automatically except when doing outlines.  You can play with the scheme colors, but basically I believe sublime also high jacks the don't color as well.  This is just when you use the highlight region API command.  Try it out and let me know if you find something different.

**Comment by facelessuser** [comment]
As for the minimap, I would have to see what I am doing internally.  Technically it's possible, I just don't think there would be much use for it.

**Comment by iBEASTMODE** [comment]
The Minimap could be useful for searching within particular regions, & perhaps other functions as well.

Usage example here:

https://lh6.googleusercontent.com/hxsIHJ4cl9GHZY4SOV7Pic1F1aRF9hW5khoBatMFD6I=w0-h0

**Comment by facelessuser** [comment]
Hmm.  Maybe it could be enabled for high visibility mode...

**Comment by facelessuser** [comment]
I've decided to add this as an optional feature in the settings file.  It won't work with the `underline` style, but it will work with other underline styles such as `thin_underline`.

```js
 // Show brackets in the minimap.
 // Depending on your highlight style, regions may not be visible in minimap.
 // "underline" won't show up due to it being a style consisting of
 // multiple zero width selections to create a fat underline.
 // But the following styles should show up fine as they are normal regions styles:
 //     - thin_underline
 //     - solid
 //     - outline
 //     - squiggly
 //     - stippled
 "show_in_minimap": false,
```

Feature is added in commit https://github.com/facelessuser/BracketHighlighter/commit/928bdec3187690d8a5ec8b4ff40079c72dac154f.

**Comment by iBEASTMODE** [comment]
Nice!  Awesome feature, thanks for adding it!

Works great with multiple selections also, useful for quickly jumping between related bracket sections via the minimap.

:+1:
