### ISSUE TITLE
Disable in certain filetypes

### ISSUE THREAD

**Issue by GaryKing** [facelessuser/BracketHighlighter#230]
Is it possible to disable this package in certain filetypes? For instance, it's active in my .md (Markdown) files when I don't want it to be. 

I checked the docs but it looks like I have to disable each bracket type individually, for .md files? So that's about 25 rules or so that I'd have to create? 

Is it possible to instead implement a `excluded_file_types: ['txt', 'md']` setting instead?

**Comment by facelessuser** [comment]
Disable:
https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L152
https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L163

Add `Markdown` to:
https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L93
https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L104
https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L182
https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L195
https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L208

Please read https://github.com/facelessuser/BracketHighlighter#configuring-brackets for more info.

**Comment by facelessuser** [comment]
I assume you got what you needed, so I will close this thread.
