### ISSUE TITLE
Swap Quotes command fails for Python triple-quoted strings

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/BracketHighlighter#233]
Finally got around to bind this to a key binding, when I found out this.

It should swap `"""` and `'''`, but a doc string such as
```
    """Some description.
    """
```
gets turned into
```
    '""Some description.
    ""'
```
which is invalid syntax.

**Comment by facelessuser** [comment]
I think you are mistaken and maybe you are running a swap command from some one else plugin, but BH translates these quotes just fine for me.

**Comment by facelessuser** [comment]
Just to back this up a little bit, you can see in the code here that I convert all old quotes to the new quotes in a given open and closing bracket region.

bh_plugins get the whole region for the opening and closing. So the swap quotes module then converts all quotes in those regions and then parses the content  between them  and swaps escaped chars: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_modules/swapquotes.py#L35.

So unless your language file is some how making it so BH can no longer recognize triple quotes strings, I can't see how this would be a problem.

If it is your language file, then putting back in the appropriate scopes would fix this.  Or adjusting the quote rules in the `bh_core.sublime-settings` file to properly find the entire opening and closing of python strings again would fix it.  But I don't think there is anything inherently wrong with the swap quotes module or BH in general.

**Comment by FichteFoll** [comment]
You are correct, it works with the default Python syntax. I'll need to tweak Python Improved then.

**Comment by facelessuser** [comment]
Another option is to add a rule in BH's settings for Python Improved.  Whatever makes the most sense.

**Comment by FichteFoll** [comment]
It appears to me the issue is actually within BH since the scope names are exactly identical.

I first assumed that BH restricts Python quote highlighting to the "Python" syntax only (according to `bh_core.sublime-settings`), but adding "PythonImproved" to the `language_list` didn't help.
(may I suggest using scope name (`source.python`) instead for this?)

Any othe ideas?

**Comment by facelessuser** [comment]
Let me take a look at what you have.

But basically, BH is basically just a bracket highlighting framework.  I am hesitant to lay blame on the current infrastructure as I am supporting a ton of different languages.  Some languages require tweaking existing rules, or sometimes inserting new rules entirely.  Generally, I leave maintaining the rules up to the community to maintain (unless I have a vested interest in the particular language).   I do not view rule tweaks as anything wrong with BH.  I basically try to just maintain the framework, and other people sort out the rules for their given languages.

So if a problem is exposed in the framework, I will rework it.  With that said, I do follow Matt's Python Improve as I do merge back changes into my personal language occasionally, so I am interested to see what is different now.  I want to see if it is a scoping issue or what.

I will get back to you once I test it.

**Comment by facelessuser** [comment]
Using the tip of your fork, this was all I needed to get things working; all I did was add `PythonImproved` to the language list:

```js
        {
            "name": "py_single_quote",
            "open": "u?r?((?:'')?')",
            "close": "((?:'')?')",
            "style": "single_quote",
            "scopes": ["string"],
            "language_filter": "whitelist",
            "language_list": ["Python", "PythonImproved"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "py_double_quote",
            "open": "u?r?((?:\"\")?\")",
            "close": "((?:\"\")?\")",
            "style": "double_quote",
            "scopes": ["string"],
            "language_filter": "whitelist",
            "language_list": ["Python", "PythonImproved"],
            "sub_bracket_search": "true",
            "enabled": true
        },
```

**Comment by FichteFoll** [comment]
... Whops. That's actually what I did as well, but I only added it to the single quote variant and not to the double quote one while testing it in a double triple quoted string. Thanks I guess.

So, back to the underlying problem. Do you think using a base-scope list is a better idea than specifying the the syntax names? That would be a more general and less specific approach.
Also, is there a better way currently than to copy the entire `scope_brackets` list when you want to override just two language_list filters? Since it's currently saved as a list it's not easy to determine which one you'd want to override. If it was a dictionary with the "name" as key it would be easier.

**Comment by facelessuser** [comment]
> So, back to the underlying problem.

Alleged problem :wink:.

> Do you think using a base-scope list is a better idea than specifying the the syntax names?

Let me explain what I am doing here.  I don't want to load every rule in bh_core.sublime-settings file when I enter a view.  I don't want to search every rule that may be irrelevant.  To plow through all of those regex rules every time would probably impact performance.   Performance is what I care about most.

So, what I do, is allow people to specify a language to allow the rule in, or to blacklist.  That way I only load the relevant regex that will be used and the the relevant bh_plugins that support a language.  This way on activation, I do that stuff once, and then I am done.  Then I focus just on matches.

If I were to do it the other way, I would have to check the scope on every match and then walk through all the rules every time compiling a list of relevant rules to then load up and execute.  Not only that, when I am preparing my search window, I now need take into account all the scope extents that should also limit my search range.  Basically I would be preparing rules for various subregions of my search window.  If I let all the languages mix, I run the risk of letting all the rules gobble up each others tokens.  it's complicated, and their is a trade off even now with allowing what rules in what file.

It's possible I will revisit this stuff in BH 3.0, but to do what you are suggesting would require quite an overhaul, and we still might get more issues than what we gain.

> Also, is there a better way currently than to copy the entire scope_brackets list when you want to override just two language_list filters?

I need an ordered list.  Order is important with rules, but yes, there is a way to manage rules withoug copying the entire list: https://github.com/facelessuser/BracketHighlighter#bracket-rule-management

**Comment by FichteFoll** [comment]
By "base-scope" I mean something like [this](https://github.com/SublimeText/AAAPackageDev/blob/fff0c4aff94f86ed9aec7bb16376d18ad46b071b/Lib/sublime_lib/view/_view.py#L112-L115). It could then be used with the `sublime.match_selector` API and matched agains a `language_selector` like `source.python`. Since this supports scope selectors, it would also allow negative selectors like `- text.plain` so `language_filter` is not needed.

Not a huge issue ofc, but sounds like a good idea to me.

> there is a way to manage rules withoug copying the entire list

Very nice. I actually remember seeing this not too long ago but I didn't actually read it, heh.

**Comment by facelessuser** [comment]
> By "base-scope" I mean something like this. It could then be used with the sublime.match_selector API and matched agains a language_selector like source.python. Since this supports scope selectors, it would also allow negative selectors like - text.plain so language_filter is not needed.

Maybe, but I would need to actually evaluate how well this idea works first.  Anyone can make a language with the same scope as another.  I would have to play around with the idea first to see how feasible it would be and what gains, if any, and what side-effects, if any.  Again, maybe in BH 3.0, but I will make a note of this to consider.

> Edit: You should mention this in the settings file, in the spirit of the "Just in Time" theory.

True, so true.
