### ISSUE TITLE
Highlights not removed when disabling package

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/BracketHighlighter#235]
It appears you don't remove the highlighted regions when the plugin is disabled (`plugin_unloaded`). The only ways to remove them are by console (if you happen to know how it works) or by closing and reopening the view.

**Comment by facelessuser** [comment]
Yep, I am aware.  It is has been on my list, just haven't gotten around to it yet.

**Comment by facelessuser** [comment]
Fixed here https://github.com/facelessuser/BracketHighlighter/commit/3f8fd78eb497f175d90ffb627393c141ec214602.
