### ISSUE TITLE
Configuring highlight style

### ISSUE THREAD

**Issue by sksea** [facelessuser/BracketHighlighter#236]
Thanks for the package, where exactly do we put the snippet below in our default tmTheme? I tried between the `<plist>` tags and also the "settings" `<array>`.

        <dict>
            <key>name</key>
            <string>Bracket Curly</string>
            <key>scope</key>
            <string>brackethighlighter.curly</string>
            <key>settings</key>
            <dict>
                <key>foreground</key>
                <string>#CC99CC</string>
            </dict>
        </dict>

**Comment by sksea** [comment]
Resolved by looking at your aprosopo theme. Placed snippet between "settings" `<array>` tags and reloaded the theme.

**Comment by facelessuser** [comment]
Glad you figured it out.  I hadn't had a chance to answer yet.
