### ISSUE TITLE
Highlight bracket matches in search

### ISSUE THREAD

**Issue by crumpley** [facelessuser/BracketHighlighter#237]
I notice when I search for a single bracket, when the bracket is highlighted there is no matching bracket highlighted. I don't know if this is behavior peculiar to  BracketHighlighter, or general behavior for Sublime Text.

It would be highly useful if I could automatically see the matching bracket highlighted directly in the search results without having to move the cursor manually. Is this possible?

**Comment by facelessuser** [comment]
I don't think I understand what you are saying...can you elaborate and/or post a screenshot of what you mean?

**Comment by crumpley** [comment]
Hi Isaac,
Thanks for your quick response. I'll try to explain more clearly, and I've
included a couple of screenshots.

In the first screenshot, AfterFind.jpg, I have just searched for a single
left brace. The first one found is highlighted in yellow. You'll notice
that there is nothing showing in left gutter to indicate any matching
bracket.

In the second screenshot, AfterClicking.jpg, all I did was click the mouse
on the found character. You can see that the left gutter now shows a pair
of braces indicating matches.

I want this matching information to show automatically for each new found
brace (each time I click the Find button). This way I can go through a file
and quickly see this information so I can correct any mismatched braces (or
brackets or parentheses).

Is that clearer? Can this be done?

Thanks,
Glenn

**Comment by facelessuser** [comment]
Can you post the screenshots directly to the github issue?  If sent by mail, github strips out attachments.

**Comment by crumpley** [comment]
Here are the screenshots refereced in  my earlier commenbt.
![afterfind](https://cloud.githubusercontent.com/assets/7952209/6858665/3744b80c-d3e7-11e4-8ef5-ef0fce83f63d.jpg)
![afterclicking](https://cloud.githubusercontent.com/assets/7952209/6858673/41e20576-d3e7-11e4-9672-0f6e9dbe45a5.jpg)

**Comment by facelessuser** [comment]
BH requires a cursor movement or the buffer to change to trigger a match. Matches occur around the cursor(s); that is fundamentally how it works.  Search selection doesn't trigger an event that can be intercepted by plugins, so I don't think this possible.
