### ISSUE TITLE
how to install BracketHighlighter via offline mode?

### ISSUE THREAD

**Issue by weijy026a** [facelessuser/BracketHighlighter#238]
If I install BracketHighlighter via Package Control, it cann't be download successfully and reports as below.

reloading Packages/User/Preferences.sublime-settings
Package Control: Downloading https://codeload.github.com/facelessuser/BracketHighlighter/zip/st3-2.5.0 timed out
error: Package Control

Unable to download BracketHighlighter. Please view the console for more details.

Then can I install BracketHighlighter via offline mode?
Thank you in advance.

**Comment by facelessuser** [comment]
I think Package Control was having some issues when Github was under a DDOS attack.  I think the problem should be resolved now.  If you need to manually check it out in the future, you can download the release and drop it in your Packages folder.  Make sure the plugin's folder name is BracketHighlighter.
