### ISSUE TITLE
Fail to match round bracket $() in shell script(Bash)

### ISSUE THREAD

**Issue by rexdf** [facelessuser/BracketHighlighter#239]
In a bash script type `$(abc)`,  BH cannot find the match. So we cannot do swap or delete operation.

**Comment by facelessuser** [comment]
Feel free to add a rule or alter the round rule to add functionality.  By default, BH avoid highlighting brackets in the during scope.  Bash highlights `$()` as strings.  BH will highlight sub brackets in strings if they are a recognized quoted string, in this case they only match within the scope of the during.

So in short, it was bad form for bash to use the string scope for a non-string. So it doesn't work for the current rules.  Modification to the existing rules may be all you need, but if not, you will have to create a new rule.

I mainly focus on the core code and require language support to be added by the community.

**Comment by facelessuser** [comment]
I'll post some pointers to get you going in a little bit.  I think your problem will be easy to fix, but you will have to run with the suggestion and do the general testing for a pull request.

**Comment by facelessuser** [comment]
Alright, to get you on your way, I would first take care of strings embedded in your the string scopeing of `$()`.

You can do this by modifying the double quoted and single quoted rules to use a more specific scope if there first fails:

```js
        {
            "name": "single_quote",
            "scopes": ["string", "string.quoted"]
        },
        {
            "name": "double_quote",
            "scopes": ["string", "string.quoted"]
        }
```

Secondly, we need to modify the round rule to make an exception and target the round brackets within strings if they are scoped as the start and end punctuation of the shell command:

```js
        {
            "name": "round",
            "scope_exclude_exceptions": [
                "text.tex string.other.math",
                "punctuation.definition.string.begin.shell",
                "punctuation.definition.string.end.shell"
            ]
        },
```

Now you can see we treat embedded strings properly, can match sub-brackets in the strings as usual, and we can now see the round brackets.  I will leave it up to you to do further tests and make further changes if necessary.  I will look for a pull request.  Hope this helps.

![screenshot 2015-04-04 10 29 31](https://cloud.githubusercontent.com/assets/1055125/6993661/0eafbda0-dab9-11e4-89b4-8f898064efdd.png)

**Comment by facelessuser** [comment]
By the way, [ScopeHunter](https://github.com/facelessuser/ScopeHunter) is a great tool for exploring scopes to help you with your BH rules.

**Comment by facelessuser** [comment]
As noted, language support is supported via the community pull requests.  This issue will be closed and will await a pull request.

**Comment by rexdf** [comment]
I have make a pull request. It just contains all you write above.

How can you gutter icon is the most outside match?

**Comment by facelessuser** [comment]
I am afraid I don't understand the question.  Can you explain?

**Comment by rexdf** [comment]
![bash_bracket](https://cloud.githubusercontent.com/assets/4038241/7068463/2ff14cd6-df05-11e4-8e99-4ee945cf261c.png)

**Comment by rexdf** [comment]
Your gutter is `()` but mine is `[]`

**Comment by facelessuser** [comment]
You can't set it in my picture, but I had three cursors in three different places, showing three different brackets being matched.  Sublime just picked the outside one to be down in the gutter.

BH will show the closest bracket match around your current cursor(s).
