### ISSUE TITLE
ColdFusion Integration

### ISSUE THREAD

**Issue by seanvikoren** [facelessuser/BracketHighlighter#24]
Greetings, I am hoping to get BracketHighlighter running well with https://github.com/SublimeText/ColdFusion.

Any help will be much appreciated.

**Comment by srconklin** [comment]
What is the status of this. I am not seeing any bracket highlighting for cfml pages at all

**Comment by facelessuser** [comment]
I don't know.  I am not sure of what you are using for your cfml highlighter, nor do I use cfml.  The status is probably as I last posted.

With that said, CFML was probably based on the ColdFusion package here https://packagecontrol.io/packages/ColdFusion, but as you can see, it is only for ST2 (which is when I added this), but it may work with ST3 even though the author did not enable the package for ST3.  If you find an ST3 compatible syntax highlighter, you can add support for it via pull request, or lastly, you can modify tag settings to use cfml searches in regular HTML: http://facelessuser.github.io/BracketHighlighter/customize/#tag-plugin-settings.

**Comment by srconklin** [comment]
This is the new cfml package that is regularly maintained for ST3 
https://packagecontrol.io/packages/CFML

**Comment by facelessuser** [comment]
I would test it out and put together a pull request if it works for you.  You probably only need to add the syntax file in a couple of places in `bh_core-sublime-settings` and `tag.sublime-settings`:

http://facelessuser.github.io/BracketHighlighter/customize/#tag-plugin-settings

http://facelessuser.github.io/BracketHighlighter/customize/#configuring-brackets

I leave language support up to the community: http://facelessuser.github.io/BracketHighlighter/contributing/.

I mainly support the core code, though if you get stuck, I don't mind offering advice or answering questions to help you get your pull request moving forward.
