### ISSUE TITLE
Freezes on Latest ST3 When Opening Scopes Inside Strings

### ISSUE THREAD

**Issue by jproffitt3ge** [facelessuser/BracketHighlighter#241]
After the latest update to ST3, I cannot open scopes (such as Twig's {{}} / {%%}) inside strings ("" / ''). 

For example, pasting `<div id='widget-{{` anywhere in a twig syntaxed file will cause ST3 to freeze consistently. If I write the inner scope first (e.g. `{{ id }}`), then paste that into the string then I don't have a problem.

It doesn't matter if I use double quotes or single quotes, or if theres anything else in the file. It doesn't matter if the string is complete ("blah") or open ended ("blah). When I disable this package I do not experience the issue.

Edit: I see a topic that discusses this exact issue: https://www.sublimetext.com/forum/viewtopic.php?f=5&p=67180 . I thought I had updated my Bracket Highlighter to the latest version. I'll go ahead and remove this if I'm not up to date.

**Comment by facelessuser** [comment]
I don't know what twig is.  I don't have a twig highlighter.  You need to provide me with detailed steps to reproduce.  I need to know ST3 version, I need to know platform, I need to know syntax highlighter package you are using.

Keep in mind there was a freeze issue that was introduced around ST build 3070.  ST changed some things that caused BH to freeze. BH was adjusted to fix this issue latest BH releases.  So, everything needs to be updated to the latest.

Anyways, if you provide the requested info, I will be able to look into it.

**Comment by jproffitt3ge** [comment]
I apparently installed BracketHighlighter manually so I was still using an old version from before the EOF patch. I updated it and the issue was of course fixed. My apologies.

**Comment by facelessuser** [comment]
Not a problem.  This is why I recommend Package Control to stay up to date.
