### ISSUE TITLE
Feature request: highlight word before opening bracket

### ISSUE THREAD

**Issue by 315234** [facelessuser/BracketHighlighter#246]
Sorry for the noise if this is already implemented or discussed before.

It would be nice to be able to highlight the word directly before the opening bracket. For example, in a function the function name would be highlighted; in an if statement the "if" would be highlighted, etc. in addition to the opening bracket being highlighted. Mathematica has this feature and it is quite pleasant.

**Comment by facelessuser** [comment]
You would have to rewrite a number of the rules, but it could possibly be done depending what you are actually trying to do, but I have no interest to do it by default.  Feel free to read the documentation to augment your own personal rules to get your desired behavior.
