### ISSUE TITLE
after upgrade package automatically opens "Default (OSX).sublime-keymap"

### ISSUE THREAD

**Issue by titoBouzout** [facelessuser/BracketHighlighter#247]
I use windows, and also, I have no interest to update the sublime-keymap after upgrading the package. Not sure what is the purpose =)

**Comment by facelessuser** [comment]
Are you sure you are attributing this to the right package?  I haven't added any open file calls to BH.  I am also not seeing this behavior.  I think whatever the issue is, it is coincidently appearing along side the BH upgrade.

**Comment by titoBouzout** [comment]
This is very weird thing. Step to reproduce:

1. Have an unzipped version of BH in Package Folder.
2. Main menu bar -> Preferences -> Package Control -> Upgrade Packages
3. BH will be listed as a package that needs update. 
4. Click the item in the quick panel to upgrade, and THEN very quickly (before the package updates) Go to Main menu bar -> Preference -> Package Control (but don't click the menuitem! just stay there... ) 
5. Wait a bit... click "Package Control" 
6. A new view/tab appears holding a file named "Default (OSX).sublime-keymap"


This is probably triggered because the menu is updated after it was opened but before it was used. 
o.O

So if you open the menu, a package updates it in between and you click something, an unexpected command will run

**Comment by facelessuser** [comment]
Wow, that is weird. Definitely looks like a Sublime thing :).

**Comment by titoBouzout** [comment]
https://github.com/SublimeTextIssues/Core/issues/824
