### ISSUE TITLE
To change color is too hard!!!!!

### ISSUE THREAD

**Issue by mqliutie** [facelessuser/BracketHighlighter#249]
I have read [docs](http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style) that may say " you build a `bh_core.sublime-settings` file in Packages/User and add some rules " OK, I do. I find `/Applications/Sublime Text.app/Contents/MacOS/Package`  . I don't know whether this Package is the previous one . Because in Package folder don't have User folder . I have did `mkdir User` in **Packages folder** and "vim bh_core.sublime-settings" copy some rules in .  [#21](https://github.com/facelessuser/BracketHighlighter/issues/21) mentioned **Copy BracketHighlighter.sublime-settings to your Packages/User folder and change the setting below.**  But in Packages folder there is don't have `BracketHighlighter.sublime-settings` file .  So , what should I do?

**Comment by facelessuser** [comment]
I'm sorry!!!!!  But that is the way it works with Sublime.  Sublime places limitations on how I can affect the color.

> OK, I do. I find `/Applications/Sublime Text.app/Contents/MacOS/Package`.

Don't do that.  Go to your menu `Sublime Text->Preferences->Browse Packages`  and you will see the `User` folder in finder.  In your `User` folder, create a `BracketHighlighter.sublime-settings` and copy over any setting you want to override.  You can find the original settings file via the menu `Sublime Text->Preferences->Package Settings->BracketHighlighter->Bracket Settings - Default`.

Hope that helps.

**Comment by mqliutie** [comment]
Sorry, Where is color scheme ?  in other words ,Where will the code below  be added? 
```
<dict>
       <key>name</key>
       <string>Bracket Curly</string>
       <key>scope</key>
       <string>brackethighlighter.curly</string>
       <key>settings</key>
       <dict>
            <key>foreground</key>
            <string>#CC99CC</string>
       </dict>
</dict>
```

**Comment by mqliutie** [comment]
Thanks ， I have solved this problem ， Thank you very much

**Comment by facelessuser** [comment]
Glad you figured it out.
