### ISSUE TITLE
background withouth removing color syntax?

### ISSUE THREAD

**Issue by neohunter** [facelessuser/BracketHighlighter#250]
Right now the option "solid" for style removes the color syntax,

I would like to add a soft background that dont remove the color syntax, is that possible?

**Comment by facelessuser** [comment]
This is a limitation to how sublime highlights a region.  I am afraid there isn't much I can do about this.  You can play with your theme colors associated with the highlighting http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style, but that is about it.  There is nothing I can do on my side.
