### ISSUE TITLE
ST3 User config is not working

### ISSUE THREAD

**Issue by norlin** [facelessuser/BracketHighlighter#254]
When i'm trying to change any default settings in the User's config (which is available from ST menu -> Preferences -> Package Settings -> ...) – nothing happens.

Is it bug in the code or in my DNA? :-)

**Comment by facelessuser** [comment]
I guess I would need more info.  The default settings won't change.  User settings should override the default no problem.  I personally override a number of the defaults.

If you could provide more info, I may be able to guess better what your issues is.

**Comment by norlin** [comment]
Which info do you need?

For example, after BH install, I have tried to set my User's setting to show on minimap:
```json
{
    "show_in_minimap": "outline"
}
```
nor 
```json
{
    "show_in_minimap": true
}
```

Also, I have tried to disable strings matching – but this part is unclear ho to do it properly – do I need to copy-paste whole matching settings (with no 'quotes') from the Default config, or just 'quotes' rules with ```enabled: false```?

**Comment by facelessuser** [comment]
What is your style setting.  `show_in_minimap` is either `true` or `false`, but it doesn't work on normal underline, on all other styles it works great.  You can read the description in the defaults:

```js
// Show brackets in the minimap.
    // Depending on your highlight style, regions may not be visible in minimap.
    // "underline" won't show up due to it being a style consisting of
    // multiple zero width selections to create a fat underline.
    // But the following styles should show up fine as they are normal regions styles:
    //     - thin_underline
    //     - solid
    //     - outline
    //     - squiggly
    //     - stippled
    "show_in_minimap": false,
```

**Comment by facelessuser** [comment]
http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management

There are a number of examples.  The old way was to copy the entire bracket list, but now you can override existing ones without copying the entire list, you can read about it in the link above.  But yeah, when you override it, you would set the `enabled` to `false`.

**Comment by norlin** [comment]
Yeah, I have read it, but it's not clear which style is it. Next line is ```"high_visibility_style": "outline",``` – so, I thought it's about this one... Ok, this part I've got, thanks! (But it's almost invisible on minimap with any style...)

Anyway, what about disabling string rules (double & single quotes)?

**Comment by facelessuser** [comment]
> Ok, this part I've got, thanks! (But it's almost invisible on minimap with any style...)

I don't control how it looks, that is all Sublime.  I only added it because it was requested; I don't particularly find it useful myself.

> Anyway, what about disabling string rules (double & single quotes)?

Did you read http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management?  Your answer is in the first three paragraphs.  I'm just going to end up rephrasing that part, so if you read and are still confused, I can clarify the specific part you are confused about.

**Comment by facelessuser** [comment]
I am assuming that your question was answered as things have gone silent here.
