### ISSUE TITLE
Not showing up in packet list in ST3

### ISSUE THREAD

**Issue by ricardozea** [facelessuser/BracketHighlighter#256]
I'm following the instructions from here http://facelessuser.github.io/BracketHighlighter/installation/#package-control and I don't see the plugin listed.

I'm suing ST3 build 3083.

Anyone else having this issue?

![brackethighlighter not showing up in package list](https://cloud.githubusercontent.com/assets/1656481/8600307/57bca4b6-2633-11e5-9175-dc182c07fe11.png)

**Comment by facelessuser** [comment]
Package control either thinks it is already installed (check the uninstall command) or Package Control is messing up.  It is either a Package Control issue or a user error.  There is nothing I can do from my end.  If it is a Package Control issue, you will need to create an issue on that repo.

**Comment by ricardozea** [comment]
You are correct, it was a Package Control issue. I reinstalled it and I was then able to install BracketHighlighter. Awesome plugin. Thanks!
