### ISSUE TITLE
Ruby matching do...end with cursor after end

### ISSUE THREAD

**Issue by kule** [facelessuser/BracketHighlighter#259]
Loving BH but just one minor niggle is that if you put the cursor after end you don't get the matching do it goes to the outer block:
![screenshot 2015-07-17 12 21 37](https://cloud.githubusercontent.com/assets/30228/8746151/6d7272f8-2c7e-11e5-942d-0426ca78618f.png)

~~Interestingly if you do the same on the do block it works properly:~~
![screenshot 2015-07-17 12 19 16](https://cloud.githubusercontent.com/assets/30228/8746150/6d702a84-2c7e-11e5-9b47-009a5e5b3ebd.png)

Opps wrong side - do does the same:
![screenshot 2015-07-17 12 26 21](https://cloud.githubusercontent.com/assets/30228/8746222/0f185514-2c7f-11e5-97c2-d2ee2f636193.png)

Is this an easy fix or can you point me in the right direction to have a go myself?

Thanks
Luke

**Comment by facelessuser** [comment]
Please follow the guidelines for issues: http://facelessuser.github.io/BracketHighlighter/contributing/#bug-reports.

- Sublime build number?
- Post example example code so I can copy and paste to reproduce
- What syntax language do you use?

etc.

Thanks

**Comment by kule** [comment]
Opps, sorry about that and doubly sorry as I was just writing all the details out; quit & restarted Sublime to get a clear console log, it updated the package and it seems to be working ok now (maybe it just needed a restart?).

**Comment by facelessuser** [comment]
> maybe it just needed a restart?

Possible.  Usually a restart is good right after some packages install as all there dependancies might not be loaded proper during an install/upgrade.  Glad its working again for you.
