### ISSUE TITLE
Ruby conditionals does not handle one liners

### ISSUE THREAD

**Issue by jtgrenz** [facelessuser/BracketHighlighter#263]
The ruby conditional plugin is not able to handle ruby's one liner if/unless statements 
```
unless condition
   some_action
end
```
and related blocks seem to work fine, but when you use a one liner like

`unless condition some action`
or 
`if condition then action`
or
` some_action if condition`

then the matching is thrown off for the rest of the file. The ruby parser is able to handle these implied endings and its a popular form for short conditionals.

**Comment by facelessuser** [comment]
1. I would read overview in the Contribution and Support section in the docs: http://facelessuser.github.io/BracketHighlighter/contributing/#overview.  In short, I require the community to support the language rules, and I deal with core framework code (and languages I usually have a vested interest in).  I don't use ruby, so this will require a pull request from someone.

2. With that said, I can at least give some guidance.  If a regex look ahead could be constructed to sniff out these one liners, then you could effectively ignore these one liners. FYI, we already ignore `some_action if condition`.

3.  Maybe look aheads aren't the way to go and you need a more programatic approach.  You can look in `bh_modules\rubykeywords.py` and add a validate check: http://facelessuser.github.io/BracketHighlighter/customize/#validate.  Here you can maybe do some more advanced logic to sniff out whether you want to count the given keyword.

4. If core changes are needed to accomplish the goal, I am open as long as no language specific code is requested in core.  The idea was to push language specific things out of the core so the community could contribute new rules and fixes to existing rules without having to understand all the core stuff.

I am willing to give advise, answer questions, and provide guidance to those willing to try and put in the effort.  In short, you are more of an expert on ruby than I am, so I will defer this issue to you or some other brave soul who wishes to tackle this.

**Comment by facelessuser** [comment]
@jtgrenz Are you sure you'r3 not mistaken about the examples you gave me?  I don't use ruby, but for the sake of my own curiosity I opened up an interactive ruby session on my mac and tried out your examples:

This didn't work as it would not evaluate until I entered an `end`:

```ruby
if condition then action
```

This worked great:

```
if condition then action end
```

Looking online, nobody seems to do it the way you mentioned, but they do it with the `end` at the end.

This is valid and works fine in BH, so nothing to be done here:

```ruby
some_action if condition
```

Again, this did not work in my session:

```ruby
unless condition some action
```

But this did work and is the way all examples online look.  BH handles this fine.

```ruby
some action unless condition
```

This is looking more like BH is handling things just good.  Please confirm as I intend to close this as your examples seem invalid.

**Comment by facelessuser** [comment]
I'll leave this open till the end of the week.  If I still haven't gotten a response, I will just close this.

**Comment by princemaple** [comment]
I think you can close this one. I code in Ruby everyday and have not seen problems with BH.

**Comment by facelessuser** [comment]
Good enough for me, thanks!
