### ISSUE TITLE
Highlight color-scheme font colors.

### ISSUE THREAD

**Issue by rhernandog** [facelessuser/BracketHighlighter#265]
Hi,

Great package, I've been able to configure it to use my own colors and stuff, really fun!!

What I'd like to do though, is to keep the current theme's font color scheme.

Also I'd like to know if it is possible to use a different color for the side icon.

Thanks,
Rodrigo.

**Comment by facelessuser** [comment]
When highlighting with `solid` sublime controls the font color.  I can't really control that well.  You can try setting background and foreground color in your theme, but I have found in the past that it doesn't work proper.  You can choose something like `underline`, and the color font should remain.  Sublime only changes the font color if the background is changed with `solid`.

**Comment by rhernandog** [comment]
Ok thanks.

For what I've read here, it seems that Sublime's API makes it really hard to mess with colors, any idea of why is that?.

Best,
Rodrigo.

**Comment by facelessuser** [comment]
In general, sublime lets you control the colors via the color scheme file by assigning color to scopes.  You assign scopes via the syntax file as that controls the the syntax highlighting.  From a programmers perspective it makes sense.  From a user's perspective it can be a little convoluted.

As far as losing control of the foreground when a background selection is set, this also kind of makes sense...a little.  Sublime  tries to ensure the foreground color is visible when a background **selection via the API** is set that is too similar.  It's approach is to always use the opposite color (inverted) from what I can tell which works in most cases, but sometimes I find it a little tough to read the text with certain combinations.  Like I said, you can play with it and see if in recent builds you can control both foreground and background, but in the past, I haven't really had much success.
