### ISSUE TITLE
High visibility only on tags/brackets/parenthesis

### ISSUE THREAD

**Issue by rhernandog** [facelessuser/BracketHighlighter#266]
Hi, me again bothering... ;)

I've found far more comfortable to toggle off the high visibility mode and set the content highlight bar to true. In that aspect this is more a request than an issue.

Would it be possible to use the toggle visibility mode to the opening and closing tags, sometimes is a bit confusing seeing all the content between the open/close elements with the high visibility style. So in the next example:
```html
<header>
  <section>
    <ul>
      <li>Lorem Ipsum</li>
      <li>Lorem Ipsum</li>
      <li>Lorem Ipsum</li>
    </ul>
  </section>
</header>
```
Have the vertical bar displaying over the content and high visibility on the <header> tags only (if you have the cursor inside those tags and not the entire content).

Thanks,
Rodrigo.

**Comment by facelessuser** [comment]
I don't really understand the request.  Can you elaborate more?

**Comment by rhernandog** [comment]
Hi,

The normal behaviour is this (using outline as option)
![bracket-h-request-1](https://cloud.githubusercontent.com/assets/4622323/9701506/9695333e-53fa-11e5-890c-6ad3e258721a.jpg)

What I'd like would be a combination of this and the standard highlight with the vertical line. Now it only creates an underline in the open and closing tags. Id' like to highlight like this (again using outline, but it would be nice to use any highlight option)
![bracket-h-request-2](https://cloud.githubusercontent.com/assets/4622323/9701516/fe31f5a4-53fa-11e5-9d01-6d74cdf780d1.jpg)

Hopefully is more clear now.

Also for the key codes, what function is the one that toggles the high visibility mode?. I'd like to create a short-cut for that.

Thanks,
Rodrigo.

**Comment by facelessuser** [comment]
If that is what you want, I would just turn on the content highlight style and use outline style for the tag brackets instead.  Then you don't even need high visibility mode.  I am afraid I have no intention of changing high visibility mode at this time.

**Comment by facelessuser** [comment]
I am assuming this is resolved.
