### ISSUE TITLE
Error message after last update (2.9.0)

### ISSUE THREAD

**Issue by Fabianred** [facelessuser/BracketHighlighter#267]
Hi,
Could you help me?
I had my own color scheme "Alexey.thTheme"
After last update (2.9.0) I have a lot of messages like on screen-shot below for each mouse click on the text area:

![image](https://cloud.githubusercontent.com/assets/9571591/9543147/158cd610-4d7f-11e5-9c80-4120d687ba52.png)

Why the plugin tries to load my color scheme from different location (from his own catalog)?

For proper work I have to duplicate my color scheme file to 
"c:\Users\%User_Name%\AppData\Roaming\Sublime Text 3\Packages\User\Color Highlighter\themes\Alexey.tmTheme"

The real location of my color scheme file is
"c:\Users\%User_Name%\AppData\Roaming\Sublime Text 3\Packages\Alexey.tmTheme"

**Comment by facelessuser** [comment]
I think you may be attributing something to BracketHighlighter that has nothing to do with BracketHighlighter.  BH doesn't touch tmThemes.  It doesn't try to load tmThemes.  If you look at the release notes for 2.9.0, none of the the changes has anything to do with tmThemes.  I think you are incorrectly attributing your problem with the BH updating.

**Comment by Fabianred** [comment]
thanks, sorry
