### ISSUE TITLE
unable to match HTML tag in certain cases

### ISSUE THREAD

**Issue by medifle** [facelessuser/BracketHighlighter#273]
system: OSX 10.10.5
sublime version: build 3083

I experienced a bug unable to match the corresponding HTML tag.
Here is a test file:
https://github.com/medifle/pj_umbrella/blob/dc1c9ab2f871558bf1139b6457aa2e43118b0649/index.html

bug occurs in line 147, 216, 217

![image](https://cloud.githubusercontent.com/assets/13296643/9935568/f44c3d72-5d89-11e5-8a3d-62635ec61f3b.png)

![image](https://cloud.githubusercontent.com/assets/13296643/9935561/e2ba427a-5d89-11e5-9132-fff34973a8a7.png)

**Comment by facelessuser** [comment]
This is not a bug.  Please see info about [search threshold](http://facelessuser.github.io/BracketHighlighter/customize/#search_threshold).  I personally use a value of about `10000`, you can pick what works best for you.  Allowing no limit can lead to performance issues in very large files.

**Comment by medifle** [comment]
I see...THX!
