### ISSUE TITLE
Help！How to add support for JSP on Sublime Text 3  Build 3083 ？

### ISSUE THREAD

**Issue by yangsaipp** [facelessuser/BracketHighlighter#274]
BH is great plugin, i like it very much! 
I am a java developer, so i need to add support for JSP when i find BH not work in jsp file on default config. i do what  #95  #180 said,  but problem is still, even work worse, plugin do not work  in all the other syntax, my  Sublime Text version is Sublime Text 3  Build 3083, what is wrong with me?

**Comment by yangsaipp** [comment]
anyone can help me ? @facelessuser

**Comment by facelessuser** [comment]
Without more specific information on what package you are using all I can do is reference you back to the issues you cited.  I would need to know a number of things before I can help:

- What package are you using for JSP and where can I acquire it?
- What config file did you edit and where did you put it?  People often edit the wrong file, or put the file in weird locations.
- What changes did you make?  People often don't edit things properly, or break the config file with invalid syntax.
- Do you see errors in the console?  This can sometimes be a big help as then you might see errors related to the breaking of the config file.

**Comment by yangsaipp** [comment]
Think you for reply,  more information is as follows:
*  I use Sublime Text 3(version:Build 3083) Package Contorl to install BH.
*  BH version is 2.9.1

BH work well in file on default config  except JSP file, The JSP page performance is as follows:
* Html tag can not Bracket Highlight when normal use.  you can refer to images at #95 
* "{ }"  symbol  work well

**Comment by yangsaipp** [comment]
I try to modify the configuration files as #95 said.
I use ST3 to edit preferances/package settings/bracket highlighter/bracket setting - user.
Add the following content:
```javascript
    {
    "brackets": [
        {
            "name": "html",
            "open": "(<)(?=[\\w\\:\\-]+(?:(?:\\s+[\\w\\-:]+(?:\\s*=\\s*(?:\"[^\"]*\"|'[^']*'|[^>\\s]+))?)*)\\s*\\/?>|\\/[\\w\\:\\-]+[^>]*>)",
            "close": "(?<=<)(?:[\\w\\:\\-]+(?:(?:\\s+[\\w\\-:]+(?:\\s*=\\s*(?:\"[^\"]*\"|'[^']*'|[^>\\s]+))?)*)\\s*\\/?|\\/[\\w\\:\\-]+[^>]*)(>)",
            "style": "tag",
            "scope_exclude": ["string", "comment"],
            "language_filter": "whitelist",
            "language_list": ["HTML", "HTML 5", "XML", "PHP", "JSP"],
            "plugin_library": "bh_modules.tags",
            "find_in_sub_search": "only",
            "enabled": false
        },
        {
            "name": "angle",
            "open": "(<)(?!\\?)",
            "close": "(?<!\\?)(>)",
            "style": "angle",
            "scope_exclude": ["string", "comment", "keyword.operator", "source.ruby.rails.embedded.html", "source.ruby.embedded.html"],
            "language_filter": "whitelist",
            "language_list": ["HTML", "HTML 5", "XML", "PHP", "HTML (Rails)", "HTML (Jinja Templates)", "HTML+CFML", "ColdFusion", "ColdFusionCFC", "JSP"],
            "plugin_library": "bh_modules.tags",
            "enabled": true
        }
    ]
}
```
however, it did not work

**Comment by facelessuser** [comment]
I need you to answer the questions I posted. #95 already tells you what you need to do.  For personalized help, I need you to answer those questions.  I can't tell you what you need to do unless I know **exactly** what JSP package you are using.  I can't tell you what's wrong with your configuration of you don't post your configuration.  I am happy to help if you can give me that info.

**Comment by yangsaipp** [comment]
so i reset my config file which i modify.
then i copy  preferances/package settings/bracket highlighter/bracket setting - Dafeult file content to  preferances/package settings/bracket highlighter/bracket setting - user,  and just modify  the angle rule that add Java Server Page to langue_list value. like this:
```javascript
{
            "name": "angle",
            "open": "(<)(?=[^?%]|$)",
            "close": "(?:(?<=[^?%])|(?<=^))(>)",
            "style": "angle",
            "scope_exclude": [
                "string",
                "comment",
                "keyword.operator",
                "source.ruby.rails.embedded.html",
                "source.ruby.embedded.html"
            ],
            "language_filter": "whitelist",
            "language_list": [
                "HTML",
                "HTML 5",
                "XML",
                "PHP",
                "HTML (Rails)",
                "HTML (Jinja Templates)",
                "HTML (Twig)",
                "HTML+CFML",
                "ColdFusion",
                "ColdFusionCFC",
                "laravel-blade",
                "Handlebars",
                "AngularJS",
                "Java Server Page"
            ],
            "plugin_library": "bh_modules.tags",
            "enabled": true
        },
```
it also did not work

**Comment by yangsaipp** [comment]
You can use this simple error.jsp for testing:

**Comment by yangsaipp** [comment]
```html
<html>
<head>
    <!-- Meta Tags -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>error page</title>
</head>
<body>
<p>This is error page</p>
</body>
</html>
<div class="wrapper">
    <div class="header"></div>
</div>
```

**Comment by yangsaipp** [comment]
Thanks for your careful reply.  
SB3 console no error message.

**Comment by facelessuser** [comment]
Please point me to the JSP package you use.

**Comment by yangsaipp** [comment]
Thinks, the JSP package what you said mean ?  

The JSP is mixed by javascript and html.

if you want to get a jsp pape to test, you can do this:
Create a call error. JSP file on SB3, and copy this text
```JSP
<html>
<head>
    <!-- Meta Tags -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>error page</title>
</head>
<body>
<p>This is error page</p>
</body>
</html>
<div class="wrapper">
    <div class="header"></div>
</div>
```

**Comment by facelessuser** [comment]
I mean where is the repository?  Where do I get the package?

**Comment by facelessuser** [comment]
I looked in the default packages, and I see this language `Java Server Pages (JSP).sublime-syntax`, I will assume you are using this.  I am on ST3 3095, so I don't know if it is different for you.

**Comment by yangsaipp** [comment]
Thank you for help me!
 i think ST3 3095 is ok , so can you test error.jsp? do BH work well?

**Comment by facelessuser** [comment]
If this were a pull request, you would modify the `angle` rule directly in default settings file, but I will show you how to override the `angle` rule in your User config locally.  See [documentation](http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management) for more info.

The documentation above states that you use the syntax file name.  So if your language is called `My Language.tmLanguage` or `My Language.sublime-syntax`, you would use the name `My Language`.

So assuming 3095's `Java Server Pages (JSP).sublime-syntax`, you use as the name `Java Server Pages (JSP)`.

**Packages/User/bh_core.sublime-settings**:

```js
{
    "user_brackets": [
        // Modified angle with JSP.  I just need the name of the rule I am overriding
        // and the key or keys I want to override.
        {
            "name": "angle",
            "language_list": [
                "HTML",
                "HTML 5",
                "XML",
                "PHP",
                "HTML (Rails)",
                "HTML (Jinja Templates)",
                "HTML (Twig)",
                "HTML+CFML",
                "ColdFusion",
                "ColdFusionCFC",
                "laravel-blade",
                "Handlebars",
                "AngularJS",
                "Java Server Pages (JSP)"  // <--- My new language
            ]
        }
    ]
}
```

**Packages\User\bh_tag.sublime-settings:**

```js
{
    // Remember, the HTML tags are handled by a bh_plugin called `tag`.
    // Recent versions of BH have moved the tag settings into their own settings file.
    // Here is where you define what tag mode will be used.
    "tag_mode": {
        "xhtml": ["XML"],
        "html": [
            "HTML",
            "HTML 5",
            "PHP",
            "HTML (Jinja Templates)",
            "HTML (Rails)",
            "HTML (Twig)",
            "laravel-blade",
            "Handlebars",
            "AngularJS",
            "Java Server Pages (JSP)"   // <-- My new HTML tag mode language.
        ],
        "cfml": ["HTML+CFML", "ColdFusion", "ColdFusionCFC"]
    }
}
```

I tired it out and it works fine.

**Comment by yangsaipp** [comment]
Thank you very much, really.  haha, now BH work well. 

ps:  **Packages\User\bh_tag.sublime-settings**  you must create by youself not ST3.

the [Document](http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management) is very good. if have some example will be best. 

BTW: I want to know How to find  the default packages that you said. Thanks a lot.

**Comment by facelessuser** [comment]
https://packagecontrol.io/packages/PackageResourceViewer allows you to navigate the default packages and see what is inside them.
