### ISSUE TITLE
Add HTML Mustache to the list angle brackets

### ISSUE THREAD

**Issue by wwhtoledo** [facelessuser/BracketHighlighter#278]
It would be nice if you could you add HTML Mustache (HTML with mustaches?) to the language list for angle brackets.

**Comment by facelessuser** [comment]
I take pull requests. http://facelessuser.github.io/BracketHighlighter/contributing/#overview.

**Comment by wwhtoledo** [comment]
Hmm, I thought it should have work if I just added the user_brackets with the new language set as "HTML with mustaches" as described in docs here: http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management.

**Comment by facelessuser** [comment]
For personal use, that user_brackets is the way to go.  For pull requests, you edit the default rule.

Now the common mistake is people look at the text in the bottom right hand corner of the editor and enter that, but BracketHighlighter uses the **actual file name** (minus the extension) of the syntax being used.  That is not always the same as the **display name**.

**Comment by wwhtoledo** [comment]
Oh, ok. Is sorta working now, except is using the angle brackets style instead of the HTML tag. Is there a way to tell it to use the tag style?

**Comment by facelessuser** [comment]
So, the tag highlighting is a bh_plugin attached to the angle bracket rule.  bh_plugins will keep their own settings, so check out `bh_tag.sublime-settings`.

**Comment by wwhtoledo** [comment]
Cool. That worked! Thanks. Btw, awesome plugin.
