### ISSUE TITLE
Laravel Blade template is not included in highlighting

### ISSUE THREAD

**Issue by churiart** [facelessuser/BracketHighlighter#281]
Hi, according to [this issue](https://github.com/facelessuser/BracketHighlighter/issues/124) I can confirm HTML highlighting is no more available in `.blade.php` files. I checked template file of blade it is `Blade.tmLanguage`, then I added  `Blade` to `Angel` type `language_list` list but couldn't have highlighting yet. Any ideas?
Thanks

**Comment by facelessuser** [comment]
See here https://github.com/facelessuser/BracketHighlighter/issues/278#issuecomment-149745836.  You will need to add blade to the bh_tag settings as well.

**Comment by churiart** [comment]
Adding `blade` to both `bh_tag.sublime-settings` and `bh_core.sublime-settings` solved issue. Thanks

**Comment by techns27** [comment]
Its still not working for me.
Its already in both the settings file.

Any suggestion ?

**Comment by facelessuser** [comment]
I'm most likely still waiting on a pull request from the community.  People have found their answer, but no one has bothered to issue a pull request to help out others.

**Comment by facelessuser** [comment]
Let me clarify.  I don't know if you are using the same blade syntax highlighters as mentioned earlier in this thread or in duplicate issues.  If you need further support you are going to have to point me at the blade package you are using and pay your actual settings.  It could be your highlighter is different and needs a new entry in your settings.  Or your settings could be corrupt.  I just don't have enough info in your post.

**Comment by tvercruysse** [comment]
hi, Blade is part of the laravel PHP framework. This is about the only maintained blade syntax package atm : https://github.com/medalink/laravel-blade

**Comment by tvercruysse** [comment]
I fixed it for me, the syntax name changed from laravel-blade.syntax to blade.syntax, you included "blade" as an option in bh_tag.sublime settings but not in bh_core.sublime settings.

In `Preferences->package-settings->BracketHighLighter->Bracket settings - user`
Search for `"laravel-blade",` hit enter, paste `"blade",`

**Comment by facelessuser** [comment]
I leave language support up to the community.  Language changes should be made via pull requests.  If updating, make sure you don't break existing support.
