### ISSUE TITLE
Overlap of BH underline and ac

### ISSUE THREAD

**Issue by davlung** [facelessuser/BracketHighlighter#282]
When my cursor is next to a } or ), the red underline of BH overlaps with sublime's gray underline (I'm guessing this is the case). Please see image:
![image](https://cloud.githubusercontent.com/assets/1403282/10901542/56c0d28a-81a5-11e5-8549-559f7f4a6489.png)

When I click outside the active sublime window, it displays correctly:
![image](https://cloud.githubusercontent.com/assets/1403282/10901553/9a3f6d00-81a5-11e5-8877-3cf600adbfe1.png)

You see the red underline is more thick b/c sublime's gray underline isn't interfering!
Thanks!

**Comment by facelessuser** [comment]
If you are using bracket highlighter, you probably want to disable Sublime's default highlighter.  What you are seeing is bracket highlighters highlighting AND sublimes.  I would pick one or the other.

**Comment by davlung** [comment]
Thank you, it worked!

I just went to Preferences -> Settings-User

And added the following:
"match_brackets": false
