### ISSUE TITLE
user_brackets treats `\l` differently 

### ISSUE THREAD

**Issue by randy3k** [facelessuser/BracketHighlighter#283]
I have the following `user_brackets`, these backslash commands are common in latex. 

```json
    "user_brackets": [
    {
        "name": "latex_test1",
        "open": "(\\\\a)",
        "close": "(\\\\b)",
        "style": "default",
        "language_filter": "whitelist",
        "language_list": ["Plain Text"],
        "scope_exclude": ["comment"],
        "find_in_sub_search": "true",
        "enabled": true
    },
    {
        "name": "latex_test2",
        "open": "(\\\\k)",
        "close": "(\\\\l)",
        "style": "default",
        "language_filter": "whitelist",
        "language_list": ["Plain Text"],
        "scope_exclude": ["comment"],
        "find_in_sub_search": "true",
        "enabled": true
    }
```

![screen shot 2015-11-03 at 5 33 16 pm](https://cloud.githubusercontent.com/assets/1690993/10923883/59097d92-8251-11e5-8ff2-ed1ad6453c5a.png)

In `\b`, the backslash is highlighted, however, in `\l`, only the char `l` is highlighted. I have tried different letters, it seems that it is only a problem of `\l`...

**Comment by facelessuser** [comment]
It's because of this http://facelessuser.github.io/BracketHighlighter/extended-regex/.  I need to revisit and test out the search backrefs more; looks like I simply didn't test them well enough.  You can get around it in the mean time by doing `(\\\\\\\\l)`.

**Comment by facelessuser** [comment]
Okay, I understand why you are getting the odd results, it will take me a couple of days before I can even sit down to fix this.

Just be aware that you will run into this issue with `l`, `L`, `c`, `C`.  In some scenarios you may also see this with `p` and `P`.

**Comment by facelessuser** [comment]
oh and `Q` and `E`.

**Comment by facelessuser** [comment]
Actually had a little time and it wasn't that bad.  My unittests for backrefs was incorrect which in turned caused some bad logic to be added.  I should have a fix posted here soon.

**Comment by randy3k** [comment]
Great, it works now. Thanks for the prompt fix.

**Comment by facelessuser** [comment]
Should be in new release https://github.com/facelessuser/BracketHighlighter/releases/tag/st3-2.10.0.  A release was well over due.
