### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by iamntz** [facelessuser/BracketHighlighter#285]
Hi!

I don't know if is solely BH fault or is a combination with other plugin, but sometimes the editor becomes *very* slow. Like 2-3 seconds for undo, save or tab switching.

Restarting editor often helps (but there are some times when it doesn't) and disabling BH plugin is always helping (re-enabling has unpredictible results; sometimes it becomes slows, sometimes is fast again).

I'm the only one who get this issue?

I'm having a lot of plugins installed, I tried to disable those that i thought it will affect performance (e.g. buffer scroll), but BH was the only one i found it.

This is my BH config:

```
{
    "search_threshold": 1000,
    "bracket_outside_adjacent": false,
    "no_multi_select_icons": true,
    "debug_enable": false,
    "align_content_highlight_bar": true,
}
```

I'm on W10 x64 with 3095 build.

**Comment by facelessuser** [comment]
Have you tried things with just BH?  I am also not sure what other plugins you are using with BH.  Your threshold is pretty small too, so you aren't being aggressive.

Is this also a new problem you are seeing?  Like how long have you experienced these issues?

**Comment by iamntz** [comment]
I think it's over a month.

Disabling every single other plugin would be a pain in both terms of actually disabling them (they are quite a lot) and in terms of functionality.

I was hoping that there is something other experienced as well :D

**Comment by facelessuser** [comment]
Try a portable version maybe.  I'll take a look and see what has been introduced and such, but with such a vague problem description, I can't promise anything.  It would be nice if you could isolate a test case that I can reproduce; without one, unless I start experiencing it, there may be nothing I can do.

**Comment by facelessuser** [comment]
You can also try manually rolling back to a previous release and see if one of them improves things.  If performance is only sometimes poor, then knowing something like it goes down the longer it runs would be helpful.  I doubt it's leaking memory, but any context would be nice.

**Comment by facelessuser** [comment]
Oh, and post your plugin list.

**Comment by facelessuser** [comment]
Maybe roll back to https://github.com/facelessuser/BracketHighlighter/releases/tag/st3-2.7.1 and see if that helps.  Only one major change was introduced after that release.  If that doesn't help, you might be targeting the wrong plugin.

**Comment by iamntz** [comment]
That's the problem, I often have DAYS without issues. It's very hard to isolate (and running for days without any package would be impossible for me)

**Comment by facelessuser** [comment]
It's sounding less like BH with every post :smile:.

**Comment by facelessuser** [comment]
I'll leave this open for a bit to see if more people comment.  I am not experiencing your issue, and I leave my editor open for days.  There is little hard evidence at this point that BH has any real part in this issue, but I will wait to see if more people come to complain about BH's performance.

**Comment by facelessuser** [comment]
I'm still not seeing performance issues, and I haven't heard of others having performance issues.  I am going to close this for now.
