### ISSUE TITLE
Disable ST default bracket highlighting

### ISSUE THREAD

**Issue by saulhudson** [facelessuser/BracketHighlighter#286]
Hi

Is there a setting I'm missing to disable the default ST bracket highlighting as with BracketHightlighter installed I get both.

![untitled](https://cloud.githubusercontent.com/assets/789556/11237067/6cfa6912-8dd5-11e5-95f0-0861bd0f6082.png)

**Comment by princemaple** [comment]
```
"match_brackets": true,
```
override it with `false`
