### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MichaelCaley** [facelessuser/BracketHighlighter#289]
Hello I am new to Github, so perhaps I am making a mistake. However when following the installation instructions I finish installing the package control and then open the list of installable plugins, but am unable to locate the bracket high lighter.

When that didn't work I dragged the unzipped installation files into the packages folder and then was able to find something on the plugins list, but none of them were obvious choices.

Further instructions would be hugely appreciated.

**Comment by facelessuser** [comment]
> Hello I am new to Github, so perhaps I am making a mistake. However when following the installation instructions I finish installing the package control and then open the list of installable plugins, but am unable to locate the bracket high lighter.

It's BracketHighlighter, and it is there.  Do you see other packages?  Did you restart after installing Package Control?

> When that didn't work I dragged the unzipped installation files into the packages folder and then was able to find something on the plugins list, but none of them were obvious choices.

I would use Package Control as you are going to probably install more packages and want to keep them up to date.

**Comment by facelessuser** [comment]
Feel free to ask more questions if you are still confused, but I suspect you are just having issues with using Package Control as PC is the most common way BracketHighlighter is installed.  Restarting Sublime will most likely get you were you need to be unless PC didn't instal correctly (in that case I would reinstall PC).
