### ISSUE TITLE
ImportError: No module named 'backrefs'

### ISSUE THREAD

**Issue by liuhewei** [facelessuser/BracketHighlighter#293]
Recently, the new version of BracketHighlighter can't work on my PC. Here is the error:  
```
File "C:\Users\lhw\AppData\Roaming\Sublime Text 3\Packages\BracketHighlighter\bh_rules.py", line 7, in <module>
    from backrefs import bre
ImportError: No module named 'backrefs'
```

I notice that there is a sub-directory called "backrefs" under BracketHighlighter package, now it's no longer there. Is this the reason?

**Comment by liuhewei** [comment]
I don't use packagecontrol. I just use "git clone" style installation. After "git checkout st3-2.10.1" (the newest release), everything is back to normal. I assume the `backrefs `module is missing in master branch.

**Comment by facelessuser** [comment]
You should use package control as BH now relies on Package Control dependencies to get backrefs.  This is so I can update backrefs in one place and all plugins that really on it can get the update.  This means less work for me.

**Comment by facelessuser** [comment]
FYI, I would install Package Control, restart, and then run "Satisfy Dependencies".  Restart may be needed after dependencies install.

**Comment by liuhewei** [comment]
@facelessuser Thanks for the explanation. I didn't install package control because of the network problem. I'll try to re-use it.

**Comment by facelessuser** [comment]
I hope it works out for you.  I was really just trying to make things easier on myself.  I hadn't considered that it may adversely certain people.

If you are really having trouble, I think we can come up with something to get it going.  The backrefs dependency is [here](https://github.com/facelessuser/sublime-backrefs).  You just have to get it to add the `st3` folder to the system path before BH gets loaded so it can find the backrefs module.  This can probably be done with a very simple plugin.  If this is the way you need to go, let me know and maybe I can help out.

**Comment by maliayas** [comment]
For python noobs like me, it's worth to note these steps:

1. Download/clone https://github.com/facelessuser/sublime-backrefs to somewhere
2. Move `st3/backrefs` to `Packages/backrefs` or make a sym link such that `Packages/backrefs/bre.py`, `Packages/backrefs/bregex.py`, etc. exists.

**Comment by facelessuser** [comment]
Thanks for the details.  I am really not sure the number of people not using Package Control.  I imagine it is a very small percentage, but it is good to at least have this info for those people.

**Comment by maliayas** [comment]
Probably very little. In my case, I use git for all the packages, so that I can control updates perfectly and make modifications to the package otherwise not possible. ST allow to override some stuff but apparently it's not as powerful as a git repo.

**Comment by facelessuser** [comment]
For those who want to install BH without package control, here are the steps.  I will put this in the official docs when I get a chance.

---

Download the latest releases of the following dependencies and unpack in the `Packages` folder as shown below:

- https://bitbucket.org/teddy_beer_maniac/sublime-text-dependency-markupsafe -> markupsafe
- https://bitbucket.org/teddy_beer_maniac/sublime-text-dependency-jinja2 -> python-jinja2
- https://github.com/packagecontrol/pygments -> pygments
- https://github.com/facelessuser/sublime-markdown-popups -> mdpopups
- https://github.com/facelessuser/sublime-markdown -> python-markdown
- https://github.com/facelessuser/sublime-backrefs -> backrefs

Get the latest BracketHighlighter release and unpack as `BracketHighlighter`:

- https://github.com/facelessuser/BracketHighlighter -> BracketHighlighter

Create a folder under `Packages` called `00-dependencies` and under that folder create a file called `00-dependencies.py`:

Copy the following code to `00-dependencies.py` (this code was taken from Package Control):

```python
import sys
import os
from os.path import dirname

if os.name == 'nt':
    from ctypes import windll, create_unicode_buffer

import sublime


if sys.version_info >= (3,):
    def decode(path):
        return path

    def encode(path):
        return path

    if os.path.basename(__file__) == 'sys_path.py':
        pc_package_path = dirname(dirname(__file__))
    # When loaded as a .sublime-package file, the filename ends up being
    # Package Control.sublime-package/Package Control.package_control.sys_path
    else:
        pc_package_path = dirname(__file__)
    st_version = u'3'

else:
    def decode(path):
        if not isinstance(path, unicode):
            path = path.decode(sys.getfilesystemencoding())
        return path

    def encode(path):
        if isinstance(path, unicode):
            path = path.encode(sys.getfilesystemencoding())
        return path

    pc_package_path = decode(os.getcwd())
    st_version = u'2'


st_dir = dirname(dirname(pc_package_path))


def add(path, first=False):
    """
    Adds an entry to the beginning of sys.path, working around the fact that
    Python 2.6 can't import from non-ASCII paths on Windows.

    :param path:
        A unicode string of a folder, zip file or sublime-package file to
        add to the path

    :param first:
        If the path should be added at the beginning
    """

    if os.name == 'nt':
        # Work around unicode path import issue on Windows with Python 2.6
        buf = create_unicode_buffer(512)
        if windll.kernel32.GetShortPathNameW(path, buf, len(buf)):
            path = buf.value

    enc_path = encode(path)

    if os.path.exists(enc_path):
        if first:
            try:
                sys.path.remove(enc_path)
            except (ValueError):
                pass
            sys.path.insert(0, enc_path)
        elif enc_path not in sys.path:
            sys.path.append(enc_path)


def remove(path):
    """
    Removes a path from sys.path if it is present

    :param path:
        A unicode string of a folder, zip file or sublime-package file
    """

    try:
        sys.path.remove(encode(path))
    except (ValueError):
        pass

    if os.name == 'nt':
        buf = create_unicode_buffer(512)
        if windll.kernel32.GetShortPathNameW(path, buf, len(buf)):
            path = buf.value
        try:
            sys.path.remove(encode(path))
        except (ValueError):
            pass


def generate_dependency_paths(name):
    """
    Accepts a dependency name and generates a dict containing the three standard
    import paths that are valid for the current machine.

    :param name:
        A unicode string name of the dependency

    :return:
        A dict with the following keys:
         - 'ver'
         - 'plat'
         - 'arch'
    """

    packages_dir = os.path.join(st_dir, u'Packages')
    dependency_dir = os.path.join(packages_dir, name)

    ver = u'st%s' % st_version
    plat = sublime.platform()
    arch = sublime.arch()

    return {
        'all': os.path.join(dependency_dir, 'all'),
        'ver': os.path.join(dependency_dir, ver),
        'plat': os.path.join(dependency_dir, u'%s_%s' % (ver, plat)),
        'arch': os.path.join(dependency_dir, u'%s_%s_%s' % (ver, plat, arch))
    }


def add_dependency(name, first=False):
    """
    Accepts a dependency name and automatically adds the appropriate path
    to sys.path, if the dependency has a path for the current platform and
    architecture.

    :param name:
        A unicode string name of the dependency

    :param first:
        If the path should be added to the beginning of the list
    """

    dep_paths = generate_dependency_paths(name)

    for path in dep_paths.values():
        if os.path.exists(encode(path)):
            add(path, first=first)


add_dependency('pygments')
add_dependency('backrefs')
add_dependency('markupsafe')
add_dependency('python-markdown')
add_dependency('python-jinja2')
add_dependency('mdpopups')

```

Restart and enjoy.

---

You will have to keep all the packages updated yourself.
