### ISSUE TITLE
Is it possible to hide mark in gutter?

### ISSUE THREAD

**Issue by coodoo** [facelessuser/BracketHighlighter#294]
It would be prefect to be able to toggle it on/off as needed, thanks!

**Comment by facelessuser** [comment]
You will need to read this: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style.

Particularly where you configure the gutter icon.  If you want a command that toggles the gutter, you may need to write your own command to automate the change.

**Comment by coodoo** [comment]
Prefect, that did the trick, thanks for helping out!
