### ISSUE TITLE
In some cases "content_highlight_bar" is dashed

### ISSUE THREAD

**Issue by r44083** [facelessuser/BracketHighlighter#296]
When options "content_highlight_bar" and "align_content_highlight_bar" are true, and between brackets there are empty lines - BracketHighlighter plugin drows dashed line (see the screenshot below). I think that this line should be solid regardless of the availability of empty lines.

!["content_highlight_bar" is dashed](https://habrastorage.org/files/274/e2c/627/274e2c6273df446b968e8dc697941e54.png)

**Comment by facelessuser** [comment]
I'll just leave these right here:

- http://facelessuser.github.io/BracketHighlighter/customize/#content_highlight_bar
- http://facelessuser.github.io/BracketHighlighter/customize/#align_content_highlight_bar

**Comment by r44083** [comment]
I understood. Thank you for the explanation. Hopefully future Sublime Text versions will add missing API.
