### ISSUE TITLE
Brackets not recognized when too much lines

### ISSUE THREAD

**Issue by MaadMax** [facelessuser/BracketHighlighter#304]
When my files has a lot of lines, Brackethighlighter doesn't recognize the opening/closing tags/brackets... and so on whereas atom find them well. Is there any way to fix it? 

Here's an example (indented by atom, so all is at his place)
![image](https://cloud.githubusercontent.com/assets/5319267/12394118/360030fe-bdfa-11e5-9b35-60adf87851de.png)

**Comment by facelessuser** [comment]
This is a frequently asked question: see [here](https://github.com/facelessuser/BracketHighlighter/issues/300).
