### ISSUE TITLE
cannot override settings

### ISSUE THREAD

**Issue by asdf23** [facelessuser/BracketHighlighter#306]
I have a bh_core.sublime-settings file in my Packages/User directory. No setting that I set here is reflected in the actual GUI.

**Comment by facelessuser** [comment]
Without more info or examples, I am afraid I cannot offer assistance.  Please be more specific with examples.  As I personally use a `bh_core.sublime-settings` in my own setup, I can confirm that it **does** work.

If you haven't already, I would take a look at the documentation as it may answer your questions: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-brackets.

**Comment by facelessuser** [comment]
I will give this issue another week for you to give more details then I will have to close it if I don't hear anything.

**Comment by asdf23** [comment]
I apologize I had some things come up and could not get back to this. I'll include my settings file tomorrow. I had a unrelated error with an unrelated package and found an issue with a corrupted file, perhaps that was causing the same issue here as well.  Again sorry for the delay.

**Comment by asdf23** [comment]
Here is my bh_core.sublime-settings file.  And a screenshot of what I am seeing below.
```
{
	 "show_in_minimap": true
	,"show_unmatched": true
	,"align_content_highlight_bar": true
	//solid, outline, underline, thin_underline, squiggly, and stippled.
	,"high_visibility_style": "outline"
}
```

**Comment by facelessuser** [comment]
So, what are you expecting?  I think this is a case of misunderstanding what the settings do.

**Comment by asdf23** [comment]
In the image beneath the quotation marks surrounding "outline" I see a underline mark. I am expecting to see a square surrounding "outline". Also if I change the file say to squiggly I expect to see squiggly lines instead of the underline. Also I assume that there should be some sort of indicator in the minimap area, I do not see any change to the minimap.

**Comment by facelessuser** [comment]
You need to read the documentation; specifically http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style.

You are trying to change the high visibility look, but you don't have high visibility enabled.  That is why you see no change.  Please follow the link and read the documentation about changing the highlight style.
