### ISSUE TITLE
Feature Request : Highlight bracket even if not in the visible area

### ISSUE THREAD

**Issue by meetjaydeep** [facelessuser/BracketHighlighter#307]
If the matching bracket is not in the visible area then also highlight the matching bracket by showing it in the popup.
Similar functionality is available in Visual studio.

![image](https://cloud.githubusercontent.com/assets/1770120/12913181/2905bd06-cf43-11e5-9f7f-011c6926a4ed.png)

**Comment by facelessuser** [comment]
I don't understand what you are requesting.   Can you elaborate?

**Comment by facelessuser** [comment]
I will leave this issue open for another week, and if there is no response, I will just close it.

**Comment by meetjaydeep** [comment]
I'll explain in detail.
In Visual Studio if you see the 1st screenshot you will notice the bracket highlighted which is similar to Sublime text

![image](https://cloud.githubusercontent.com/assets/1770120/13210738/231d1992-d958-11e5-9844-ddde6ff74696.png)

In Screenshot 2 opening bracket is not visible but still the bracket highlighter shows it as the popup/tooltip.

![image](https://cloud.githubusercontent.com/assets/1770120/13210757/5185bca8-d958-11e5-80ec-23b8c2a4768d.png)

If you compare the similar thing with the Sublime text the 2nd case is missing

![image](https://cloud.githubusercontent.com/assets/1770120/13210766/63ce5636-d958-11e5-98f9-33a6196310ce.png)

![image](https://cloud.githubusercontent.com/assets/1770120/13210767/66ec6650-d958-11e5-980c-c9108c64a097.png)

**Comment by facelessuser** [comment]
Okay, I at least understand now.  This gets more complicated with multi-cursors.  And what to do if both brackets are off screen (sublime I think will only allow one tooltip).

The tooltip API is a little limited, but I think it is possible.  I personally think this would get in my way.  I might be okay with it if it were on demand.

I'm not going to promise anything, but I won't quickly dismiss it either.  Let me think about it, possibly play with some ideas.  Worse case scenario, I will pass, but maybe something will come out of this.

**Comment by facelessuser** [comment]
This may actually be possible now with Sublime's new hover event.

The plan is to allow a popup to show on mouseover of the shown bracket **if** the other matched bracket is off the screen.  There will also be a link to jump to the offscreen bracket in the popup.

This is experimental and is not guaranteed to make it in or remain.  But I think I may code something up under a setting (disabled by default) and let people try it out and see if it is worth keeping.

**Comment by facelessuser** [comment]
The experimental feature is now in [st3-2.18.0 release](https://github.com/facelessuser/BracketHighlighter/releases/tag/st3-2.18.0).  You will have to enable it in you settings file and you have to be on ST3 dev build 3116+ (recommend 3117).

I will consider this closed, but feel free to give feedback on the feature.  Whether it sticks around as a permanent feature will depend on how it is received.

**Comment by alexanderadam** [comment]
@facelessuser how is the name of the setting if I may ask?

**Comment by facelessuser** [comment]
@alexanderadam, this is covered in the documentation: http://facelessuser.github.io/BracketHighlighter/usage/#find-matching-offscreen-brackets.

**Comment by alexanderadam** [comment]
Thank you for the fast response. So it's `show_offscreen_bracket_popup`.
