### ISSUE TITLE
Crashing on specific XML

### ISSUE THREAD

**Issue by daanvosdewael** [facelessuser/BracketHighlighter#308]
I'm working in a XML document that has attributes with dot's in them:

```xml
<element attr.value="100"/>
```

Directly opening the file yields no problems, but opening the file inside a project crashes ST. `plugin_host` cpu usage goes to 100%.
Removing the attributes with the dot's or disabling the plugin fixes the problem.

OS X 10.11.3
Sublime Text 3 build 3103
BracketHighlighter v2.11.1

**Comment by facelessuser** [comment]
Example coffee snippet I can test,  or is all that is needed is a file with that one line?

**Comment by facelessuser** [comment]
Oh, also tell me what XML package you are using.

**Comment by daanvosdewael** [comment]
I encountering it while working on a project that uses [krpano](http://krpano.com/). [This](https://gist.github.com/daanvosdewael/bfdee206db9d8cc945c5) is included in one of the config files. If you save that as an .xml en try to open it, ST crashes.

Not sure what you mean with 'XML package'. I guess just the standard one that comes with ST?

**Comment by facelessuser** [comment]
Also, OS?

**Comment by daanvosdewael** [comment]
Mac OS X 10.11.3

**Comment by facelessuser** [comment]
I'll see if I can reproduce.

**Comment by facelessuser** [comment]
Are dots even allowed in the attributes in the XML spec?  I know my syntax highlighter isn't allowing them?

I am experiencing a hang which needs to be addressed, but I am not even sure if dots in the attribute name are formally allowed (obviously this may differ depending the parser, but I am talking officially).  I haven't been able to locate yet the exact spec on this yet.

**Comment by facelessuser** [comment]
In any case, it looks like the tag detection regex isn't efficient enough.  I will at least look into a regex that is better in these non-ideal cases.

**Comment by daanvosdewael** [comment]
Yeah, when I saw the syntax I thought the same. But it's being used by that panorama framework. So I don't really have a choice if it's valid or not.

Thanks for checking out my edge-case…
