### ISSUE TITLE
Feature request: nested icons in left hand area

### ISSUE THREAD

**Issue by asdf23** [facelessuser/BracketHighlighter#309]
I'm not sure how much Sublime is setup to allow you to do this. But it would be awesome if you could show the entire history of nesting. Perhaps showing an ellipsis "..." if some threshold is met. Attached is an image of what I was thinking. The code to the right of the image does not match what the icons should show in the left, it was just thrown together.

![bh_featurerequest](https://cloud.githubusercontent.com/assets/4165735/12956709/1cdcf530-cfde-11e5-8e89-62992d43a0a2.png)

**Comment by facelessuser** [comment]
I am afraid that the current design of BH will not allow such a feature.  BH focuses on one pair and one pair only to accomplish its different tasks.  At the present, I do not have a desire to rewrite the framework.  I appreciate the suggestion, but at this time, I will have to decline.
