### ISSUE TITLE
Not highlighting between brackets

### ISSUE THREAD

**Issue by va01** [facelessuser/BracketHighlighter#313]
I can't get the package to highlight the lines in between brackets, the package's main intended function.

**Detailed description of the problem**
The lines between brackets are not being highlighted:
![no highlights btw brackets](https://cloud.githubusercontent.com/assets/12104721/13181124/15ad45fc-d6f1-11e5-8191-e90126adac38.png)

In case it's informative, here are my Sublime preferences:
![sublime prefs](https://cloud.githubusercontent.com/assets/12104721/13181134/22bd53ae-d6f1-11e5-9b20-2fcd47ecaf94.png)

**What I've tried**
I figure I must be doing something stupid but I've tried the following:

1. toggling `"high_visibility_enabled_by_default": true` between `true` and `false` as well as commenting it out
2. restarting sublime after above toggles

**System Info.:**
Sublime Text build: 3103
Operating system: OS X, El Capitan, Version 10.11.3 (15D21)

**Comment by facelessuser** [comment]
Did you put this in `Preferences.sublime-settings`?  If so, that is a big misunderstanding.  If you read the documentation it mentions that the settings file is `bh_core.sublime-settings`: http://facelessuser.github.io/BracketHighlighter/customize/#core-settings.

You need to create a `bh_core.sublime-settings` file in your User folder and override the settings in that file.  Please the read the documentation for more info.

**Comment by va01** [comment]
Thank you. This solved my problem.

  

I did open the documentation but I mistakenly overlooked the first paragraph
on creating the bh_core.sublime-settings file. Thanks and I apologize for the
inconvenience.

> On Feb 19 2016, at 11:02 am, Isaac Muse &lt;notifications@github.com&gt;
wrote:  

>

> Did you put this in `Preferences.sublime-settings`? If so, that is a big
misunderstanding. If you read the documentation it mentions that the settings
file is `bh_core.sublime-settings`:
<http://facelessuser.github.io/BracketHighlighter/customize/#core-settings>.

>

> You need to create a `bh_core.sublime-settings` file in your User folder and
override the settings in that file. Please the read the documentation for more
info.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/faceles
suser/BracketHighlighter/issues/313#issuecomment-186304397).![](https://github
.com/notifications/beacon/ALi0EQs0X7tWNrFcwZvK2gbZtvMh0C5Lks5pl0HsgaJpZM4HeHIb
.gif)

**Comment by facelessuser** [comment]
Glad you got it figured out.
