### ISSUE TITLE
Feature request: swapquotes - add backtick (`) as another quote type

### ISSUE THREAD

**Issue by elado** [facelessuser/BracketHighlighter#314]
Currently only `'` and `"` are supported. With the rise of ES6,  a backtick "`" has become popular too.

**Comment by facelessuser** [comment]
As stated in the [docs](http://facelessuser.github.io/BracketHighlighter/contributing/), support for bracket rules is provided by the community (unless it is in a language I specifically use).  Pull requests are welcome.  I don't mind offering guidance or suggestions if you get stuck while trying to implement the rule for a pull request.  Feel free to ask questions.

**Comment by facelessuser** [comment]
I will go ahead and close this in anticipation of a pull request.  Again, if you decide to tackle the pull request and have questions, please feel free to ask.  I am willing to help, I just don't have time to familiarize myself with all the nuances of different languages that I don't use.
