### ISSUE TITLE
Feature Request: Directly jump behind bracket

### ISSUE THREAD

**Issue by r-stein** [facelessuser/BracketHighlighter#315]
I think it would be useful to jump directly behind the matching brackets. Currently it is only possible (?) to jump at the inside of the bracket and afterwards to the outside of the bracket. This requires 2 keystrokes and I think it would be helpful to create an option to reduce this to 1.

To demonstrate, which action I am speaking of:

![bh_jump_right](https://cloud.githubusercontent.com/assets/12573621/13317254/b1970620-dbb4-11e5-95e6-0e965153c528.gif)

The executed action is available with `BracketHighlighter: Jump to Right Bracket`.

**Comment by facelessuser** [comment]
I will have to check if this is currently possible by tweaking settings.  I can't remember as I have had people request various different bracket jumping behavior (some possible in the current architecture, some not).

I see nothing impossible with your request.  I will probably leave the current behavior as is by default.

If it is not currently possible with current selection bh_plugin, you may need to create a custom bh_plugin for our purposes.  As I am pretty busy right now, my best suggestion is to create a bh_plugin based off the original selection bh_plugin: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_modules/bracketselect.py. Place that in a folder in `User\bh_modules`.  You can modify your custom bh_plugin to suite your own purposes and just change all your shortcut commands to use your new plugin instead.

For more info on bh_plugins see: http://facelessuser.github.io/BracketHighlighter/customize/#bracket-plugin-api.  Also see http://facelessuser.github.io/BracketHighlighter/customize/#run-instance-plugins to see how to change your command to support your plugin.

When I get a little time, I will let you know whether there is already an existing way to achieve what you desire, if not, you will probably need to create a specialized bh_plugin.

**Comment by r-stein** [comment]
Thanks for the advice. I made a small specialized plugin:

``` py
class JumpOutRight(bh_plugin.BracketPluginCommand):
    def run(self, edit, name):
        self.refresh_match = True
        pos = self.right.end
        self.selection = [sublime.Region(pos, pos)]
```

However this could also easily added with an additional arg into the `selectbracket` plugin. I made this changes [here](https://github.com/r-stein/BracketHighlighter/commit/fe43491472cbcd1d8d22febaec481de1ba985298) and could create a PR.

**Comment by facelessuser** [comment]
Let me think about it.  I always knew it *could* be added, but that plugin is getting pretty complicated with all the different bracket jump options.  I think I almost prefer separate bh_plugins to handle different bracket jump styles.

Thanks for posting your work though to help others out.  Let me consider the direction I want to take and then I will get back to you.

**Comment by facelessuser** [comment]
Sorry it's taken me forever to get back to this.  I think I am going to leave things as is for now.  Since BH is flexible enough to support the current implementation and allow you to easily override it with your own stuff, I think I will pass on this feature for now since even if I included it, I wouldn't have BH use it by default.

If I get more requests for this, I will gladly include `JumpOutRight` so it is an available option, but users would still need to configure their commands in there user files as I would not have the commands use it by default.

Thanks for posting the example for others.
