### ISSUE TITLE
Compatibility with GitGutter markings

### ISSUE THREAD

**Issue by pirate** [facelessuser/BracketHighlighter#317]
Sorry to open an issue and take up your time, I wasn't able to find your email though.

We're trying to compile a list of gutter region keys from several different Sublime packages, for the purpose of setting gutter marking precedence order.  E.g. some users (like me) may want Bracket Highlighter's gutter markings to take 1st priority, and display on top of any GitGutter or SublimeLinter markings.  Other users may want SublimeLinter to take precedence, then Bracket Highlighter, and lastly Gitgutter.

https://github.com/jisaacks/GitGutter/issues/113#issuecomment-189455426

To be able to do this we need the list of region keys used by BracketHighlighter, and unfortunately using the keys produced by `view.settings().get('bh_regions')` doesn't seem to do the trick.  Do you know where I can find the relevant region keys?

**Comment by facelessuser** [comment]
As I recall, each region name is different as the icons are different for not only different bracket types/name, but for opening, closing, and even lines where the opening and closing are on the same line.  So each bracket variant has its own region name so they can exist simultaneously (multi-cursor etc.).

In the future, I would probably like to namespace them `brackethighlighter.name.type` etc., but currently, they follow the pattern `bh_name_type` (just replace type with close or open or whatever other type I use).  The code is found here: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_regions.py#L487.  So theoretically more names could always be added. Now I would have to dig a little deeper to be able to tell you how I determine `name` in the above examples, but it is likely that it is derived from the bracket style settings (name of each defined style entry https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L465).

I don't know if any of that helps, but hopefully :).

**Comment by facelessuser** [comment]
Yep, I just checked, the names are derived from the bracket style rules.  It's an area of code I haven't bothered to look at in a while.  It's funny how quickly you can forget things that you create.

**Comment by pirate** [comment]
I looked in `bh_regions.py` before opening this ticket and tried these with no luck: 
```python
>>>view.settings().get('bh_regions')
['bh_c_define', 'bh_c_define_center', 'bh_c_define_open', 'bh_c_define_close', 'bh_c_define_content', 'bh_curly', 'bh_curly_center', 'bh_curly_open', 'bh_curly_close', 'bh_curly_content', 'bh_angle', 'bh_angle_center', 'bh_angle_open', 'bh_angle_close', 'bh_angle_content', 'bh_square', 'bh_square_center', 'bh_square_open', 'bh_square_close', 'bh_square_content', 'bh_double_quote', 'bh_double_quote_center', 'bh_double_quote_open', 'bh_double_quote_close', 'bh_double_quote_content', 'bh_regex', 'bh_regex_center', 'bh_regex_open', 'bh_regex_close', 'bh_regex_content', 'bh_unmatched', 'bh_unmatched_center', 'bh_unmatched_open', 'bh_unmatched_close', 'bh_unmatched_content', 'bh_tag', 'bh_tag_center', 'bh_tag_open', 'bh_tag_close', 'bh_tag_content', 'bh_round', 'bh_round_center', 'bh_round_open', 'bh_round_close', 'bh_round_content', 'bh_default', 'bh_default_center', 'bh_default_open', 'bh_default_close', 'bh_default_content', 'bh_single_quote', 'bh_single_quote_center', 'bh_single_quote_open', 'bh_single_quote_close', 'bh_single_quote_content']`
```
I was hoping there might be another source of key names... Oh well, I guess it could be a GitGutter bug that's not giving these regions precedence.

**Comment by facelessuser** [comment]
I guess I am not sure what you mean.  I'm not exactly sure how Sublime determines priority for gutter icons, but it was my understanding that this isn't really something that can be controlled.  What exactly did you do with those region names?

**Comment by pirate** [comment]
GitGutter has a `protected_regions` setting that makes it not draw icons if the gutter is already occupied by another icon. The setting takes a list of region keys to give precedence to, e.g. `sublimelinter-errors` or `bh_curly_open`. You can see the discussion in the issue I linked to.  I was trying to add BracketHighlighter region keys to that list to no avail.  It seems like either GitGutter is unable to tell that the gutter is occupied by BH keys, or this list of keys is wrong.  I'm betting it's probably the first one.

**Comment by facelessuser** [comment]
Well, this is of course assuming that BH has rendered it's icon before GitGutter checks.  It is possible that GitGutter is checking before BH renders.
