### ISSUE TITLE
Code highlighted on click when code folded

### ISSUE THREAD

**Issue by RyanMcEvoy** [facelessuser/BracketHighlighter#321]
I believe I have found an issue when you fold code at the bottom of a file and then click.

I can only replicate this issue by folding the last 2 functions in my PHP file then clicking random brackets and text. The result of this bug is as shown
![screen shot 2016-03-17 at 15 30 33](https://cloud.githubusercontent.com/assets/10846845/13851336/a96dd99a-ec55-11e5-9006-827e8798cbb2.png)

By clicking once it will highlight the text right down to the bottom of the file, if you click anywhere else it will repeat this process making it difficult to place the cursor. The only way to circumvent it is to click the exact same spot as before. (It also happens when you click and drag to highlight code - it continuously jumps the highlighted area to the bottom of the file)

I have also only been able to replicate this bug if the cursor is within the last 15 lines of the viewable code.

I've provided my settings - just in case it's something I've done
```
{
    "match_brackets": false,
    "match_only_adjacent": true,
    "bracket_outside_adjacent": true,
    "show_unmatched": false,
    "search_threshold": 60000,
    // Define region highlight styles
    "bracket_styles": {
        "default": {
            "icon": "dot",
            "color": "brackethighlighter.default",
            "style": "outline"
        }
    }
}
```

**Comment by facelessuser** [comment]
I can't tell what the problem is from your description, but BH doesn't auto select text if that is what you are implying.  BH highlights brackets (not select).

I don't think this is a BH bug.

Just an aside, screenshots are helpful, but if you want me to try and reproduce a bug, please post code I can copy and paste as well.

**Comment by RyanMcEvoy** [comment]
I can't really explain it but I know it's definitely this plugin because I've uninstalled it and it no longer happens.
I think it might relate to when it is attempting to find the nearest bracket, it hits the end of the file due to the length of my search threshold and the code being folded which ends up leaving me with highlighted text.

Unfortunately I can't really provide you with code due to the nature of the business I work for, the most I can suggest is to use any PHP file that is 500 lines long or more and ensure you are scrolled to the very bottom.

**Comment by facelessuser** [comment]
> Unfortunately I can't really provide you with code due to the nature of the business I work for, the most I can suggest is to use any PHP file that is 500 lines long or more and ensure you are scrolled to the very bottom.

Just provide me with an example that works.  I don't know, some `foobar` stuff or whatever.  Then just provide me with step by step instructions so I can replicate your issue.  If you can hunt me down some PHP example from the web works, do that.  I am just asking you to provide me the necessary examples and info so I can replicate it and debug if necessary.

> I can't really explain it but I know it's definitely this plugin because I've uninstalled it and it no longer happens.

I am very doubtful that this is BH related, but I am willing to look into it.  Highlighting is a completely different API call than selecting text.  Absolutely no selection commands are invoked during highlight or bracket detection.  A "window" of text within the view is copied to a separate buffer and cursor positions are noted (but not altered), and bracket detection is performed within that separate buffer.  Afterwards we just add the highlight regions.  In some cases we reference back to the view to get scopes, but again, this is read only stuff.  If you were using the bracket jump calls, then I would be more likely to believe there was something.

But with all that said, if you provide me with the examples, I will confirm.

**Comment by facelessuser** [comment]
I will leave this open for another week to await a working (or non-working as the case may be) example to reproduce the issue.  I use various languages in some very large files and have never experienced these kinds of issues.  This is why I want to get an **exact** example that fails for you.  If an example that exhibits the problem for you can be posted here, I will look into it.  But after a weeks time, if no example has been posted, I will consider this issue stale and close it.

Being that you are the only one I have ever heard this from, I suspect there is something unique to your system.  It is possible another plugin you are using is interacting badly with BH, but as stated earlier, I am very doubtful that BH is directly to blame.

**Comment by facelessuser** [comment]
As I haven't received the info I requested, I am closing this issue.
