### ISSUE TITLE
Any way to configure the color of highlight brackets without pollute original theme.tmTheme

### ISSUE THREAD

**Issue by zheeeng** [facelessuser/BracketHighlighter#325]
Have read this part of BH doc:
<http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style>
The generated question is how I can add user-customized color scheme without original theme file modification.

**Comment by facelessuser** [comment]
Sure, instead of adding new scopes, use existing scopes already colorized in your tmTheme file.  You are limited to the scopes and colors already in your tmTheme file.  You can try things like `keyword`, `constant.numeric`, etc.

**Comment by zheeeng** [comment]
@facelessuser OK, I got your point, I thought of that and now with your reply, it seems that the colors I can use all are predefined in the theme file.

**Comment by facelessuser** [comment]
Yup.  It's just how Sublime works.  I wish there was a way to do it outside the color scheme file, but there isn't.
