### ISSUE TITLE
Turn off Bracket Highlighter on start

### ISSUE THREAD

**Issue by excetara2** [facelessuser/BracketHighlighter#326]
I have tried to create a syntax setting to turn off bracket highlighter when I load latex documents and turn on `match_bracket`. I have no problem turning on `match_bracket` but I have no idea how to turn off bracket highlighter besides using the toggle in the command palette.

**Comment by facelessuser** [comment]
You will have to write a simple plugin that detects when a file is latex on file activation and then call the BH toggle command when appropriate.

Or you can modify your personal BH bracket rules to ignore latex.

**Comment by excetara2** [comment]
Okay so the toggle is the only way to turn it off then?

I didn't know if it set a value so I could just set that to false on start. Thanks for the tips.

**Comment by facelessuser** [comment]
No, I mentioned you can alter the default rules to ignore latex.

**Comment by facelessuser** [comment]
I won't alter latex by default though, so you would have to do it for your setup.

**Comment by excetara2** [comment]
Okay no worries. I got it.

**Comment by r-stein** [comment]
This might not be the best way to to it, but you can easily write a listener to toggle the enabled value:

Just press `Tools >>> New Plugin...` and paste the following:

``` py 
import sublime_plugin
import BracketHighlighter


class DisableBhOnLatexListener(sublime_plugin.EventListener):
    def _set_bh_enabled(self, view):
        if view.score_selector(0, "text.tex"):
            # disable BH
            BracketHighlighter.bh_core.GLOBAL_ENABLE = False
        else:
            # enable BH
            BracketHighlighter.bh_core.GLOBAL_ENABLE = True

    on_load = _set_bh_enabled
    on_activated = _set_bh_enabled
```

This keeps the bracket highlighting in non-LaTeX files and has a very small overhead. it

**Comment by facelessuser** [comment]
That is one way.  The other is to simply use the rules to do the same like we blacklist Plain Text here: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L133.

There are rules that whitelist certain syntaxes and ignore all else, and rules that blacklist certain syntaxes and enable for all else.

Since you can just override the default settings already, this makes the most sense, but a plugin can laos do the same.

**Comment by r-stein** [comment]
@facelessuser one would have to change all rules, which are enable in LaTeX?

**Comment by facelessuser** [comment]
Yup.  For instance, LaTeX specific rules could just be disabled, and blacklist rules that aren't already blacklisting LaTeX would just need to have `LaTeX` (or whatever the name of the LaTeX syntax highlighter you are using) to the `language_list`.  So taking a quick look, this might be sufficient:

Notice, that I use the settings `user_brackets` and `user_scope_brackets`, and that I only override the option I want to change:

```js
    "user_scope_brackets": [
        // Quotes
        {
            "name": "single_quote",
            "language_list": ["LaTeX", "Plain text", "Hex"],
        },
        {
            "name": "double_quote",
            "language_list": ["LaTeX", "Plain text", "Hex"],
        },
        // LaTeX
        {
            "name": "latexmath_inline",
            "enabled": false
        }
    ],
    "user_brackets": [
        // Basic brackets
        {
            "name": "curly",
            "language_list": ["LaTeX", "Plain text", "Hex"],
        },
        {
            "name": "round",
            "language_list": ["LaTeX", "Plain text", "Hex"],
        },
        {
            "name": "square",
            "language_list": ["LaTeX", "Plain text", "Hex"],
        },
        // LaTeX
        {
            "name": "latexenv",
            "enabled": false
        }
    ],
```

**Comment by r-stein** [comment]
Thanks that looks nice =)

**Comment by facelessuser** [comment]
Originally you had to modify the default rule, but that meant you would miss out on bracket regex fixes or new rules as your user default rules would be used instead of the default.  By splitting user overrides to a separate settings, I could overlay user settings on top of default settings. This allows you to override parts of a rule, but still get all the other updates.  Just seemed cleaner from a user's perspective.

**Comment by r-stein** [comment]
Yes thats better

**Comment by facelessuser** [comment]
I feel this question has been answered.
