### ISSUE TITLE
Change in latest Blade highlighter plugin

### ISSUE THREAD

**Issue by Noldaru** [facelessuser/BracketHighlighter#337]
Hey,

This is more of a heads-up for the latest version of the Blade highlighter. It seems like they've done away with the 'laravel-blade.tmLanguage' file and are instead using a 'blade.sublime-syntax' file.

May want to update the configuration to include just 'blade' for angle syntax as well.

For those who want to fix it manually, it's fairly simple
:
in 'bh_core.sublime-settings', alter the following block:

        // Angle
        {
            "name": "angle",
            "open": "(<)(?=[^?%]|$)",
            "close": "(?:(?<=[^?%])|(?<=^))(>)",
            "style": "angle",
            "scope_exclude": [
                "string",
                "comment",
                "keyword.operator",
                "source.ruby.rails.embedded.html",
                "source.ruby.embedded.html"
            ],
            "language_filter": "whitelist",
            "language_list": [
                "HTML",
                "HTML 5",
                "XML",
                "PHP",
                "HTML (Rails)",
                "HTML (Jinja Templates)",
                "HTML (Twig)",
                "HTML (Django)",
                "HTML+CFML",
                "ColdFusion",
                "ColdFusionCFC",
                "laravel-blade",
                "blade", // ADD THIS LINE
                "Handlebars",
                "AngularJS",
                "Java Server Pages (JSP)"
            ],
            "plugin_library": "bh_modules.tags",
            "enabled": true
        },

Next, in 'bh_tag.sublime-settings', edit:

        "tag_mode": {
            "xhtml": ["XML"],
            "html": [
                "HTML",
                "HTML 5",
                "PHP",
                "HTML (Jinja Templates)",
                "HTML (Rails)",
                "HTML (Twig)",
                "HTML (Django)",
                "laravel-blade",
                "blade", // ADD THIS LINE
                "Handlebars",
                "AngularJS",
                "Java Server Pages (JSP)"
            ],
            "cfml": ["HTML+CFML", "ColdFusion", "ColdFusionCFC"]
        },

**Comment by facelessuser** [comment]
If you can issue a pull request, we can ensure it gets in.  The community supports the language rules as I don't use all languages.  It allows me to focus on the core code.
