### ISSUE TITLE
Have select brackets respect soft undo.

### ISSUE THREAD

**Issue by excetara2** [facelessuser/BracketHighlighter#340]
I switched from the normal bracket selection to the brackethighlighter one and I've noticed it doesn't respect soft undo. Is this possible to include like `sublime-expand-region`.

**Comment by facelessuser** [comment]
This may or may not be related to BH commands being window commands opposed to text commands (per window opposed to per view/file).  Text commands I think are actually tracked for things like this.  This would be related to #320 which would make this a duplicate issue.  I cannot promise that if/when I change BH commands to Text Commands that it will solve the issue, but if I do, and it doesn't work, then there is nothing else I can do.

I would follow #320 to monitor progress on a potential resolution.

**Comment by excetara2** [comment]
Yes maybe that will do but I just realized from looking at other plug-ins like `expand-region` is they forced an edit to begin with a different token id to enable soft undo to be triggered so maybe just changing to Text Commands won't fix the issue but I am not entirely sure. If you do change them over and it doesn't work I will have a look at getting it working.

**Comment by timfjord** [comment]
It would be really cool to have soft undo working with the plugin, as currently it simply nukes the selection altogether.
It looks like it can be achieved by wrapping the command in `sublime.set_timeout` with a 0 timeout, like here https://github.com/aafulei/sublime-expand-selection-to-line-upwards/blob/master/expand_selection_to_line_upwards.py#L5-L9

@facelessuser Do you think this `sublime.set_timeout` is compatible with BracketHighlighter?
I have little experience with the Sublime Text API but I am happy to try to implement this but it would be good to know if this is something you might be interested in?

**Comment by facelessuser** [comment]
Soft undo does actually work. The confusing part is that if you select really fast, you won't get much resolution and will soft undo all of them, but if you slow, soft undo will undo through all of them:

![soft_undo](https://user-images.githubusercontent.com/1055125/123471418-fff3e100-d5b2-11eb-8031-073c02fef08e.gif)

Here is when we select quickly:

![soft_undo_fast](https://user-images.githubusercontent.com/1055125/123471632-506b3e80-d5b3-11eb-9306-8964ebf656ed.gif)

Not sure why that is though 🤷🏻

**Comment by timfjord** [comment]
Hm, interesting. When you wait around 4-5 seconds then the command becomes reversible 😄 
Is there a way to add that `sublime.set_timeout` when invoking the command? (at least try)
I tried to find where it can be potentially added but my Python knowledge is limited 😞

**Comment by facelessuser** [comment]
So, here's the thing. I have the selection command bound to a keymap:

```js
    // Select text between brackets
    {
        "keys": ["ctrl+alt+super+s"],
        "command": "bh_key",
        "args":
        {
            "no_outside_adj": null,
            "lines" : true,
            "plugin":
            {
                "type": ["__all__"],
                "command": "bh_modules.bracketselect"
            }
        }
    },
```

You can force it to be called with `set_timeout` by using `bh_key_async` instead of `bh_key`. You can see the command below and that it does indeed call after a timeout.

```py
class BhAsyncKeyCommand(BhKeyCommand):
    """Call BH key command asynchronously."""

    def execute(self):
        """Call execute command asynchronously."""

        sublime.set_timeout(self.async_execute, 100)

    def async_execute(self):
        """Trigger actual BH command."""

        debug("Async Key Event")
        self.bh.match(self.view)
        bh_thread.ignore_all = False
        bh_thread.time = time()
```

But that actually prevents the soft undo from working at all.

I'm honestly not sure yet why the soft undo requires this wait to work with BH or why using the `set_timeout` causes it to not work. I know the `BhAsyncKey` was created to avoid issues when calling the command from the command palette (there was some issue which now I don't remember), but maybe that is no longer an issue when we migrated BH commands back to `TextCommands` from `WindowCommands` 🤷🏻 . It is probably something I'm doing, but I'd have to investigate much further to root cause this.

**Comment by timfjord** [comment]
Indeed, there is something mystic going on with the soft undo.
I came across this thread https://forum.sublimetext.com/t/plugin-soft-undo/40064/4
It looks like `sublime.set_timeout(lambda: ...., 0)` should work but I guess it should be called when the actual selection happens

**Comment by facelessuser** [comment]
That's interesting. I'm not sure how easily that would fit into what we are currently doing...at least that gives me something to look at. Assuming we could find a way to make it work, it probably won't make it into the next release as I plan on cutting a release this weekend to get some bug fixes out.

I'll at least explore if we could somehow how incorporate such a change somewhere to improve behavior, but it may not help with how we currently structure things, but I'll at least give it a try.

**Comment by timfjord** [comment]
I was able to make soft-undo working with the plugin with this simple plugin

```python
import sublime
import sublime_plugin


class BhKeyReversibleCommand(sublime_plugin.TextCommand):
  def run(self, edit, **kwargs):
    sublime.set_timeout(lambda:
      self.view.run_command('bh_key', args=kwargs),
      0
    )
```

So now I use `bh_key_reversible` instead of `bh_key` in key bindings and soft-undo works without the delay

**Comment by facelessuser** [comment]
Okay, I need to look into this some more. I would think the BH async command should work in this case then, but it doesn't, so maybe we can just adjust that. I'll try and play with this during the week.
