### ISSUE TITLE
Is there a way to disable BracketHighlighter for a particular filetype?

### ISSUE THREAD

**Issue by fgimian** [facelessuser/BracketHighlighter#343]
Hey there guys, thanks so much for the package, really love it!: 😄 

I would like to automatically disable the plugin for Markdown files to give a more minimal experience but can't seem to find a way to do this.  Any help would be greatly appreciated.

Thanks
Fotis

**Comment by facelessuser** [comment]
Yup, you can disable markdown specific rules, and you can disable general brackets by excluding markdown scopes.

**Comment by fgimian** [comment]
Thanks so much for the reply @facelessuser 😄 

That seems to have done trick.  I simply `scope_brackets` to my user settings for your plugin and removed all Markdown regex definitions.

Huge thanks for your help
Fotis

**Comment by facelessuser** [comment]
A better way is to just use `user_scope_brackets`.  You can do stuff like this: https://github.com/facelessuser/BracketHighlighter/issues/341#issuecomment-223422241.  It allows you to just override the fields of rules you want to modify.  That way when BH updates, you will get the latest rules **and** still be able to override what you want.

**Comment by fgimian** [comment]
Oh that's way better, thank you so much!!! 😄

**Comment by fgimian** [comment]
Hmm, perhaps I'm doing something wrong but I can't get that solution to work.  Here's what I'm trying:

```json
{
    // Override regexes used to apply bracket highlighting so we can exclude
    // Markdown for a cleaner Markdown editing experience
    "user_brackets": [
        // Markdown
        {
            "name": "mditalic",
            "scope_exclude": ["markup.italic"]
        },
        {
            "name": "mdbold",
            "scope_exclude": ["markup.bold"]
        },
        {
            "name": "mdcodeinline",
            "scope_exclude": ["markup.raw.inline.markdown"]
        },
        {
            "name": "mdcodeblock",
            "scope_exclude": ["markup.raw.block.fenced.markdown, markup.raw.block.markdown.fenced"]
        }
    ]
}
```

Cheers
Fotis

**Comment by fgimian** [comment]
Oh wait, I made a booboo, I should have used `user_scope_brackets', all working now :smile:

**Comment by facelessuser** [comment]
> Oh wait, I made a booboo, I should have used `user_scope_brackets', all working now 😄

Yup.  Scope rules go under the scope variant.  Glad you got it working.
