### ISSUE TITLE
IF without bracket

### ISSUE THREAD

**Issue by KaduAmaral** [facelessuser/BracketHighlighter#347]
The statements without brackets shows `?`.

![brackbug](https://cloud.githubusercontent.com/assets/4316607/16196943/63a19e08-36d6-11e6-9aba-7f71a918a106.png)

The language is PHP. To simulate this problem, have to use the `self::` on the statement, i.e.: 

```php
<?php

   if ( self::$routes )
      echo '...';

```

I'm using the Sublime build `3114`, on Windows 10;

**Comment by facelessuser** [comment]
Please read this to see what I am looking for in bug reports: http://facelessuser.github.io/BracketHighlighter/contributing/#bug-reports.

Also, mentioned in the above link is that specific language rules are supported by the community (though I do occasionally address issues in languages I actually use and or extremely problematic issues).

I am not entirely sure what language you are showing me above as you didn't mention what language I am looking at.

**Comment by KaduAmaral** [comment]
The language is PHP.

**Comment by facelessuser** [comment]
I'll explain why this is the case.  In a language like C you have if statements like this:

```c
if (condition) {
    i++;
}

if (condition)
    i++;
```

PHP is the same way, but they also have this other format:

```php
<?
if ($condition):
endif
>?

So two of those scenarios you don't want to highlight if, and only one you do.  BH has fairly simple rules to try and detect brackets.  The more exceptions you have for when it is okay to highlight something, the more difficult it is for BH to know when it needs to highlight.  Since the `if` is scoped no differently in these three cases, I can't use scope to get context.  I have to rely on regex, and Python's re doesn't handle recursive regex to help me be 100% sure that I can find `if ($condition):`, so instead we use a naive regex.

With that said, I did recently touch this keyword rule to try and simplify things a bit and reduce conflicts with other rules, but I did forget about such things as `self::` throwing things off (this is why the community supports the language rules, I don't use all programming languages). What I will do is adjust the rule to look for a line end after `:` or comments followed by a line end after `:`.  This is closer to how it used to be.  That will make it more reliable.

What really needs to probably happen is for the rule to look for all `if` and then use a bh_plugin to use procedural logic to scan ahead and make sure the conditional statement is a valid `if ($condition):` scenario as regex has a difficult time with this.  Though I don't use PHP enough to for me dig into that at this point.

**Comment by facelessuser** [comment]
I've released a bug fix release with this issue fixed.

**Comment by KaduAmaral** [comment]
Maybe some other statements can use `self::`, like `while(self::something())`, `for($i = self::count())` and etc... Thanks for your plugin and time..! :smile:

**Comment by facelessuser** [comment]
> Maybe some other statements can use `self::`, like `while(self::something())`, `for($i = self::count())` and etc... 

The fix above address all those.

> Thanks for your plugin and time..!

No problem
