### ISSUE TITLE
show_offscreen_bracket_popup does nothing

### ISSUE THREAD

**Issue by LeonardoGentile** [facelessuser/BracketHighlighter#354]
Hello,
I've tried your experimental settings `"show_offscreen_bracket_popup": true` but it seems nothing happens.
My bracket opens at one point and the closing bracket is not visible because offscreen. 
When I hover the gutter on the opening bracket nothing shows up and I have no error or any log in the console.

ST3 Build 3114 on Mac 10.9.5

**Comment by keith-hall** [comment]
I've found that I need to have the selection caret next to the bracket (either the opening or closing bracket, and making sure one is out of view) for the popup to work.

**Comment by LeonardoGentile** [comment]
Thanks @keith-hall, I've tried your suggestion but still no luck, nothing happens for me

**Comment by keith-hall** [comment]
@LeonardoGentile [the release notes](https://github.com/facelessuser/BracketHighlighter/blob/master/messages/2.18.0.md) state that you must be using ST3 build 3116 or newer - it won't work in 3114.

**Comment by LeonardoGentile** [comment]
Ops, sorry for that. "Check for new updates" tells me "No available Updates" so I've assumed I was running on the latest one. I will wait for the updates then 👍

**Comment by facelessuser** [comment]
> I've found that I need to have the selection caret next to the bracket

I don't think that is a requirement.  There are no checks on where the caret is,  only where the hover occurs and its relation to highlighted brackets in the view.

> Ops, sorry for that. "Check for new updates" tells me "No available Updates"

You have to be on the dev channel.  If you are a registered Sublime user, you can download dev releases:

https://www.sublimetext.com/3dev

**Comment by keith-hall** [comment]
>> I've found that I need to have the selection caret next to the bracket

> I don't think that is a requirement. There are no checks on where the caret is, only where the hover occurs and its relation to highlighted brackets in the view.

I've done some more testing, and it seems that the bracket you want to hover over must be highlighted/underlined and shown in the gutter by BH. So it only works for the outermost bracket where the selection is.

i.e. having the cursor inside a string in a JSON file, the gutter shows the quotation marks, and thus the outermost actual brackets that contain the string have the popup functionality disabled.

**Comment by facelessuser** [comment]
I'll clarify, it will work on strong word as well, but only if they are not visible, but Sublime won't tell you if briskets aren't visible in the horizontal, only in the vertical.  I will have to experiment if there are ways to predict the horizontal, but maybe I'm out of luck with that.

**Comment by facelessuser** [comment]
String word not strong... Stupid phone autocorrect.

**Comment by keith-hall** [comment]
Horizontal non-visible brackets aren't as important IMO :)

Let's take the following JSON file (following the instructions inside):

    {
        "example_json": true,
        "array": [1, 2, 3, 4]
        "now": "insert enough new lines below to ensure the } is not visible without scrolling"
    
    
    }

when the selection is inside one of the strings, or between the `[` and `]`, hovering over the `{` or `}` (depending which is on screen) does nothing.

**Comment by facelessuser** [comment]
> Horizontal non-visible brackets aren't as important IMO :)

I feel the same, but if there is way, I don't mind trying :).

> when the selection is inside one of the strings, or between the [ and ], hovering over the { or } (depending which is on screen) does nothing.

Yeah, it will only work on highlighted brackets, so yes, only the brackets surrounding a caret.  It will work with multi-select.  On-hover works by looking at the view settings to see where current highlighted brackets exist.  It doesn't perform an on demand match.  I was trying to make it quick and avoid any labor intensive calculations.  I must have misunderstood what you were saying.

**Comment by keith-hall** [comment]
@facelessuser understood, thanks for the clarification. Maybe this could be added to the documentation so that people know what to expect? :)

**Comment by facelessuser** [comment]
> @facelessuser understood, thanks for the clarification. Maybe this could be added to the documentation so that people know what to expect? :)

Yeah, I will update the doc once I understand all the diverse ways people are confused :).

**Comment by facelessuser** [comment]
I'm going to close this issue and open a new one dedicated to discussing this new feature.

**Comment by facelessuser** [comment]
Issue #355 is available for discussing the new feature.  Hopefully the new title will draw people to it so we don't get multiple threads.
