### ISSUE TITLE
Discuss new experimental pop-ups for ST3 3116+

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/BracketHighlighter#355]
Discuss the new experimental pop-up feature.  Make suggestions and ask questions etc.

**Comment by keith-hall** [comment]
I figured I'd add a link to the forum post where a few things were already discussed, so people won't ask about it twice :) https://forum.sublimetext.com/t/st3-brackethighlighter-2/8725/55

**Comment by facelessuser** [comment]
Thanks!  Good idea.

**Comment by princemaple** [comment]
Love this new feature. Thanks!

**Comment by facelessuser** [comment]
Thanks! Glad you like it.

**Comment by facelessuser** [comment]
I think in general people like it and there is nothing more to discuss.  Closing issue.
