### ISSUE TITLE
BH not matching brackets in regexes while Sublime does?

### ISSUE THREAD

**Issue by MattDMo** [facelessuser/BracketHighlighter#357]
As you may know, I have my Neon theme all tricked out for supporting various regex languages, including PackageDev's `YAML-tmLanguage` format for writing (old-style, now) syntax definitions. I was going through your docs today and customizing BH more, and came across this (the real regex is longer, I just made an MCVE):
![bh1](https://cloud.githubusercontent.com/assets/1776358/16474072/6fc03c5e-3e41-11e6-8de3-391345ed0685.png)
The vertical bar just to the left of the first paren, and the red box indicates an unmatched bracket (all unescaped parens *are* matched in this example). I also have `"match_brackets": true` in my settings, and Sublime isn't matching that set either.

Next, I move the cursor next to open paren # 2. Everything works fine:
![bh2](https://cloud.githubusercontent.com/assets/1776358/16474212/b68927b2-3e42-11e6-948a-3545135fc96e.png)
The parens are matched both with a white underline (Sublime) and a blue box (BH). 

OK, on to the next open paren:
![bh3](https://cloud.githubusercontent.com/assets/1776358/16474255/3d1e2fd4-3e43-11e6-9f63-887431c07b93.png)
Again we have the red box of an unmatched bracket, but instead of highlighting the next close paren (which is syntax-colored correctly), Sublime matches the *last* paren with the white underline.

Moving on the the escaped paren, BH does nothing (good), but Sublime matches it:
![bh4](https://cloud.githubusercontent.com/assets/1776358/16474330/e6ac3870-3e43-11e6-85a0-50da39c3d3b1.png)
Weird.

Now we're before the escaped square bracket. For some reason, BH highlights it as unpaired, even though it's escaped:
![bh5](https://cloud.githubusercontent.com/assets/1776358/16474396/72eb0e88-3e44-11e6-87dc-e03b0f451bb7.png)
Is there a reason for this, or is it a bug? If so, is it fixable, or Sublime's fault?

This is strange, too. Moving the cursor over by 1 so it's to the left of the closing paren (or by 1 more so it's to the right), the escaped square bracket stays highlighted, and the closing paren, while being correctly syntax-highlighted, is not matched by BH *or* Sublime:
![bh6](https://cloud.githubusercontent.com/assets/1776358/16474468/1d9c533c-3e45-11e6-8c8c-2e4b29134d86.png)
How did *that* happen?

Finally, to the last closing paren. It is correctly syntax highlighted, but again unmatched by either BH or Sublime:
![bh7](https://cloud.githubusercontent.com/assets/1776358/16474511/82c1b6bc-3e45-11e6-8a18-4195ed734194.png)

---

So what's going on? Why are there so many discrepancies between BH, Sublime's bracket matching, and the syntax highlighting (which is being run on the old regex engine using a tmLanguage file, in case that's important)? If I removed the unmatched paren and square bracket from the regex, all the remaining parens match just fine. Interestingly, if I add in matching escaped square bracket and paren, this happens:
To left of open paren: 
![bh8](https://cloud.githubusercontent.com/assets/1776358/16474885/63c332c4-3e48-11e6-9807-b987ab6289e5.png)
To left of escaped open paren: 
![bh9](https://cloud.githubusercontent.com/assets/1776358/16474902/77e15a24-3e48-11e6-869c-6b6e2f1a8a49.png)
To left of escaped open square bracket: 
![bh10](https://cloud.githubusercontent.com/assets/1776358/16474919/8ea4681e-3e48-11e6-9281-ef015a42a6ec.png)
To left of escaped closing square bracket: 
![bh11](https://cloud.githubusercontent.com/assets/1776358/16474932/9f8dd106-3e48-11e6-95d6-8f4b58277d20.png)
To left of escaped closing paren: 
![bh12](https://cloud.githubusercontent.com/assets/1776358/16474959/b62f42a0-3e48-11e6-961d-96eb7d77201a.png)
To left of closing paren: 
![bh13](https://cloud.githubusercontent.com/assets/1776358/16474979/d2bdfbdc-3e48-11e6-81cd-715431d40043.png)
To right of closing paren: 
![bh14](https://cloud.githubusercontent.com/assets/1776358/16474996/e6da287a-3e48-11e6-9be7-c5e6ec393eeb.png)

It seems that BH properly matches the opening and closing paren, but improperly matches the opening and closing escaped square brackets (but *not* the opening and closing escaped parens). Sublime's matching is all over the place.

So, any thoughts? (Yes, I was bored tonight :grinning: )

**Comment by facelessuser** [comment]
Yeah its probably getting confused on the escaped brackets.  What's the scope of the escaped round brackets?

**Comment by facelessuser** [comment]
And scope of escaped square brackets?

**Comment by facelessuser** [comment]
This is probably what you need in your square bracket rule:

```diff
diff --git a/bh_core.sublime-settings b/bh_core.sublime-settings
index 41a8aa9..adf517c 100755
--- a/bh_core.sublime-settings
+++ b/bh_core.sublime-settings
@@ -326,9 +326,13 @@
             "scope_exclude": [
                 "string",
                 "source.regexp constant.character.escape",
+                "source.yaml-tmlanguage constant.character.escape",
                 "comment"
             ],
-            "scope_exclude_exceptions": ["text.tex string.other.math", "source.yaml-tmlanguage meta.value -constant.character.escape"],
+            "scope_exclude_exceptions": [
+                "text.tex string.other.math",
+                "source.yaml-tmlanguage meta.value -constant.character.escape"
+            ],
             "language_filter": "blacklist",
             "language_list": ["Plain text", "Hex", "RTF"],
             "find_in_sub_search": "true",
```

**Comment by facelessuser** [comment]
Hmm.  Now I look more, I think we can ditch one of the `scope_exclude_exceptions` as well:

```diff
diff --git a/bh_core.sublime-settings b/bh_core.sublime-settings
index 41a8aa9..37fa89a 100755
--- a/bh_core.sublime-settings
+++ b/bh_core.sublime-settings
@@ -326,9 +326,12 @@
             "scope_exclude": [
                 "string",
                 "source.regexp constant.character.escape",
+                "source.yaml-tmlanguage constant.character.escape",
                 "comment"
             ],
-            "scope_exclude_exceptions": ["text.tex string.other.math", "source.yaml-tmlanguage meta.value -constant.character.escape"],
+            "scope_exclude_exceptions": [
+                "text.tex string.other.math"
+            ],
             "language_filter": "blacklist",
             "language_list": ["Plain text", "Hex", "RTF"],
             "find_in_sub_search": "true",
```

I think they have just been tweaking it since the last time they issued a pull request.

**Comment by MattDMo** [comment]
Escaped round:
```
source.yaml-tmlanguage 
meta.repository-block.yaml-tmlanguage 
meta.match.yaml-tmlanguage 
meta.value.yaml-tmlanguage 
meta.regexp.group 
meta.regexp.group 
constant.character.escape.general.regexp
```
Escaped square:
```
source.yaml-tmlanguage 
meta.repository-block.yaml-tmlanguage 
meta.match.yaml-tmlanguage 
meta.value.yaml-tmlanguage 
meta.regexp.group 
meta.regexp.group 
constant.character.escape.general.regexp
```
So they're exactly the same...

As far as the change in `"scope_exclude"`, do you think just having a plain `constant.character.escape` would be better? After all, we don't want to be matching *any* escaped characters, right?

**Comment by facelessuser** [comment]
We need to give them a more specific scope.  We are fixing the issue in this yaml file, so we don't want to cause more headaches by potentially introducing side effects in other languages. Constant.character.escape is too broad.  Some languages it might not work as expected.

**Comment by facelessuser** [comment]
So did my suggestion work for you?  What did you end up settling on?

**Comment by facelessuser** [comment]
Not sure if this was resolved.  Marking stale and giving it another week.

**Comment by facelessuser** [comment]
@MattDMo I guess I am closing this as I've heard nothing else.  If per chance you were able to get things working satisfactorily, please issue a pull request.  I don't really use AAAPackageDev, so I need someone who does that is willing to test out changes before it gets committed (which is why I require a pull request).

**Comment by MattDMo** [comment]
Sorry for leaving you behind, I just started a new job two weeks ago, and haven't had as much time to fiddle around with stuff like this. I basically took your suggestion; the relevant part of my user settings is this:
```js
"brackets": [
    // Basic brackets
    {
        "name": "curly",
        "open": "(\\{)",
        "close": "(\\})",
        "style": "curly",
        "scope_exclude": [
            "string",
            "comment",
            "source.regexp constant.character.escape",
            "source.yaml-tmlanguage constant.character.escape"
        ],
        "scope_exclude_exceptions": ["text.tex string.other.math"],
        "language_filter": "blacklist",
        "language_list": ["Plain text", "Hex"],
        "find_in_sub_search": "true",
        "ignore_string_escape": true,
        "enabled": true
    },
    {
        "name": "round",
        "open": "(\\()",
        "close": "(\\))",
        "style": "round",
        "scope_exclude_exceptions": [
            "text.tex string.other.math",
            "punctuation.definition.string.begin.shell",
            "punctuation.definition.string.end.shell"
        ],
        "scope_exclude": [
            "string",
            "comment",
            "source.regexp constant.character.escape",
            "punctuation.definition.case-pattern.shell",
            "source.yaml-tmlanguage constant.character.escape"
        ],
        "language_filter": "blacklist",
        "language_list": ["Plain text", "Hex", "RTF"],
        "find_in_sub_search": "true",
        "ignore_string_escape": true,
        "enabled": true
    },
    {
        "name": "square",
        "open": "(\\[)",
        "close": "(\\])",
        "style": "square",
        "scope_exclude": [
            "string",
            "source.regexp constant.character.escape",
            "comment"
        ],
        "scope_exclude_exceptions": ["text.tex string.other.math", "source.yaml-tmlanguage meta.value -constant.character.escape"],
        "language_filter": "blacklist",
        "language_list": ["Plain text", "Hex", "RTF"],
        "find_in_sub_search": "true",
        "ignore_string_escape": true,
        "enabled": true
    },
```
and it's been working well so far. I may end up experimenting with just setting `constant.character.escape` in `"scope_exclude"`, but I haven't had any issues in other languages yet, so I'll just let it be for now. Thanks for your help!

**Comment by facelessuser** [comment]
> Sorry for leaving you behind, I just started a new job two weeks ago, and haven't had as much time to fiddle around with stuff like this.

No worries.  I just try and address this stuff within a time frame because if I don't, I will forget about it as support a bunch of repos.

Sounds good.  I probably wouldn't accept just `constant.character.escape` on the main branch as though it may work for you in all the languages you try, it is the other languages you don't try that I am more concerned about.  Better to start narrow and broaden as needed.  If it is working well for you, I'd be happy to accept a pull for others.

Anyways, good luck with your new job!  And thanks for for updating me on this.
