### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by badraufran** [facelessuser/BracketHighlighter#358]
Sorry for an off-topic question, wasn't sure how else to ask. I couldn't find anything in closed issues either.

What is the Sublime Text color scheme/theme you have in the preview image? I can't find it anywhere.

Thanks

**Comment by facelessuser** [comment]
No worries.  It's from the Aprosopo theme: https://github.com/facelessuser/Aprosopo.

**Comment by badraufran** [comment]
Oh awesome, thanks.
