### ISSUE TITLE
Can’t install mdpopups dependency library “Version could not be acquired!”

### ISSUE THREAD

**Issue by onirix** [facelessuser/BracketHighlighter#360]
I follow the instructions for the last update of BracketHighlighter and it seems not be able to install the library mdpopups.
Here is the content of “Support Info” :
```
- ST ver.:        3103
- Platform:       windows
- Arch:           x64
- Plugin ver.:    2.20.0
- Install via PC: True
- mdpopups ver.:  Version could not be acquired!
- backrefs ver.:  1.0.post1
- markdown ver.:  Version could not be acquired!
- pygments ver.:  Version could not be acquired!
- jinja2 ver.:    Version could not be acquired!
```
Here the log after running the command “Satisfy Dependency” :
`Package Control: All dependencies have been satisfied`

Also I can’t open this `Preferences->Package Settings->BracketHighlighter->Changelog`, the menu is gray out.

I’ll have this config in Bracket Settings - User :
`{
	// Character threshold to search
	"search_threshold": 22500,
	// "search_threshold": 20000,
	"show_offscreen_bracket_popup": true
}`
but I try to comment it and above all to remove BracketHighlighter package and reinstall it.

### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

For bugs, provide errors from console, examples etc.  For feature requests, describe the desired feature.  Be as detailed as possible. Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

---

### Issue Support Info

For bugs, run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.  Omit for feature requests.

### Steps to Reproduce Issue

Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests.

**Comment by facelessuser** [comment]
Your on too old a version.  You should be fine without it.  Mdpopups won't install unless you are on ST 3116+.
