### ISSUE TITLE
BracketHighlighter 2.21.0 dependencies problem

### ISSUE THREAD

**Issue by felixlu** [facelessuser/BracketHighlighter#361]
After upgrading, console outputs:

    ImportError: No module named 'mdpopups'
    reloading settings Packages/User/Package Control.sublime-settings
    reloading settings Packages/User/Preferences.sublime-settings
    reloading settings Packages/User/Preferences.sublime-settings

After running `Satisfy Dependency` command:

    Package Control: All dependencies have been satisfied

and the module 'mdpopups' still not installed.

PS: I'm using ST3 3114, thx

**Comment by facelessuser** [comment]
Sorry, it requires it if you are on 3116+.  I really should have made a more specific message.

**Comment by facelessuser** [comment]
I now see I closed this when I shouldn't have.  Ref #362.  This will be fixed in the next version.
