### ISSUE TITLE
"search_threshold" don't work for me

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/BracketHighlighter#365]
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

I want that in my big html-files instead of a question mark there were angular brackets, if the distance between the opening and closing tags is large. But at me it is impossible to make it.

![Question mark](http://i.imgur.com/3HslSM4.png)

---

### Issue Support Info

- ST ver.: 3114
- Platform: windows
- Arch: x32
- Plugin ver.: 2.21.5
- Install via PC: True
- mdpopups ver.: Version could not be acquired!
- backrefs ver.: 1.0.post1
- markdown ver.: Version could not be acquired!
- pygments ver.: Version could not be acquired!
- jinja2 ver.: Version could not be acquired!

### Steps to Reproduce Issue

I reproduce my steps to the clean portable version of Sublime Text 3 without plugins.

`Preferences` →` Package Settings` → `BracketHighlighter `→ `Bracket Settings - User` → the contents of the opened file I replaced with the following code:

```
{
    "search_threshold": 1005000
}
```

I restart Sublime Text 3, close and open newly my HTML file, but still in the gutter question mark.

Thanks.

**Comment by facelessuser** [comment]
Without the example source you are trying this in, it is tough to tell if `1005000` is enough or if there is something odd in your source that is interfering with BH's ability to resolve all brackets.

I would try a pair of working brackets and reduce the threshold to a number of chars less than the working distance.  You will see that the threshold does in fact work, and you will no longer be able to find the bracket pair that previously worked.

So if `1005000` is a more than sufficient threshold, then I would say there is some syntax in your file getting in BH's way.  Maybe it is some template language syntax, or maybe it is PHP syntax getting in the way.  If you can point me at a non-working example, I can maybe tell you why it isn't working, but without an example, I am afraid I am not able to help.

**Comment by Kristinita** [comment]
@facelessuser , I'm sorry, the mistake was mine. I checked my code HTML-pages via SublimeLinter, it was discovered that I had an extra slash in the tag `<a>` — `/`.

Correct:
` <a href="http://example.com">Sasha Zeitgeist</a>`

I have:
`<a href="http://example.com"/>Sasha Zeitgeist</a>`

Now all works. Thanks.

**Comment by facelessuser** [comment]
Yup, that will cause an issue :smile:.  Glad you figured it out.
