### ISSUE TITLE
BH is not able to identify closing bracket for alternative syntax in PHP.

### ISSUE THREAD

**Issue by paKanhu** [facelessuser/BracketHighlighter#366]
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x ] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

BH is not able to identify closing bracket for alternative syntax in PHP.

![st-brackethighlighter](https://cloud.githubusercontent.com/assets/3684243/18223599/abc85d46-71d9-11e6-8b96-93a6c04c7fb5.png)

---

### Issue Support Info

- ST ver.: 3120
- Platform: windows
- Arch: x64
- Plugin ver.: 2.21.5
- Install via PC: True
- mdpopups ver.: 1.10.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

### Steps to Reproduce Issue

1. Set syntax to PHP.
2. Paste below code.
```php
<?php foreach ($variable as $key => $value): ?>
    
<?php endforeach ?>
```
3. Check BH error on ```foreach```.

**Comment by facelessuser** [comment]
I think this is because it expects a semi-colon at the end of `endforeach`.  You can issue a pull request that will accept `endforeach;` or `endforeach ?>` if you like.

**Comment by facelessuser** [comment]
Maybe test out something like this for a closing rule and see if it works for you.  If it does, you can issue a pull request.

```
(?:(?<=^)|(?<=<\\?php)|(?<=<\\?))\\s*(endif|endfor|endforeach|endwhile|endswitch)\\b(?=\\s*(?:;|;?\\?>))
```

**Comment by Kitanga** [comment]
This is also true for javascript. I have been trying to fix the issue, but still no success. Weirdest part is that when I took my code and pasted it function by function into another file (I was looking for where the issue might be), I noticed that if I removed comments with '//' and used '/**/' then the bracket matching would work. Now it's still stuck on '?'. You can seethe code here:
```
var test = (function() {
    /* Removing */
    /* Public Variables */
    var t = this;
    this.images = {}; /* This is where all the loaded images are saved */
    this.sprites = []; /* This is where are sprites are saved */
    this.anim = ''; /* This is the main animation loop. Uses requestanimationframe to animate rooms */
    this.canStart = false; /* Can the game start? Should be set to true when loading finishes */
    this.rooms = {}; /* This is where all the rooms are saved. */
    this.display = ''; /* Display canvas */
    this.world = ''; /* This is the reference to the world canvas on which all the currrent running room's objects will live. */

    /* ./Public Variables */

    /* Private Variables */
    var toBeLoaded = 0,
        /* Total number of images that need loading */
        isLoaded = 0,
        /* Images that have loaded */
        perLoadedDec = 0,
        /* Percentageloaded in decimal form */
        iDontDoAnything; /* Self explanatory, doesn't do anything */
    /* ./Private Variables */

    /* Private Functions */
    function getSqr(num) {
        /* This function will return the square (or to the power of two) of num */
        return num * num;
    }
    function Vector(x, y) {
        this.x = x;
        this.y = y;
        this.normalize = function() {
            var length = this.length();
            if (length > 0) {
                return vector(this.x/length, this.y/length);
            } else {
                // zero-length vectors cannot be normalized, as they do not have direction.
                return vector();
            }
        };
        this.length = function() {
            return Math.sqrt(getSqr(this.x) + getSqr(this.y));
        };
        console.log(this.force)
        return this; /*{
            x: x || 0,
            y: y || 0
        };*/
    }
    function point(x, y) {
        /* Returns x and y */
        this.distance = function(a, b) {
            var x = b.x - a.x;
            var y = b.y - a.y;
            return Math.sqrt(getSqr(x) + getSqr(y));
        };
        return {
            x: x || 0,
            y: y || 0
        };
    }
    function Sprite(layer, key, x, y, isAlive) {
        /* Sprite Class */
        var spr = this;
        this.pos = point(x, y);
        this.mass = 1;
        this.force = Vector(0, 0);
        this.velocity = Vector();
        this.acceleration = Vector(this.force.x/this.mass, this.force.y/this.mass);
        this.layer = layer; /* The layer onto which to draw this sprite */
        this.canvas = this.layer.canvas; /* The layer's canvas */
        this.ctx = this.layer.ctx; /* The layer canvas' drawing context */
        this.img = new Image(); /* The sprite's main image */
        this.img.src = t.images[key].src;
        this.rotImg = undefined; /* The rotated version of the main image. To be used when rotating towards mouse/Vector */
        this.doIRotate = undefined;
        this.rotAngleRad = undefined; /* This is the angle between mouse and sprite */
        this.mouse = Vector();
        this.alive = isAlive; /* Whether the sprite should be drawn onto the world */
        this.init = function() {
            /* Create the drawer canvas */
            /*debugger*/
            this.drawer = undefined;
            this.cW = 0;
            this.cH = 0;
            this.imgW = this.img.width;
            this.imgH = this.img.height;
            
            /* Find dimensions for canvas */
            this.cW = (Math.sqrt(getSqr(this.imgW/2) + getSqr(this.imgH/2))) * 2;
            this.cH = this.cW;
            this.imgOnDrawerX = 0 - (this.imgW/2);
            this.imgOnDrawerY = 0 - (this.imgH/2);
            this.drawer = t.createCanvas(this.cW, this.cH, '0');
            this.drawer.ctx.translate(this.cW/2, this.cH/2);
            t.drawOnCanvas(this.drawer, this.img, this.imgOnDrawerX, this.imgOnDrawerY);
            t.drawOnWorld(this.drawer.canvas, this.pos.x, this.pos.y);
            /* END Create the drawer canvas */

            /* Event Listeners */
            this.canvas.onclick = function(ev) {
                ev.preventDefault();
                if (spr.doIRotate) {
                    spr.mouse = Vector(ev.pageX - spr.canvas.offsetLeft, ev.pageY - spr.canvas.offsetTop);
                    console.log(spr.mouse);
                    spr.setMouseToPointAngle(spr.mouse);
                    spr.rotationInit(spr.drawer);
                }
                spr.applyImpulse(spr.xy(10, 10),spr.mouse.normalize());
            };
        };
        this.kill = function() {
            /* This will remove sprite from world canvas */
            if (this.alive) {
                this.alive = false;
            }

        };
        this.rotationInit = function(drawer) {
            this.drawer.ctx.clearRect(0 - (this.drawer.canvas.width/2), 0 - (this.drawer.canvas.height/2), this.drawer.canvas.width, this.drawer.canvas.height);
            this.drawer.ctx.save();
            this.drawer.ctx.rotate(this.rotAngleRad);
            t.drawOnCanvas(this.drawer, this.img, 0 - (this.img.width/2), 0 - (this.img.height/2));
            t.drawOnWorld(this.drawer.canvas, this.pos.x, this.pos.y);
            this.drawer.ctx.restore();
        };
    }
})();
```

**Comment by facelessuser** [comment]
@kitanga, I am fairly certain you are not experiencing the same thing.  What you are most likely experiencing is BH halting search because it reached its distance threshold.  This is covered in the documentation.  You can increase the threshold, but as you increase the threshold you will impact performance; when that impact becomes noticeable and negative will depend on your system.  If you have a particular bracket you want to search that is outside the threshold, you can run a command that will match without the threshold which should find the other bracket assuming you don't have an error in your code.  But we always use a threshold for instant searching for performance sake.

**Comment by Kitanga** [comment]
Thank you for your reply. Btw, my laptop only has 2GB of RAM :sob:  
Even opening this tab took time :laughing:  So yea, this will be fun. Thanks though

**Comment by facelessuser** [comment]
FYI, I tried out your code and I had no problems.  My threshold is set to this:

```js
    // Character threshold to search
    "search_threshold": 10000,
```

Smaller thresholds (like the default value) may not be able to search the full content in your example.

**Comment by Kitanga** [comment]
Thank you😆

**Comment by facelessuser** [comment]
@paKanhu I am assuming you did not try my suggestion or it did not work for you, but since there has been no response from you, I am closing this issue.  Requesters should be willing to participate in discussion in order to get support, but since discussion has ceased, I will close the issue.

**Comment by paKanhu** [comment]
Sorry for delay in reply. I was ill for last 15 days. I have tested the suggested closing rule and it's working.

`(?:(?<=^)|(?<=<\\?php)|(?<=<\\?))\\s*(endif|endfor|endforeach|endwhile|endswitch)\\b(?=\\s*(?:;|;?\\?>))`
