### ISSUE TITLE
unmatched bug

### ISSUE THREAD

**Issue by ctf0** [facelessuser/BracketHighlighter#368]
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

For bugs, provide errors from console, examples etc.  For feature requests, describe the desired feature.  Be as detailed as possible. Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

---

### Issue Support Info

For bugs, run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.  Omit for feature requests.

>
- ST ver.: 3120
- Platform: osx
- Arch: x64
- Plugin ver.: 2.21.5
- Install via PC: True
- mdpopups ver.: 1.10.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

### Steps to Reproduce Issue

Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests.

![bug](https://cloud.githubusercontent.com/assets/7388088/18439379/5b750a8c-7905-11e6-9282-03fd78aeae8e.jpg)

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
    <div class="container">
        <my-tasks></my-tasks>
    </div>
    
    <template id="my-tasks">
        <h1>My Tasks</h1>
        
        <ul class="list-group">
            <li v-for="task in list" class="list-group-item">
                @{{ task.body }}
                <button @click="deleteTask(task)" class="btn btn-danger">remove</button>
            </li>
        </ul>
    </template>
</body>
</html>
```

**Comment by facelessuser** [comment]
This is not pure HTML.  Please describe what you are actually using and go into details.  I see `@click` which I am unfamiliar with.  If this is not pure HTML, I see no bug and would recommend you issue a pull request to add your desired functionality for the template language you are using.  If `@click` is some HTML standard that I am not familiar with (I am not a web developer), then please explain and point at the appropriate documentation.

**Comment by ctf0** [comment]
u r correct, the `@click` is the one that was causing the issue, its a vue syntax , can u plz point me to how i can add this function ?

**Comment by facelessuser** [comment]
You will probably need to take a look at the the [`bh_tag.sublime-settings`](https://github.com/facelessuser/BracketHighlighter/blob/master/bh_tag.sublime-settings).  I've pushed most of the logic into the settings file to allow for pull requests without me having to modify the main bh_plugin.

**Comment by ctf0** [comment]
okay , i will try to play with it and see what will comeout,
one last question,
is there away to give foreground & background to the unmatch ? so whatever the unmatched tag fg & bg is currently set ,it gets changed to the unmatched ?

**Comment by facelessuser** [comment]
> is there away to give foreground & background to the unmatch ? 
so whatever the unmatched tag fg & bg is currently set ,it gets changed to the unmatched style.

I don't think I understand the question.  Can you elaborate?

**Comment by ctf0** [comment]
i got it, i just needed to change the setting for unmatched to "solid" , thanx again
