### ISSUE TITLE
Make it work with Crystal Files.

### ISSUE THREAD

**Issue by taggedboy** [facelessuser/BracketHighlighter#371]
Is it possible to make BracketHighlighter workd with Crystal files?
The syntax is that of ruby, with the only difference that Crystal files end with .cr

**Comment by facelessuser** [comment]
The template for issues was not followed.  If you read the template, it explains that these things are covered in the documentation.  If after reading the documentation on this matter you still have questions, I'd be happy to answer your questions.

**Comment by taggedboy** [comment]
If you read the comment, you'll come to know that it will take 1/10th time to read the above comment than readting the comment created following that template, and the meaning of the comment is also clear.

**Comment by facelessuser** [comment]
Do you know why I have a template?  To save **me** time.  Your question is covered in the documentation.  It is also covered in numerous, previous issues (which you can also search).  I have a template to remind people to **first**, before contacting me, **read** the documentation **and** search issues.

In the documentation I cover customizing brackets etc.  In the issues I have guided many people through the process.  Based on your comment, which I did read (and it has yet saved me any time reading it), it would appear you did **not** read the template which requires all who wish to solicit support from me to first **search** and **read** the documentation.

In the template I am clear that I want people to do their part before I spend any of my free time on their issues.  I require people to follow the template, not improve or argue with me about the template.  If you would like to open a separate, specific issue to offer constructive improvements to the template or the issue process, feel free.

Please read the documentation and then respond with questions accordingly.  If this is going to become a discussion of how you think I should offer up my free time to help people, then I will close the issue now and we can both move on.  I am increasingly become more firm about this as these questions have been answered more times than I can count.

**Comment by facelessuser** [comment]
I've heard no response, so I am marking this stale.  I will close it in a weak if I hear no answer.

**Comment by facelessuser** [comment]
No response.  Closing issue.
