### ISSUE TITLE
stop working in sublime 3 Build 3124

### ISSUE THREAD

**Issue by josem32** [facelessuser/BracketHighlighter#372]
I updated to the newest version of sublime 3, build 3124 and i cant make the plugin work, it simple doesn't work.

**Comment by facelessuser** [comment]
Please follow the template: https://raw.githubusercontent.com/facelessuser/BracketHighlighter/master/.github/ISSUE_TEMPLATE.md.

And it is working fine for me in 3124 (I use 3123 -- 3124 is the public beta release of the dev release of 3124, so they are the same).

**Comment by orcinus** [comment]
Doesn't work for me in 3124 either.

**Comment by facelessuser** [comment]
@orcinus, if you create an issue following the template I can look into the issue.

**Comment by orcinus** [comment]
Done.
