### ISSUE TITLE
Doesn't seem to work since update to build 3124

### ISSUE THREAD

**Issue by orcinus** [facelessuser/BracketHighlighter#374]
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

After upgrading to build 3124 recently, BracketHighlighter stopped working. I'm getting regular (built-in) Sublime highlighting, i.e. underscore under the brackets, but no BracketHighlighter highlighting. I've got no user configuration for BracketHighlighter and am currently on the defaults only.

---

### Issue Support Info

- ST ver.: 3124
- Platform: osx
- Arch: x64
- Plugin ver.: 2.21.5
- Install via PC: True
- mdpopups ver.: 1.10.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

### Steps to Reproduce Issue

- Install Sublime 3 build 3124
- Install BracketHighlighter
- Enter a bracketed block
- Observe BracketHighlighter not working

**Comment by orcinus** [comment]
Just updated to 3126.
Working again.

**Comment by facelessuser** [comment]
> Just updated to 3126.
Working again.

Nice, I was going to suggest an upgrade.
