### ISSUE TITLE
Sometimes starting bracket doesnt match ending bracket but it works the other way

### ISSUE THREAD

**Issue by felyx** [facelessuser/BracketHighlighter#375]
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

For bugs, provide errors from console, examples etc.  For feature requests, describe the desired feature.  Be as detailed as possible. Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

As I said in some cases the starting bracket doesnt match the ending bracket but it works the other way around, see below.

---

### Issue Support Info

For bugs, run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.  Omit for feature requests.

- ST ver.:        3126
- Platform:       windows
- Arch:           x64
- Plugin ver.:    2.21.3
- Install via PC: True
- mdpopups ver.:  1.10.0
- backrefs ver.:  1.0.post1
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8

### Steps to Reproduce Issue

Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests.

As I said in some cases the starting bracket doesnt match the ending bracket but it works the other way around: 

When the cursor is at the starting bracket theres no match to the ending bracket:

![bh-1](https://cloud.githubusercontent.com/assets/421171/19020468/cf00ef94-88a9-11e6-8299-9d9c22894ef0.PNG)

When the cursor is at the ending bracket theres a match to the starting bracket:

![bh-2](https://cloud.githubusercontent.com/assets/421171/19020469/cf03fda6-88a9-11e6-9a39-92b1154a5e45.PNG)
![bh-3](https://cloud.githubusercontent.com/assets/421171/19020470/cf07e40c-88a9-11e6-9b18-16071b346d4f.PNG)

And here is the full block of code (PHP, Laravel framework):

```
if ($validator->fails()) {
            return Redirect::to('admin/contracts/list')
                ->withErrors($validator)
                ->withInput();
        } else {

            $data = array(
                'search_query' => Input::get('search_query'),
                'search_contract_type' => Input::get('search_contract_type')
            );

//            DB::connection()->enableQueryLog();

            $contracts = Contracts::with('partners', 'contract_invite', 'field_contents', 'custom_fields')
                ->where(function ($q) use ($data) {
                    $q->where('subject', 'LIKE', '%' . $data['search_query'] . '%')
                        ->orWhere('custom_content', 'LIKE', '%' . e($data['search_query']) . '%')
                        ->orWhereHas('field_contents', function($q) use ($data) {
                            $q->where(function ($q) use ($data) {
                                $q->where('field_title', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('field_content', 'LIKE', '%' . $data['search_query'] . '%');
                            });
                        })
                        ->orWhereHas('custom_fields', function($q) use ($data) {
                            $q->where(function ($q) use ($data) {
                                $q->where('field_title', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('field_content', 'LIKE', '%' . $data['search_query'] . '%');
                            });
                        })
                        ->orWhereHas('partners', function($q) use ($data) {
                            $q->where(function ($q) use ($data) {
                                $q->where('name', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('mothers_name', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('personal_id_number', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('address', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('phone', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('email', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('company_name', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('company_tax_number', 'LIKE', '%' . $data['search_query'] . '%')
                                    ->orWhere('company_residence', 'LIKE', '%' . $data['search_query'] . '%');
                            });
                        });
                })
//                ->where('contract_type_id', $data['search_contract_type'])
                ->where(function($q) use ($data) {
                    if ($data['search_contract_type'] != 'all')
                    {
                        $q->where('contract_type_id', $data['search_contract_type']);
                    }
                })
                ->orderBy('created_at', 'DESC')
                ->paginate(10);

//            dd(DB::getQueryLog());

            return View::make('admin.contracts.search')->with(array('contracts' => $contracts, 'search_query' => $data['search_query'], 'search_contract_type' => $data['search_contract_type']));
        }
```

**Comment by facelessuser** [comment]
Most likely it has to do with the search window.  I don't know what your search window settings are.  Are your BH thresholds set to default?  If so, try increasing them.  Your search window will not be the exact same buffer of source code when selecting the end bracket vs the first bracket, and if your search threshold window is small, it won't match.  You can test if BH has a logic error by running the command `BracketHighlighter: Match Brackets (ignore threshold)` from the command palette to confirm if it matches the brackets when no threshold is applied.  If it matches fine, then it isn't a logic error, but a it reaching the current threshold limit.  I personally use a threshold of `10000` which is much bigger than the default.

**Comment by felyx** [comment]
Thank you, it was indeed the threshold that was set to too small which caused my "issue". Thank you once again for taking the time to help me out!

**Comment by facelessuser** [comment]
No problem.
