### ISSUE TITLE
[Question] Highlight tag angle brackets

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/BracketHighlighter#377]
### Briefly

I don't understand, how I can highlight angle brackets in tags.

### Expected behavior

Highlight tags with angle brackets.

![Expected behavior](http://i.imgur.com/T5gARs3.png)

### Actual behavior

Highlight tags without angle brackets.

![Actual behavior](http://i.imgur.com/DeWm23A.png)

### Did not help

Part of my `User\bh_core.sublime-settings` file:

```json
"tag": {
    "icon": "tag",
    "color": "brackethighlighter.tag",
    "style": "outline",
},
```

I try add [all values](http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style) to `style` parameter, but I don't get expected behavior.

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by facelessuser** [comment]
Make sure that template gets followed when creating an issue on this repo.  Eventually, all of my repos will  follow a similar pattern.  I appreciate the clearness of expected vs actual, but it is also helpful for me to get info such as BracketHighlighter version and such as that can be critical in helping to solve bugs.

> I don't understand, how I can highlight angle brackets in tags.

To answer your question now.  The main picture on the readme does show the entire tag being highlighted.  That was from a much earlier version of bracket highlighter.  It became kind of annoying having the entire tag highlighted (attributes and all).  So a change was made directly in the tag module to just highlight the tag name to be a little more less annoying.  It is a bit more low profile, but it also less distracting than when it was encompassing the entire tag with attributes.

Unfortunately, it is not configurable.  Ideally, I should update the main image to reflect the current behavior.

**Comment by D-side** [comment]
Surprisingly enough (for me, anyway) I've found a way to do this without modifying the source code, only using configuration.

Putting the following in "Tag Settings &ndash; User" does just that for HTML:

```json
{
  "tag_style": {
    "html": null
  }
}
```

**Undocumented, no promises, YMMV, etc.**

**Comment by facelessuser** [comment]
lol.  Well that is new :smile:.  It was unintentional, but I guess that works.  That setting was supposed to give an alternative icon when the tag module overrides the angle rule, but it looks like I added an undefined state that brings back full tag highlight.

**Comment by facelessuser** [comment]
I can not promise this will always remain, but I have no intention of going out of my way to change this behavior.

**Comment by facelessuser** [comment]
As question has been answered, I will close this.
