### ISSUE TITLE
Allow the `bh_remove_brackets` command to take args for faster use

### ISSUE THREAD

**Issue by drew-wallace** [facelessuser/BracketHighlighter#380]
I really like the remove brakets plugin, but I would love it if it could take arguments so I wouldn't need to select a menu item each time. The idea would be, if the keybinding has args, forget the menu and use the args to send to the plugin.
```json
{
  "keys": ["alt+shift+w"],
  "command": "bh_remove_brackets"
}
```
to this
```json
{
  "keys": ["alt+shift+w"],
  "command": "bh_remove_brackets",
  "args" : {
    "indent" : true,
    "block": true,
    "content": false
  }
}
```

### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

For bugs, provide errors from console, examples etc.  For feature requests, describe the desired feature.  Be as detailed as possible. Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

---

### Issue Support Info

For bugs, run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.  Omit for feature requests.

### Steps to Reproduce Issue

Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests.

**Comment by facelessuser** [comment]
This is already possible.  All I did was write a front end for it: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_remove.py#L31.

So if you want a keymap:

```js
    {
        "keys": ["alt+shift+w"],
        "command": "bh_key",
        "args":
        {
            "plugin":
            {
                "type": ["__all__"],
                "command": "bh_modules.bracketremove",
                "args": {"remove_content": true, "remove_indent": false, "remove_block": true}
            }
        }
    },
```

**Comment by facelessuser** [comment]
Please do follow the template in the future.  Post version and put description under description.  Omit things that aren't applicable.

**Comment by drew-wallace** [comment]
Ah, thank you.
