### ISSUE TITLE
user_brackets is inconvenient to use in some cases

### ISSUE THREAD

**Issue by jfcherng** [facelessuser/BracketHighlighter#385]
## Description

`user_brackets` is inconvenient to use in some cases because user-defined brackets having lower priorities than built-in brackets.

## Support Info

```
- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.23.0
- Install via PC: True
- mdpopups ver.: 1.11.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1.3
- jinja2 ver.: 2.8
```

## Steps to Reproduce Issue

Let's say I wants to highlight `{%` `%}` pair and `{{` `}}` pair in `HTML (Twig)` langueage.
So I have following settings in my `bh_core.sublime_setting`:

```javascript
{
    "user_brackets": [
        // HTML (Twig)
        {
            "name": "twig_tag",
            "open": "({%)",
            "close": "(%})",
            "style": "angle",
            "language_filter": "whitelist",
            "language_list": ["HTML (Twig)"],
            "enabled": true
        },
        {
            "name": "twig_variable",
            "open": "({{)",
            "close": "(}})",
            "style": "curly",
            "language_filter": "whitelist",
            "language_list": ["HTML (Twig)"],
            "enabled": true
        },
    ],
}
```

But the settings above would not work as expected because the built-in `curly` rule will be matched first.

## My current workaround

Disable the `curly` rule for `HTML (Twig)` and add a `twig_curly`, which is exactly the same with `curly` but only works in `HTML (Twig)`, to the last part of my `user_brackets`. So it matches `twig_tag` and `twig_variable` first and then `twig_curly`.

```javascript
{
    "user_brackets": [
        // disable curly for HTML (Twig)
        {
            "name": "curly",
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex", "HTML (Twig)"],
        },
        // HTML (Twig)
        {
            "name": "twig_tag",
            "open": "({%)",
            "close": "(%})",
            "style": "angle",
            "scope_exclude": [],
            "language_filter": "whitelist",
            "language_list": ["HTML (Twig)"],
            "enabled": true
        },
        {
            "name": "twig_variable",
            "open": "({{)",
            "close": "(}})",
            "style": "curly",
            "scope_exclude": [],
            "language_filter": "whitelist",
            "language_list": ["HTML (Twig)"],
            "enabled": true
        },
        // add curly that only works in HTML (Twig)
        {
            "name": "twig_curly",
            "open": "(\\{)",
            "close": "(\\})",
            "style": "curly",
            "scope_exclude": [
                "string",
                "comment",
                "source.regexp constant.character.escape"
            ],
            "language_filter": "whitelist",
            "language_list": ["HTML (Twig)"],
            "find_in_sub_search": "true",
            "ignore_string_escape": true,
            "enabled": true
        },
    ],
}
```

## My Suggestion

`user_brackets` should always have the highest priority because it's user-defined. If this makes it hard to implement the overriding for built-in rules, we could add another section, for example `override_brackets`, to do it.

**PS.** `user_scope_brackets` have the same problem too.

### Settings merging steps

0. Add `user_brackets` as the base
0. Merge/Override it with `brackets`
0. Merge/Override it with `override_brackets`

```javascript
{
    "override_brackets": [
        // this section is used to override rules and
        // will be merged in the last stage
    ],
    "user_brackets": [
        // this section is used to add user-defined rules and
        // will be added in the very first stage
    ],
}
```

**Comment by facelessuser** [comment]
Thank you for your contribution to BracketHighlighter.  Unfortunately BracketHighlighter now requires all issues to follow the [issue template](https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md). 
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

One the opening post has been updated, I will be happy to help you with this issue 😄 .

**Comment by jfcherng** [comment]
@facelessuser sorry about that. updated.

**Comment by facelessuser** [comment]
@jfcherng  thanks!

So there is actually a whole [section](http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management) in the documentation that explains how to deal with your issue, I will paraphrase here.

So yes, user brackets do get appended to the end.  In a lot of cases this is fine, but obviously not all.  Some times you may not only need to move your rule before the default ones, but you might need to your rule before the defaults, but one or two defaults need to be before yours.  This creates something more complicated than  a `user_brackets` and `override_brackets` could easily handle.

But no fear, you manually specify the index of your rule, or even change the index of your existing rule.  So each rule has an implicit position.  The first default rule is in position zero and so on through user brackets.  If in your `user_brackets` you override an existing default rule that is position 0, it will still be in position 0.  This is nice so that overriding doesn't break the existing carefully constructed order.  But if you need to, you can  enable debug mode and run a command to see all the position indexes of all the rules.  And then you can manually specify the index with the `position` parameter.  This allows you to insert, append, prepend, and even move existing rule positions.  Check out the documentation and let me know if you have any other questions.

**Comment by facelessuser** [comment]
FYI, I did notice a mistake in the documentation.  Where I use `mylang` as the example language, I mess up in one of the examples and it is called `trex`.  Don't let that confuse you.  I'll fix that tonight.

**Comment by jfcherng** [comment]
@facelessuser Thanks. I assign a position shift to built-in rules and it resolves my problem perfectly. :+1: 

![image](https://cloud.githubusercontent.com/assets/6594915/20397732/c579ec32-ad25-11e6-9bc4-f89b82236866.png)

**Comment by facelessuser** [comment]
I should probably mention that you don't have to assign positions to all defaults, but it doesn't hurt.  If you create a new rule with position 0, all the implicit positions should shift as now position 0 is taken.  Manually manual have the highest weight, then implicit fill in the gaps.  But either way it should work.

**Comment by jfcherng** [comment]
@facelessuser I was doing that because position 0 is `curly` by default but assigning 0 would cause nothing to happen. Assigning 1 works as expected so I am not sure that assign 0 triggers a bug or not.

**Comment by facelessuser** [comment]
@jfcherng, I will take a look at that later.  Thanks for letting me know.

**Comment by facelessuser** [comment]
Yeah, now that I see the picture you posted, yeah that is a bug.

**Comment by facelessuser** [comment]
This will be fixed in the next version via https://github.com/facelessuser/BracketHighlighter/commit/3ffac9122b6c7bbe937f18c538e470e6f80738ea.
