### ISSUE TITLE
How to do continued underline when inside a tag, instead of dotted style?

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/BracketHighlighter#388]
### How to do continued underline when inside a tag, instead of dotted style?

On this screen shot, we may see the cursor on the tag corner, and tag is well underlined within a solid line:

![image](https://cloud.githubusercontent.com/assets/5332158/20459366/f4fd3b04-aea5-11e6-99ae-d39affccd909.png)

However, here we may see when the cursor is inside the tag. The tag is not well underlined, its line is dotted, not solid underlined.

![image](https://cloud.githubusercontent.com/assets/5332158/20459329/30fb6790-aea4-11e6-8fe6-3296286f5915.png)

I searched on the documentations, issues, and checked my settings and my theme file, and I do not find any mention to this ugly dotted underline behavior.

On the `Support Info` section, I am putting also my current settings and theme file.

### Support Info

```
- ST ver.: 3126
- Platform: windows
- Arch: x32
- Plugin ver.: 2.23.0
- Install via PC: True
- mdpopups ver.: 1.11.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

1. https://github.com/evandrocoan/SublimeTextStudio/blob/develop/User/bh_core.sublime-settings
1. https://github.com/evandrocoan/SublimeNotepadPlusPlusTheme/blob/e9a21fed9a4e2a511bab07759988726f9b45530f/Default%20Stylers.tmTheme#L57-L143

**Comment by facelessuser** [comment]
You're going to feel silly when I point this out...

`User/Preferences.sublime-settings`:

```
"match_tags": true,
```

You should probably pick 1 tag highlighter 😉 .

**Comment by evandrocoan** [comment]
Thanks for your time, and sorry for do not find it.

But I kinda do not understood the `match_tags` behavior from the settings doc:
```
    // Enable visualization of the matching tag in HTML and XML
    "match_tags": true,
```
Why does this would create dotted underline instead of continue/solid underline on my tags, anyways
the other settings as `match_brackets`, states it is underline.
```
    // Set to false to disable underlining the brackets surrounding the caret
    "match_brackets": true,
```

**Comment by facelessuser** [comment]
@evandrocoan The dotted line is the builtin tag matcher.  BH does the solid.  When they are both on, you get both, but one is going to be more dominant I guess.

**Comment by evandrocoan** [comment]
Yes, and thank you for doing it solid. Much better this way. Highlighting stuff on the text does not is the Sublime Text builtin strength.

**Comment by facelessuser** [comment]
Glad you got it working.  This makes me think I probably need to mention this in the documentation.   This is not the first time someone has asked about the `match_tag` conflict.

**Comment by evandrocoan** [comment]
May be some examples could be useful when you say:

> or you will have matching conflicts

or you will have matching conflicts as `dotted` underline instead of solid ones.

**Comment by facelessuser** [comment]
It's not just dotted line issues.  Sublime's matcher behaves differently at times.  I think the real point is that people need to turn off one or the other and not try to use both.
