### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ignore_all'

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/BracketHighlighter#390]
### AttributeError: 'NoneType' object has no attribute 'ignore_all'

On Sublime Text start:
```
( plugin_loaded ) Calling on_activated, view id 15
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "bh_core in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\BracketHighlighter.sublime-package", line 1055, in on_selection_modified
  File "bh_core in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\BracketHighlighter.sublime-package", line 1077, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "scope_hunter in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\ScopeHunter.sublime-package", line 632, in on_selection_modified
AttributeError: 'NoneType' object has no attribute 'is_enabled'
```

One of this appears after each time of this call:
```
def plugin_loaded():

    views   = None
    windows = sublime.windows()

    for window in windows:

        views = window.views()

        for view in views:

            print( "( plugin_loaded ) Calling on_activated, view id {0}".format( view.id() ) )
            view.run_command( "move", {"by": "lines", "forward": False} )
            view.run_command( "move", {"by": "lines", "forward": True} )
```

## Support Info
```
- ST ver.: 3126
- Platform: windows
- Arch: x32
- Plugin ver.: 2.23.0
- Install via PC: True
- mdpopups ver.: 1.11.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

## Steps to Reproduce Issue

1. Create a plugin with the `plugin_loaded()` python instructions above.
1. Open Sublime Text and some files.
1. Close and open Sublime Text.
1. Open the console.
1. Wait until the forward `plugin_loaded()` to be called.

**Comment by facelessuser** [comment]
I've had something like this reported before by one person, but I am yet to reproduce something like this ever.  It may have to do when packages are bundled as `sublime-package` files.  But here's the thing.  Sublime is *supposed* to run `plugin_loaded` for all packages before it starts firing off their events.

We can see that we initialize bh_thread in `plugin_loaded`: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.py#L1179.

But your error report shows this:

```
File "bh_core in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\BracketHighlighter.sublime-package", line 1077, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
```

But when we see that is an attribute of `bh_thread`: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.py#L1077.

If I were to patch that one attribute, another one probably throw an error because you are having some weird case where sublime is running plugin events before `plugin_loaded`.  Not sure what is expected for me to do as I need to initialize things in `plugin_loaded` before events get handled.  This feels like a Sublime bug.  It also seems to only happen to very certain people.  Is it because you are syncing your plugins with dropbox?  Is it only when with zipped forms of BH?  From what I remember, the other guy who had this issue, it was only a problem on first load of Sublime.

One thing that seems clear is that it has to do with a Sublime bug.  **Maybe** I can initialize the structures and classes I need outside of `plugin_loaded`, I don't know yet.  But I know I shouldn't have to.

I will look and see if there is something I can do to ensure the important thread class is loaded, but if it turns out I **have** to have it loaded  in `plugin_loaded`, then there is nothing I can do.

**Comment by facelessuser** [comment]
I might just have to put a check to exit all Sublime events if bh_thread is none.  Maybe that will fix things.

**Comment by evandrocoan** [comment]
## Question 1

> I am yet to reproduce something like this ever. It may have to do when packages are bundled as sublime-package files. 

You cannot reproduce this? Create a package with the same name as mime: 
```
Fix Project Switch-Restart Bug\fix_project_switch_restart_bug.py
```
With the same contents:
```python



import sublime
import sublime_plugin

# this var is not used yet
lastOnLoadViewCallTime = 0



def plugin_loaded():

    # print( "( fix_project_switch_restart_bug.py )" )

    views         = None
    windows       = sublime.windows()
    currentViewId = 0

    for window in windows:

        views         = window.views()
        currentViewId = window.active_view().id()

        for view in views:

            # print( "( fix_project_switch_restart_bug.py ) View id {0}, buffer id {1}".format( view.id(), view.buffer_id() ) )

            if currentViewId != view.id():

                restore_view( view )
                view.run_command( "move", {"by": "lines", "forward": False} )
                view.run_command( "move", {"by": "lines", "forward": True} )


def restore_view( view ):
    """
        view.set_viewport_position( , False )
    """

    # for selection in view.sel(): print( "( fix_project_switch_restart_bug.py ) Iterating view.sel()[i].begin() {0}".format( selection ) )

    # print( "( fix_project_switch_restart_bug.py ) Setting show_at_center to view id {0}".format( view.id() ) )
    view.show_at_center( view.sel()[0].begin() )



def are_we_on_the_project_switch_process():
    """
        Call `plugin_loaded()` only one time, after the project switch process is finished.

        Restrictions:
        1. We cannot call `plugin_loaded()` if this function is called only one time.
        2. If this function is called consequently 2 times with less than 0.1 seconds, then we
           must to return True.
           Basically, on each call
    """

    # set task to call plugin_loaded() after 2 seconds, if this task currently does not exists.

    return False



class OnLoadedViewCommand( sublime_plugin.EventListener ):
    """
        This partially fix the issues:

        Restore session, does not set the last scroll position after a project change, or sublime restart #1379
        https://github.com/SublimeTextIssues/Core/issues/1379

        Scroll sync doesn't work (ST3 3084)
        https://github.com/titoBouzout/BufferScroll/issues/23

        Finish the package: Fix Project Switch-Restart Bug
        https://github.com/evandrocoan/SublimeTextStudio/issues/26
    """

    # def on_load( self, view ):
    def on_load_async( self, view ):
    # def on_activated( self, view ):
    # def on_activated_async( self, view ):

        # { "keys": ["up"], "command": "move", "args": {"by": "lines", "forward": false} },
        # { "keys": ["down"], "command": "move", "args": {"by": "lines", "forward": true} },
        # view.run_command( "move", {"by": "lines", "forward": False} )
        # view.run_command( "move", {"by": "lines", "forward": True} )
        #
        # print( "( fix_project_switch_restart_bug.py ) Calling restore_view, view id {0}".format( view.id() ) )

        # Need to fix to the bug on the Sublime Text core, where all cloned views are called with the same
        # view object. If we do not fix this here, it would set all the cloned views to the same
        # position. So to overcome this, we call all the views to center with `plugin_loaded()`.
        #
        # #1253 Event handlers for cloned views get called with the wrong view object
        # https://github.com/SublimeTextIssues/Core/issues/1253
        #
        # The `on_load_async()` is called for each view on for the project change, however
        # due the bug https://github.com/SublimeTextIssues/Core/issues/1253, the cloned
        # views are called with the wrong `view`, then we need to call `plugin_loaded()` to catch
        # all the correct views (including the cloned ones) to apply the scroll fix for the bug
        # https://github.com/SublimeTextIssues/Core/issues/1379.
        #
        if not are_we_on_the_project_switch_process():

            restore_view( view )
```

## Question 2

> Is it only when with zipped forms of BH? 

I uninstalled the package and cloned it. Stills the same error, but now pointing to the real `.py` file.
```
plugins loaded
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\BracketHighlighter\bh_core.py", line 1055, in on_selection_modified
    if self.ignore_event(view):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\BracketHighlighter\bh_core.py", line 1077, in ignore_event
    bh_thread.ignore_all or
AttributeError: 'NoneType' object has no attribute 'ignore_all'
```

## Question 3

>  Is it because you are syncing your plugins with dropbox?

I do not sync anything with dropbox, it is on the dropbox folder for backup purposes. I sync things with git at the develop branch: https://github.com/evandrocoan/SublimeTextStudio/commits/develop, but only the absolute necessary as settings and source code files.


## Question 4

> Maybe I can initialize the structures and classes I need outside of plugin_loaded

You can, you just cannot call the Sublime API outside the `plugin_loaded()` forward.


## Question 5

> I will look and see if there is something I can do to ensure the important thread class is loaded, but if it turns out I have to have it loaded in plugin_loaded, then there is nothing I can do.

Seems simple, if it being called when its state is `None`, check for `None` before call it. However it seems not worth spend all the plugin life cycle checking for `None`, just for something which happens exactly for some microseconds on the plugins load. On this case would be wise on start calling the events those microseconds later.

I looked over the code and just surrounding it with a `try... catch` block seems appropriate. I just did it and seems to be working properly. Is it patched?
```python
File: D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\BracketHighlighter\bh_core.py
1077:         try:
1078: 
1079:             return (
1080:                 bh_thread.ignore_all or
1081:                 settings.get('bracket_highlighter.ignore', False) or
1082:                 (
1083:                     settings.get('is_widget') and
1084:                     not sublime.load_settings("bh_core.sublime-settings").get('search_in_widgets', False)
1085:                 )
1086:             )
1087: 
1088:         except Exception as e:
1089: 
1090:             pass
1091: 
1092:         return True
```

## Question 6

After my patch on `Question 5`, it stopped doing it. Now it looks like we got the same problem only with `ScopeHunter`:
```python
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "scope_hunter in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\ScopeHunter.sublime-package", line 632, in on_selection_modified
AttributeError: 'NoneType' object has no attribute 'is_enabled'
```

**Comment by facelessuser** [comment]
> You cannot reproduce this? Create a package with the same name as mime:

It's more complicated than that.  I mentioned I've seen this before:

- https://github.com/facelessuser/BracketHighlighter/issues/305
- https://github.com/facelessuser/BracketHighlighter/issues/232

It's not just you need your plugin and and then it fails.  It is a bit more complicated.  I have all of mine installed locally as I develop on them, and they are not zipped like they would be for those who use Package Control.  Is that part of it?  I don't know.  I've tried to reproduce this issue before with people.  I figured they were isolated situations, but this is the third time.

> I do not sync anything with dropbox, it is on the dropbox folder for backup purposes. I sync things with git at the develop branch: https://github.com/evandrocoan/SublimeTextStudio/commits/develop, but only the absolute necessary as settings and source code files.

The point really that I have a hard time duplicated this and I feel there is some other factors at play.

> You can, you just cannot call the Sublime API outside the plugin_loaded() forward.

Yes I am aware it is possible, I just didn't know if it was possible for how I was doing things.   The statement was more suggesting that I need to look at how **I** handle things in my code to determine if **I** could do it.

> Seems simple, if it being called when its state is None, check for None before call it.

I don't want to waste cycles on this, but if I have to, I will. I don't think I want to mask other errors by using a try catch.  And I would need to implement this in every event to be safe.  I could evaluate the failure in the catch, but I'm just not sure if it is worth all that to save the insignificant amount of time lost to do the None check.

**Comment by facelessuser** [comment]
I believe HexViewer is still susceptible to this as well, not just ScopeHunter, but ColorHelper looks to be protected against this currently.

**Comment by evandrocoan** [comment]
Basically it looks like the `static initialization` problem. Sublime Text cannot call all the forwards `plugin_loaded()` at the same time. So some of them are called before the others. I would bet they are called alphabetically by package name, for example. But it just a matter of test to know exactly.

The code I am presenting to trigger the bug is moving the caret/cursor up and down fastly. This trigger the `BracketHighlighter` to perform its function. However, my plugin seems to be loaded before the BracketHighlighter's `plugin_loaded()` forward. This way, the registered BracketHighlighter's forward `on_selection_modified(2)` is called when the `BracketHighlighter` plugin is on an inconsistent state.

This indeed seems to be a `Sublime Text` core bug. Sublime Text cannot call the plugins forwards as `on_selection_modified(2)` before the plugin goes through the forward `plugin_loaded()`. Because it seems funny bug, I am gonna try to create a small code reproduction and report it on the Sublime Text core issue tracker. But before I am going to check whether this an issue and if it was already reported.

**Comment by facelessuser** [comment]
Sounds good.  I will have a fix in a release probably tomorrow.
