### ISSUE TITLE
Doesn't correctly match nested <span> tags.

### ISSUE THREAD

**Issue by raimondsf** [facelessuser/BracketHighlighter#391]
Hey all,

Currently highlights only the nested open tag if you select either of the ending tags.

<span>Bedrooms: <strong><span id="bedroomsVal">0</strong></span></span>

**Comment by raimondsf** [comment]
That was my mistake. The code wasn't correctly written.

**Comment by facelessuser** [comment]
Glad you figured it out. Next time please do follow the template for support.
