### ISSUE TITLE
Having trouble with custom brackets and Go Sublime HTML

### ISSUE THREAD

**Issue by justrjlewis** [facelessuser/BracketHighlighter#399]
## Description

I have defined some custom brackets and they're not being recognized in my html files if I use the [GoSublime highlighting package](https://github.com/DisposaBoy/GoSublime).  I added "GoSublime" and "GoSublime: HTML" to the language list, but the settings aren't taking.  For example I have a custom html bracket wrapper in html files to add a comment around a selection and allow me to explain the scope and I have to switch the syntax to regular html then switch back to get it to work.

Here's my HTML user setting:

```
// HTML
		{
			"name": "html",
			"open": "(<)(?=[\\w\\:\\-]+(?:(?:\\s+[\\w\\-:]+(?:\\s*=\\s*(?:\"[^\"]*\"|'[^']*'|[^>\\s]+))?)*)\\s*\\/?>|\\/[\\w\\:\\-]+[^>]*>)",
			"close": "(?<=<)(?:[\\w\\:\\-]+(?:(?:\\s+[\\w\\-:]+(?:\\s*=\\s*(?:\"[^\"]*\"|'[^']*'|[^>\\s]+))?)*)\\s*\\/?|\\/[\\w\\:\\-]+[^>]*)(>)",
			"style": "tag",
			"scope_exclude": ["string", "comment"],
			"language_filter": "whitelist",
			"language_list": ["HTML", "HTML 5", "XML", "PHP","GoSublime", "GoSublime: HTML"],
			"plugin_library": "bh_modules.tags",
			"find_in_sub_search": "only",
			"enabled": true
		}
```

tag mode settings: 
```
// Determine which style of tag-matching to use in which syntax
	"tag_mode": {
		"xhtml": ["XML"],
		"html": ["HTML", "HTML 5", "PHP", "HTML (Jinja Templates)", "HTML (Rails)", "HTML (Twig)", "GoSublime", "GoSublime: HTML"],
		"cfml": ["HTML+CFML", "ColdFusion", "ColdFusionCFC"]
	}
```

## Support Info

...

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.23.1
- Install via PC: True
- mdpopups ver.: 1.12.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Customize html bracket/tag settings
2. install GoSublime and add to language definitions

Just wondering if this is an actual bug, or if I've added the language definition incorrectly.  
Thank you!

**Comment by facelessuser** [comment]
I wouldn't use the rule you are using.  I would append your `go` stuff to the default tag rule: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L369.

**Comment by justrjlewis** [comment]
Do you think that the terms i'm using are okay?  
`"GoSublime", "GoSublime: HTML"`

**Comment by facelessuser** [comment]
You should use the syntax file name (minus the extension), not what you see in the bottom right hand corner of Sublime.  I believe you are looking for [`GoSublime-HTML`](https://github.com/DisposaBoy/GoSublime/blob/master/syntax/GoSublime-HTML.tmLanguage).

**Comment by justrjlewis** [comment]
Yay!  It's working now.  Thanks!
