### ISSUE TITLE
Feature Request - Special rule for start/end tag for latex documents 

### ISSUE THREAD

**Issue by diego898** [facelessuser/BracketHighlighter#401]
## Description

The last closing tag of my latex documents is always `\end{document}`. The length of my documents can't be predicted ahead of time, so I can't set my settings correctly for brackethighlter to correctly search for the `\begin{document}` tag, which is usually (99% of the time) located in the top 20 lines of the file. In my mind, this is really the only latex tag which will typically extend that long. It might make sense to make a special rule for that specific open/close that searches the first X lines of the file, and the last Y lines of the file for opening/close pair

**Comment by facelessuser** [comment]
1. Please follow the template next time.
2. The bracket search framework is purposefully generic.  I am afraid I have no intentions of adding specific logic to account for one specific type of bracket.

I'm going to have to pass on this.  You can always use the on-demand bracket search which ignores the threshold if you need to see the pairing.
