### ISSUE TITLE
Cant find in sublime 3 now. 

### ISSUE THREAD

**Issue by kangarooo** [facelessuser/BracketHighlighter#402]
![braackeeet](https://cloud.githubusercontent.com/assets/73187/23681919/bf685ebc-0399-11e7-9c93-6a2aaaee3f46.JPG)
Cant find in sublime 3 now

**Comment by facelessuser** [comment]
Is it already installed?  Check your `Packages` folder and/or `Installed Packages` folder.  It seems to be showing up in Package Control for ST3  https://packagecontrol.io/packages/BracketHighlighter.

If it isn't showing up, and you don't have it already installed (even a broken version), you may need to file an issue with Package Control as it seems to be showing up on their site fine which indicates that they see it.

There is nothing I can do here, but I suspect you already have it installed.  Maybe you tried to clone it or the install went bad, but I think Package Control is most likely seeing a local copy and not giving you a chance to install.  If that is not true, you'll have to ask them why else it might not be showing up.

**Comment by kangarooo** [comment]
Yes it was in there but still wasnt showing. I thought that https://packagecontrol.io/ was already embedded in sublime since i could find and install a lot packages but this one wasnt able to until i installed again. And even 2 times. Even got sublime to crash. I have no idea what made it finally to work and appear since appeared after 2nd time installing https://packagecontrol.io/ and restarting programm again.

But trying to remove channel says that only 1 channel is added. So that means i didnt installed 3rd time but brackets appeared without logic i saw.

**Comment by facelessuser** [comment]
I can only guess what what was going on, but I just support the plugin, not Package Control.  I'm glad you were able to get it installed.
