### ISSUE TITLE
Is there any shortcut key for jump between close and open mark? 

### ISSUE THREAD

**Issue by dotku** [facelessuser/BracketHighlighter#404]
Eg, the HTML close and close tag?

**Comment by facelessuser** [comment]
I think this is what you are looking for: https://github.com/facelessuser/BracketHighlighter/issues/405.

Please use the issue template when creating issues next time.  Thanks.

**Comment by facelessuser** [comment]
Did the suggestion work for you?  If not please give a detailed instructions.  I leave issues open for about a week when waiting for additional info to determine if the issue is valid.  If I don't hear back in about a week, I usually close the issue.
