### ISSUE TITLE
[feature] Command equivalent to CTRL+M

### ISSUE THREAD

**Issue by LucaMoschella** [facelessuser/BracketHighlighter#405]
There isn't an equivalent to sublime text CTRL+M (jump to the _other_ bracket)?

**Comment by r-stein** [comment]
Just add this to your keymap:

``` js
    {
        "keys": ["ctrl+m"],
        "command": "bh_async_key",
        "args": {
            "no_outside_adj": null,
            "lines": true,
            "plugin": {
                "command": "bh_modules.bracketselect",
                "args": {"select": "right", "alternate": true},
                "type": ["__all__"]
            },
            "no_block_mode": null
        },
    },
```

**Comment by LucaMoschella** [comment]
That's great, thanks!

**Comment by facelessuser** [comment]
@r-stein is correct.  I rarely add any shortcuts by default to my plugins to prevent shortcut conflicts.  I let the user manage their own shortcuts.

**Comment by LucaMoschella** [comment]
Yeah, the problem Is that at the moment I do not have time to learn how to write the definitions of shortcuts  ...

Would be great if in the "shortcuts examples" there were the ones that are supposed to override.
eg. the one that "expands" the selection to the next pair of brackets (CTRL+SHIFT+SPACE if I remember well)

**Comment by facelessuser** [comment]
> Yeah, the problem is that at the moment I do not have time to learn how to write the definitions of shortcuts...

Is what you were looking for not here? https://github.com/facelessuser/BracketHighlighter/blob/master/Example.sublime-keymap.

It's a challenge at times managing all the plugins that I do.  To a large degree, I rely on the community to help me get this kind of stuff documented.  If you feel an example could be added to help out people in the future, please do issue a pull request.

**Comment by LucaMoschella** [comment]
I see. No... it's not there. 

There is the shortcut that "Select text between brackets" and if the text is already selected, it deselects the text.

I was thinking to have a similar beahvior of the CTRL+SHIFT+SPACE, that is "expand the current selection" to the next pair of brackets. 

eg. (where | is the cursor)

Initial situation: { test1 " te|st2 " test3 }
1° press : {test1"`te|st2`"test3}
2° press: {test1`"te|st2"`test3}
3° press: {`test1"te|st2"test3`}
4° press: `{ test1"te|st2"test3}`

**Comment by r-stein** [comment]
Use this keybinding:

```js
    {
        "keys": ["ctrl+shift+space"],
        "command": "bh_async_key",
        "args": {
            "plugin": {
                "type": ["__all__"],
                "command": "bh_modules.bracketselect"
            },
            "lines": true,
            "no_outside_adj": null
        },
    },
```

The `"no_outside_adj": null` musst be in the `"args"`

**Comment by facelessuser** [comment]
@r-stein beat me to it :slightly_smiling_face: .  Yes, that is exactly what I use.

**Comment by LucaMoschella** [comment]
I get the impression that sharing your shortcuts (related to BH), by inserting them in the example file, would be a huge help :D

Thanks a lot!

**Comment by facelessuser** [comment]
That's basically what I already did.  But I if I tweak my settings, I don't always remember to update examples in BH.  My personal settings aren't auto synced to BH.  Again, that is why pull requests can be helpful to make sure this information gets out there.

**Comment by Drarok** [comment]
This feature seems like an absolute must-have! Installing BracketHighlighter with the recommended settings disables the built-in `ctrl+m` and `ctrl+shift+m` shortcuts for jumping between brackets, and selecting between brackets.

This should definitely be included in the example keymap, at the very least.
