### ISSUE TITLE
Highlight only by background

### ISSUE THREAD

**Issue by hxss** [facelessuser/BracketHighlighter#406]
Hello. Can I highlight brackets only by background, whithout underline, borders or other styles? Like in Netbeans. I was try [this ](http://montesjmm.com/2012/09/19/sublime-text-2-bracket-highlighter/)instruction, but in subl3 this dont work.

**Comment by hxss** [comment]
Seems to have found.
In bh user config:
`"bracket_styles": {
	"default": {
		"style": "solid"
	},
}`
And in theme:
`<dict>
            <key>name</key>
            <string>Bracket Default</string>
            <key>scope</key>
            <string>brackethighlighter.default</string>
            <key>settings</key>
            <dict>
                <key>background</key>
                <string>#f00</string>
                
                
            </dict>
        </dict>`

**Comment by facelessuser** [comment]
Glad you figured out out.

**Comment by kanlukasz** [comment]
Information for people looking for a solution based on ST3 JSON (_.sublime-color-scheme_)

### Example with brackets:
A. In BH Bracket Settings (_bh_core.sublime-settings_) put
```
"user_bracket_styles": {
    "curly": {
        "color": "brackethighlighter.curly",
    }
},
```
and change `bracket_styles { default { style }}` from `underline` to `solid`
 
B. In your Color Scheme (_xxxxxx.sublime-color-scheme_)
```
"rules":
[
    {
        "scope": "brackethighlighter.curly",
        "background": "gray"
    }
]

```
