### ISSUE TITLE
Closing TAG mark wrong opening tag

### ISSUE THREAD

**Issue by gavalierm** [facelessuser/BracketHighlighter#407]
If i click on open tag, right closing tag is market out. But if i click on closing tag, first opening tag above is marked out.

Right opening tag is market with underline (default sublime tagOptions marker) 

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.23.3
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

Info has been copied to the clipboard.

Same part of code with correct markup, when i click on opening tag
<img width="433" alt="snimka obrazovky 2017-03-24 o 2 55 45" src="https://cloud.githubusercontent.com/assets/17672623/24277478/7d532df8-103d-11e7-9fe1-6742a775b876.png">

Wrong markup, when i click on closing tag
<img width="601" alt="snimka obrazovky 2017-03-24 o 2 55 52" src="https://cloud.githubusercontent.com/assets/17672623/24277477/7d5214d6-103d-11e7-9b87-2fb4744f6606.png">

little different problem on "a" tag:

when i click on opening tag looks good
<img width="237" alt="snimka obrazovky 2017-03-24 o 3 08 24" src="https://cloud.githubusercontent.com/assets/17672623/24277729/51bb441c-103f-11e7-9215-022544c3f23b.png">

but when i click on closing "</a>" tag is marked only with rounded border, and again default underlined markup is present... next to line number i have "?"

<img width="349" alt="snimka obrazovky 2017-03-24 o 3 08 32" src="https://cloud.githubusercontent.com/assets/17672623/24277744/685289ce-103f-11e7-8821-36e297b2761d.png">

**Comment by facelessuser** [comment]
I can't look at this unless you provide an example I can copy and paste. Pictures are fine, but I'm not going to try and look at the picture to recreate the issue.  Also, please provide an me with what syntax highlighter you are using for your PHP code.  If you are using the default one, then just let me no that it is the default.  Thanks.

**Comment by gavalierm** [comment]
Here is my sample code:

```
        <div id="logo">
            <a href="/<?php echo $html->locales['selected']['region']; ?>"><img src="/img/logo/logo_skarper_red_black_vert.svg">
                <div class="slogan">Professional woodchipper</div>
            </a>
            <div class="wellcome_message">
                <?php echo $html->messages['wellcome_message']; ?>
            </div>
            <div class="wellcome_note">
                <?php echo $html->description; ?>
            </div>
        </div>
```

Here is my user settings:


```
{
	"bracket_styles": {

	"tag": {
            "icon": "tag",
            "color": "brackethighlighter.tag",
            "style": "background"
        }
    }
}
```


My theme is: Monokai

**Comment by gavalierm** [comment]
Here is video of behavior (stored on cloud, because have 60MB) - please watch it if it possible

http://www.uschovna.cz/zasilka/LI2J9EYN5GKKV75T-2B9/

**Comment by facelessuser** [comment]
What syntax highlighter are you using (not color scheme)?

**Comment by gavalierm** [comment]
Sorry maybe i dont uderstand what you mean, i use BracketHighlighter. Is this an answer?

<img width="664" alt="snimka obrazovky 2017-03-24 o 14 09 06" src="https://cloud.githubusercontent.com/assets/17672623/24295566/9c488150-109b-11e7-94f6-07327522aab2.png">

**Comment by facelessuser** [comment]
Yeah, PHP.  Is it the default one or a 3rd party package?

**Comment by gavalierm** [comment]
Is default. I dont use anything special on sublime. 
<img width="504" alt="snimka obrazovky 2017-03-24 o 14 14 05" src="https://cloud.githubusercontent.com/assets/17672623/24295666/2b8d23ac-109c-11e7-8f8f-fc66ca5de0b6.png">

**Comment by facelessuser** [comment]
Thanks.  I'll take a look and let you know what I find.

**Comment by facelessuser** [comment]
I need you to provide me with a tested failing example.  The example you gave me did not show the issues you described.  Please test out the snippet before posting.  For instance, the snippet you posted may fail when included with the rest of your original file, but by itself, it is not failing.

**Comment by gavalierm** [comment]
:O is truth, lol, sorry i dont realize that.

So, this is my all code

```
<?

$html->messages['wellcome_message'] = get_translation_phrase("dd11d6a6739913f5");
$html->description = get_translation_phrase("257c66fd3660a1a3");

//echo "<pre>"; print_r(get_all_phrases()); echo "</pre>";

?>
    <!DOCTYPE html>
    <html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Skarper - Professional woodchipper | Skarper.AT</title>
        <meta name="description" content="<?php echo $html->description; ?>" />
        <link rel="apple-touch-icon" sizes="57x57" href="/img/logo/favicon7/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/img/logo/favicon7/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/img/logo/favicon7/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/img/logo/favicon7/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/img/logo/favicon7/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/img/logo/favicon7/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/img/logo/favicon7/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/img/logo/favicon7/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/img/logo/favicon7/apple-icon-180x180.png">
        <link rel="icon" type="image/png" href="/img/logo/favicon7/favicon-96x96.png">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php 
    //hreflangs
  foreach($html->locales['all_locales'] as $locale_key => $locale ){
    echo '<link rel="alternate" href="https://www.skarper.at/'.strtolower($locale['region']).'" hreflang="'.strtolower($locale['region']).'" />'."\n";
  }
  ?>
        <link rel="alternate" href="https://www.skarper.at/" hreflang="x-default" />
        <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400|Exo:300,400|Exo+2:300,400|Ubuntu:300,400" rel="stylesheet">
        <style type="text/css">
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
        }
        
        body {
            font-family: sans-serif;
        }
        
        a {
            text-decoration: none;
            color: inherit;
        }
        
        img {
            display: block;
        }
        
        .wrapper{
          max-width: 1200px;
        }
        #logo {
            text-align: center;
            opacity: 0;
            -webkit-transition: opacity 2s ease-in;
            -moz-transition: opacity 2s ease-in;
            -ms-transition: opacity 2s ease-in;
            -o-transition: opacity 2s ease-in;
            transition: opacity 2s ease-in;
        }
        
        #logo img {
            width: 100%;
            max-width: 300px;
            margin: auto;
        }
        
        #logo.load {
            opacity: 1;
        }
        
        #logo .wellcome_message {
            font-family: 'Work Sans', sans-serif;
            font-weight: 300;
            padding: 10px;
            font-size: 22px;
        }
        
        #logo .slogan {
            font-family: serif;
        }
        </style>
        <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-93509258-1', 'auto');
        ga('require', 'displayfeatures');
        ga('send', 'pageview');
        </script>
    </head>

    <body onload="document.getElementById('logo').className += ' load';">
        <style type="text/css">
        .header {
            text-align: right;
        }
        
        .locales {
            display: inline-block;
            text-align: left;
            margin: 4px;
        }
        
        .locales a {
            color: black;
            display: block;
            text-decoration: none;
            cursor: pointer;
            border-top: 1px solid #d3d3d3;
            padding: 5px 12px 7px 0px;
            font-size: 12px;
        }
        
        .locales a:first-child {
            border: none;
        }
        
        .locales .local_icon {
            padding: 0px 3px;
            color: transparent;
        }
        
        .locales .selected_locale .local_icon {
            color: #8bc34a;
        }
        </style>
        <div class="header">
            <div class="locales">
                <?php 
      foreach($html->locales['all_locales'] as $locale_key => $locale ){
        echo '<a href="/'.strtolower($locale['region']).'" class="locale_handle '.$locale['classes'].' "><span class="local_icon">&#9679;</span><span class="local_name">'.$locale['local_name'].'</span></a>';
      }
      ?>
            </div>
        </div>
        <div id="logo">
            <a href="/<?php echo $html->locales['selected']['region']; ?>"><img src="/img/logo/logo_skarper_red_black_vert.svg">
                <div class="slogan">Professional woodchipper</div>
            </a>
            <div class="wellcome_message">
                <?php echo $html->messages['wellcome_message']; ?>
            </div>
            <div class="wellcome_note">
                <?php echo $html->description; ?>
            </div>
        </div>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
        <script type="text/javascript">
        function clear_utm_from_url() {
            var currentLocation = window.location.search.replace(/\?/g, '').split('&');
            var new_url = new Array();

            for (i = 0; i < currentLocation.length; i++) {
                var q = currentLocation[i].split('=');
                if (q[0].search("utm_")) {
                    new_url.push(currentLocation[i]);
                }
            }
            if (new_url.length > 0) {
                new_url = "?" + new_url.join("&");
            } else {
                new_url = "";
            }

            history.pushState({}, "", window.location.pathname + new_url);

        }

        $(document).ready(function() {
            //clear_utm_from_url();  
        });
        </script>
    </body>

    </html>

```

**Comment by facelessuser** [comment]
I could not reproduce your issue until I lowered my threshold for search.

I use the following setting in `bh_core.sublime-settings`:

```js
    // Character threshold to search
    "search_threshold": 10000,
```

If you use that setting, I imagine your issue will disappear.  BH, to keep things performing well, doesn't auto-search the entire view, but it searches a window around the cursor whose size is controlled by `search_threshold`.  I just can't let it search the whole file on every key press or selection or BH would slow down Sublime.  Sometimes BH has a hard time resolving all brackets without a bigger window.  I use the setting `10000` in my personal settings as it works well on my system, you can play around with that setting to get your best setting for your system.  Also, if you ever have a bracket that is too far to allow auto-search to find, you can always utilize the mouse-over popup window to search with no threshold (search entire file), or use the command palette command to search with no threshold.

Anyways, it looks like things are working as expected.

**Comment by gavalierm** [comment]
I have this and its default (because I did not change this settings)

```
    // this value will be used.
    "ignore_block_mode_in_plugin": true,

    // Character threshold to search
    "search_threshold": 5000,

    // Ignore threshold
    "ignore_threshold": false,

    // Set mode for string escapes to ignore (regex|string)
    "bracket_string_escape_mode": "string",
```

so i try 10000 and works, thanks for your help!

**Comment by facelessuser** [comment]
Just to explain things a little further.  The reason why sometimes a bracket can be matched one way and not the other is for the following reasons:

1.  The search window created uses the size from `search_threshold`.

2. It splits the size around the cursor equally (or as equal as possible).

3.  Selecting opening vs closing bracket shifts the window since the window is around the cursor.  In the case the window doesn't cover exactly the same chars.  So if a a bracket or parent bracket that is needed to resolve bracket nesting is right on the edge when selecting the opening bracket, it can sometimes throw off the calculation.

I do find the matching of the div, when threshold is low a little concerning.  It seems that clicking the two different closing divs causes them to match the same opening div.  I may look to see if I can improve the algorithm to fix this corner case.  I'll have to analyze things to get a better idea why this happening in this low threshold environment.

**Comment by gavalierm** [comment]
Yes i understand this.

Maybe little trick is, that if you click on closing tag (</*>), so algorithm use search_trheshold in up direction, not down direction...

1. opening tag: search start = click position - 1000, search end = click position + 4000
2. closing tag (matchet by regex?): search start = click position - 4000, seach end = click position + 1000

maybe in strict search end = click position + "0" (or other really close position) becuase opennig tag will be never after closing tag. 

If you use same scenario (1.) in both (opening and closing tag) so is make sense, that did not work as expected

**Comment by facelessuser** [comment]
I'm okay with a tag not matching if the window shifts which is what you showed in the example with the `a` tag. What I am concerned about is multiple closing brackets matching the same opening bracket like what you showed with the `div`.  I am doing a test right now where I can put multiple closing `div` tags, and they all match the same opening.  There is a bug that is allowing multiple ends to match to the same beginning.   That needs to be fixed.

**Comment by gavalierm** [comment]
Ok, i got it, so good luck with future work! Thank you for help.

**Comment by facelessuser** [comment]
Thanks for the report.  Now that I've looked into things a bit closer, I've created a new issue to handle the weird div matching issue.  It seems this bug is not specific threshold per se. But an issue that manifests itself when at the tail end of the search.  When I have some time I will work through the issue to provide better tail end search logic.  From what I can tell, it is specific to matching only.

**Comment by facelessuser** [comment]
Hmm.  I assumed all of your issues were related to threshold, but I have a tentative fix that resolves the issues you showed even with low threshold.  I probably need to run it through more extensive testing before I release it though.  Anyways, I suspect this should be fixed in the next release as I seem to have a fix or am really close to having a fix.

**Comment by oshihirii** [comment]
just reporting, in regards to [this comment](https://github.com/facelessuser/BracketHighlighter/issues/407#issuecomment-289214196) about brackets matching in one way and not the other... 

i have html in a file, and if i click on the closing `</div>` tag at line `79` then it matches the opening `<div>` tag at line `12` .

if i do it the other way around and click on the opening `<div>`, then it displays a red `?` icon in the gutter.  

i tried hovering over the opening div and clicked the link `match brackets without highlighting` and it doesn't seem to do anything.  

i have changed search threshold in `Preferences` > `Package Settings` > `BracketHighlighter` > `Bracket Settings`:  
```
{
"search_threshold": 10000
}
```
i have my monitor rotated vertically so that i can *see* both opening and closing tags on the screen.

**Comment by facelessuser** [comment]
@oshihirii, your case may be different, but if you don't provide an actual minimal reproducible case, I can't tell you what is happening or make any suggestions.
