### ISSUE TITLE
HTML tag highlighting in EJS

### ISSUE THREAD

**Issue by dlcerva** [facelessuser/BracketHighlighter#410]
I'm leveraging the EJS plugin(https://packagecontrol.io/packages/EJS) for SublimeText 3 and highlight is working for the EJS syntax, however I'm not getting any highlighting for actual HTML tags inside the ejs document.

**Comment by facelessuser** [comment]
I'm assuming you figured out your question?  Anyways, next time please do follow the issue template.  Version numbers can be important as some times people are behind and that is the reason for their issues.
