### ISSUE TITLE
Error trying to parse settings

### ISSUE THREAD

**Issue by TacoJoe** [facelessuser/BracketHighlighter#414]
![error](https://cloud.githubusercontent.com/assets/21250802/26082934/63fe306e-3987-11e7-9cb2-95c60af0c2f4.PNG)

Just installed bracketHighlighter on ST3 and it was working fine while i was testing it out, once i restarted sublime it gave this error about 2 seconds into it.

It'll give me the same error right after I press "ok".
)

I only have the one setting inside the user settings and i dont understand what is going on.

![error 2](https://cloud.githubusercontent.com/assets/21250802/26082974/b8df84b6-3987-11e7-95fb-1d20691918f2.PNG)

**Comment by facelessuser** [comment]
1. Next time please follow the template.

2. If you are going to post settings always post them in text.

3.  Your settings are not valid JSON. Place them curly brackets around your `high_visibility_enabled_by_default` setting.
