### ISSUE TITLE
Lua brackets don't match at the beginning of the file

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/BracketHighlighter#415]
## Description

Lua keyword pairs that start at the beginning of the file aren't recognized. As a result, the closing bracket doesn't match anything.

Using "function" snippet, bundled by default, in a newly created view:

![img1](https://x0.at/MLp.png )

![img2](https://x0.at/qtG.png)

## Support Info

- ST ver.: 3131
- Platform: linux
- Arch: x64
- Plugin ver.: 2.23.3
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

Note: I actually have 2.24 installed, according to Package Control. Perhaps the version number wasn't updated in source? [No, it wasn't](https://github.com/facelessuser/BracketHighlighter/blob/cb2d65f99da501fa169be8ed6f263c39afb0c624/support.py#L8).

**Comment by facelessuser** [comment]
Which Lua syntactic highlighter? Default?

**Comment by FichteFoll** [comment]
Yes, default Lua.

**Comment by facelessuser** [comment]
I currently leave support for languages I don't use up to the community, but as this one looks pretty straight forward, I'll take care of it

**Comment by FichteFoll** [comment]
Yeah, I was the one who added proper bracket support to Lua in the first place. I could take a look, but I also believe my time is better spent elsewhere.
