### ISSUE TITLE
Quick Start Guide is just ¯\_(ツ)_/¯'

### ISSUE THREAD

**Issue by rusterholz** [facelessuser/BracketHighlighter#420]
## Quick Start Guide is just `¯\_(ツ)_/¯'`

After installing BracketHighlighter, the Package Control message helpfully suggested:

```
  Welcome to BracketHighlighter!  For a quick start guide, please go to  
  `Preferences->Package Settings->BracketHighlighter->Quick Start Guide`.
```

I thought to myself "sure, I could use some helpful pointers to get me started," and so I diligently selected the Quick Start Guide from the instructed menu. The following document appeared:

<img width="367" alt="screen shot 2017-07-02 at 1 02 23 pm" src="https://user-images.githubusercontent.com/1099426/27772804-c499270c-5f26-11e7-84e4-e811bfe6ce48.png">

Curiously, I was unable to select the text of the shrug, or interact with it in any way (thus the need for a screenshot).

Expected: Either (1) that the Quick Start Guide would exist and contain instructions on getting started with the plugin, or (2) that the Package Control message would not suggest that I go to nonexistent instructions.

Actual: It's hard to tell whether this is the actual content of the Quick Start Guide or whether this is supposed to be some kind of error message. 

If it is an error message, it's really unhelpful (to the point that it's unclear that it's an error), and it doesn't seem to be one of Sublime Text's built-in errors (the only mention of it I can find by googling "sublime text shrug" is [this Reddit thread](https://www.reddit.com/r/SublimeText/comments/6fmdzh/odd_question_why_does_the_shrugging_guy_emoji_pop/) -- and note that user also has BracketHighlighter installed).

If it is the actual content of the Quick Start Guide, it feels petulant, like a slap in the face to new users. I understand that maybe the Guide hasn't been written yet, but if that's the case, could the Package Control message be changed so as not to point new users in the direction of the empty guide?

## Support Info

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.24.2
- Install via PC: True
- mdpopups ver.: 2.0.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Go to Preferences -> Package Settings -> BracketHighlighter -> Quick Start Guide.
2. Observe the text `¯\_(ツ)_/¯'` in red.

**Comment by facelessuser** [comment]
Did you restart after installing? That is usually recommended to ensure all dependencies get loaded in proper.

**Comment by rusterholz** [comment]
A restart of Sublime Text does turn out to solve the issue. Thank you.

Is the shrug an error coming from BracketHighlighter? If so, could it be made more user-friendly?

Also, could the instruction to restart Sublime Text be added to the Package Control message? I've never had to do that for any other ST3 plugin I've ever installed, so it seems like a nonstandard requirement.

**Comment by facelessuser** [comment]
It's from the mdpopups dependency.  I should probably make the pop-up failure be more specific where it came from.

**Comment by rusterholz** [comment]
Thanks. It was a really frustrating error. If you can add some additional color to the failure it would go a long way. Not that you should have to make up for mdpopups' shortcomings, but I appreciate the help. I'll go ahead and close.

If you're in the US, have a good holiday weekend!

**Comment by facelessuser** [comment]
As I'm the author of the dependency as well, I'll try to make it more clear in the future.

> If you're in the US, have a good holiday weekend!

I am, and thanks!
