### ISSUE TITLE
Brackets doesn't match when code lines 60+

### ISSUE THREAD

**Issue by Jakitto** [facelessuser/BracketHighlighter#422]
Brackets match failed when a function has 60+ lines in Ruby.

Are you sure you want to rule Rubyists obey 60- lines function?

![qq20170711-185319](https://user-images.githubusercontent.com/18480287/28065225-4e2be5e6-666a-11e7-9dde-7fc967db7ea9.png)

![qq20170711-185332](https://user-images.githubusercontent.com/18480287/28065228-51de0070-666a-11e7-82a8-4b49a953a4d8.png)

There is no wrong code in main function that I can ensure and I can run this correctly. And my code is linter-check ok.

And I found there is another same problem in HTML

![qq20170711-185734](https://user-images.githubusercontent.com/18480287/28065363-d0cc4338-666a-11e7-9c28-24a1c03f50f1.png)

Brackets doesn't match when there is a little more code inner.

**Comment by r-stein** [comment]
Have you tried to increase the [`search_threshold`](https://github.com/facelessuser/BracketHighlighter/blob/st3-2.24.2/bh_core.sublime-settings#L105)?

**Comment by Jakitto** [comment]
@r-stein Thanks, that works!

**Comment by facelessuser** [comment]
You should also be able to hover over the bracket with the `?` and a popup will appear allowing you search without the threshold.

Usually you want to find a `search_threshold` that performs well, but not too big to cause issues when auto matching.  When you have a bracket beyond the threshold, you can mouse over the problem bracket and get the popup, and then click the link to do an "on-demand" search with no threshold.  This is of course if you have popups enabled.

**Comment by facelessuser** [comment]
@r-stein, Thanks!
