### ISSUE TITLE
Support Nested "Rainbow" Brackets

### ISSUE THREAD

**Issue by jonasflint** [facelessuser/BracketHighlighter#423]
## Nested Colored "Rainbow" Brackets (Feature Proposal)

BracketHilighter is a excellent plugin.   I would like to see nested brackets be configurable to be different colors based on it's nested placement. 

There is a plugin that claims to do this,  but it does not seem to work for sass or scss... here it is: 
https://github.com/whitequark/rainbowth

There is also a atom plugin that does this: 
https://atom.io/packages/swackets

I figured this would fit right into this awesome plugin.

**Comment by facelessuser** [comment]
Rainbowth takes your colorschemes and inserts a bunch of colors.  It is also pretty specific to your language syntax as it must add the colors by scope, and scope differs from syntax to syntax.  BracketHighlighter's mission is highlight scopes around the cursor making it clear where you are, not to colorize brackets.

Unfortunately, I have no desire to add such a feature. I'm going to pass on this request.

**Comment by jonasflint** [comment]
booooo.

**Comment by facelessuser** [comment]
Meh, it is what it is.

**Comment by facelessuser** [comment]
By the way, if you are upset with rainbowth, create an issue there or issue a pull request there to fix your issue. Or fork it and maintain your own version.
