### ISSUE TITLE
icon is hidden by gitgutter

### ISSUE THREAD

**Issue by AJgotBeard** [facelessuser/BracketHighlighter#428]
when using both package at same time, the brackethighlighter's icon is overrided by GitGutter icon.

**Comment by facelessuser** [comment]
Please follow the template on any issues in the future.  I usually close issues that don't follow the template as `invalid`.

Some reading on this issues:

https://github.com/jisaacks/GitGutter/issues/113
https://github.com/facelessuser/BracketHighlighter/issues/317
https://github.com/SublimeTextIssues/Core/issues/1664
https://github.com/SublimeTextIssues/Core/issues/319

At this point there is nothing I can do as this is an issue with how Sublime handles gutters. There is no actionable item for this.

**Comment by AJgotBeard** [comment]
Gotcha
Thanks for the info.

**Comment by r-stein** [comment]
GitGutter has a [setting](https://github.com/jisaacks/GitGutter/blob/1.7.3/GitGutter.sublime-settings#L112) to not add its icons if there are already regions present. However if I am correct you need to add all regions defined in the [bracket styles](https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L612):

```js
"bh_default",
"bh_default_open",
"bh_default_close",
// ...
"bh_curly",
"bh_curly_open",
"bh_curly_close",
// ...
```

**Comment by AJgotBeard** [comment]
@r-stein does it work?

**Comment by r-stein** [comment]
@AJgotBeard I assume it does work (it works for the linter) and I may add it to the shipped GitGutter settings file.

**Comment by AJgotBeard** [comment]
@r-stein So what do i need to do, I didn't clearly understand the solution.

**Comment by r-stein** [comment]
@AJgotBeard Open *Preferences > Package Settings > GitGutter > Settings* and add to the user settings:

```js
  "protected_regions": [
    "bh_default",
    "bh_default_open",
    "bh_default_close",
    "bh_unmatched",
    "bh_unmatched_open",
    "bh_unmatched_close",
    "bh_curly",
    "bh_curly_open",
    "bh_curly_close",
    "bh_round",
    "bh_round_open",
    "bh_round_close",
    "bh_square",
    "bh_square_open",
    "bh_square_close",
    "bh_angle",
    "bh_angle_open",
    "bh_angle_close",
    "bh_tag",
    "bh_tag_open",
    "bh_tag_close",
    "bh_c_define",
    "bh_c_define_open",
    "bh_c_define_close",
    "bh_single_quote",
    "bh_single_quote_open",
    "bh_single_quote_close",
    "bh_double_quote",
    "bh_double_quote_open",
    "bh_double_quote_close",
    "bh_regex",
    "bh_regex_open",
    "bh_regex_close",
    "sublimelinter-warning-gutter-marks",
    "sublimelinter-error-gutter-marks",
    "bookmarks"
  ],
```

However I am not sure whether we will add it to GitGutter, because if you move the cursor the brackethighlighter icon will be removed, but the GitGutter icon won't be added until it runs a diff again (save, modification, ...).
