### ISSUE TITLE
Support request: Trying to add a new tag mode (jsx) and failing.

### ISSUE THREAD

**Issue by teehemkay** [facelessuser/BracketHighlighter#429]
## Description

After reading the docs, I'm trying to create a new tag-mode to identify [jsx](https://facebook.github.io/react/docs/jsx-in-depth.html) tags.

I've created a new `bh_tags.sumble-settings` file (see below) and added the `jsx` key to all settings.
But the jsx tags are not recognized as tags by BH. The settings are essentially the same as those from the `html` tag mode with small changes to the `tag-mode`->`syntax`, the `tag_scope_exclude`, the `self_closing_tag_patterns` and the `attributes` settings.

It seems to me that the settings are complete.

But BH only highlight the angle brackets `<` and `>`, not the tags themselves.

![screen shot 2017-08-17 at 12 30 16](https://user-images.githubusercontent.com/4826/29407810-058e2bc0-8346-11e7-8694-e51a0c1fa49f.png)

![screen shot 2017-08-17 at 12 30 41](https://user-images.githubusercontent.com/4826/29407813-0a9ebc6a-8346-11e7-8f9a-2a5f08f4b6ba.png)

 
What am I missing?

Any help would be very much appreciated.

Thanks!

```json
{
  "tag_mode": [
      {
        "mode": "jsx",
        "syntax": ["JavaScript (Babel)"]
      }
    ],
    "tag_style": {
        "jsx": "tag"
    },

    "tag_scope_exclude": {
        "jsx": ["comment"]
    },

    "optional_tag_patterns": {
        "jsx": "colgroup|dd|dt|li|options|p|td|tfoot|th|thead|tr"
    },

    "void_tag_patterns": {
        "jsx": "area|base|basefont|br|col|embed|frame|hr|img|input|isindex|keygen|link|meta|param|source|track|wbr"
    },

    "self_closing_tag_patterns": {
        "jsx": "[A-Z]\\w+"
    },

    "tag_name":
    {
        "jsx": "[\\w:\\.\\-]+"
    },

    "attributes":
    {
        "jsx": "{\\.{3}[^}]+}|[\\w\\-:]+(?:\\s*=\\s*(?:|{[^}]+}|\"[^\"]*\"|'[^']*'|[^\\s\"'`=<>]+))?"
    },

    "start_tag": {
        "jsx": "<(%(tag_name)s)(?:\\s+%(attributes)s)*\\s*(/?)>"
    },

      "end_tag": {
        "jsx": "</([\\w\\:\\.\\-]+)[^>]*>"
    }
}
```
> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.25.0
- Install via PC: True
- mdpopups ver.: 2.1.1
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
You are going to have a difficult time because JSX allows you to break HTML with non-traditional HTML.  To be honest it turns HTML more into a template language.  BH is looking for valid HTML.  What you have posted above is valid JSX, not valid HTML.  You'd have to provide something that is supportive of a JSX specific HTML.

You can play with creating a new HTML profile with regex for an HTML that.  It seems that is the path that you are on.

I'll say this.  I see this in your regex `{[^}]+}`. I am assuming you are trying to capture curly brackets.  But you need to escape curly brackets in regex: `\{` etc.  Further, you need to escape backslashes in JSON strings: `\\{` etc.

Second, order of regex rules is important.  BH will already try and target `{}` pairs.  You may need to  inject a JSX specific rule that is separate from the default HTML rule and have it before the `{}` rule so that it doesn't gobble up your curly brackets before they can be evaluated in your custom HTML rule.

**Comment by teehemkay** [comment]
First thank you very much for the quick feedback!

> BH is looking for valid HTML. What you have posted above is valid JSX, not valid HTML. You'd have to provide something that is supportive of a JSX specific HTML.

Unless I'm mistaken, I've tried to capture in my regexes, the places where I think JSX differs from HTML (the self-closing tag name and the attributes)

> You can play with creating a new HTML profile with regex for an HTML that. It seems that is the path that you are on.

Just to clarify, when you say "new HTML profile" do you mean creating a new tag-mode, like I'm trying to do or is that something else entirely?

> I'll say this. I see this in your regex {[^}]+}. I am assuming you are trying to capture curly brackets. But you need to escape curly brackets in regex: \{ etc. Further, you need to escape backslashes in JSON strings: \\{ etc.

Yes. In JSX attribute values can be specified within curly braces e.g. `{1 + 1}` or `{...some_data}`. Thank you for the heads up re: escaping curly brackets. I'll escape them. I was wondering though, is BH using the Python `re` module? I'm asking because I've tested regex with unescaped `{` using the python command line and it does seem to work 😲 

> Second, order of regex rules is important. BH will already try and target {} pairs. You may need to inject a JSX specific rule that is separate from the default HTML rule and have it before the {} rule so that it doesn't gobble up your curly brackets before they can be evaluated in your custom HTML rule.

Are referring to [Bracket Rule Management](http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management)? 

I've just noticed that on my machine, none of the tags (`html`, `cfml`, etc) appear as a rules But BH still highlights tags without problem in an HTML file...

This is what I get when I run the `BracketHighlighter: (Debug) Filter Rules by Key` using the `position` key. 

```json
        {"name": "curly", "position": 0},
        {"name": "round", "position": 1},
        {"name": "square", "position": 2},
        {"name": "php_angle", "position": 3},
        {"name": "angle", "position": 4},
        {"name": "cssedit_groups", "position": 5},
        {"name": "ruby_embedded_html", "position": 6},
        {"name": "ruby", "position": 7},
        {"name": "c_compile_switch", "position": 8},
        {"name": "php_keywords", "position": 9},
        {"name": "erlang", "position": 10},
        {"name": "bash", "position": 11},
        {"name": "fish", "position": 12},
        {"name": "lua", "position": 13},
        {"name": "latexenv", "position": 14},
        {"name": "pascal", "position": 15},
        {"name": "elixir", "position": 16},
        {"name": "cmake", "position": 17},
        {"name": "s840d_gcode", "position": 18},
        {"name": "s840d_hmi", "position": 19}
```

As opposed to

```json
[
        {"name": "curly", "position": 0},
        {"name": "round", "position": 1},
        {"name": "square", "position": 2},
        {"name": "html", "position": 3},
        {"name": "cfml", "position": 4},
        {"name": "php_angle", "position": 5},
        {"name": "angle", "position": 6},
        {"name": "cssedit_groups", "position": 7},
        {"name": "ruby_embedded_html", "position": 8},
        {"name": "ruby", "position": 9},
        {"name": "c_compile_switch", "position": 10},
        {"name": "php_keywords", "position": 11},
        {"name": "erlang", "position": 12},
        {"name": "bash", "position": 13},
        {"name": "fish", "position": 14},
        {"name": "mylang", "position": 15}
    ]
```
from the documentation

**Comment by facelessuser** [comment]
> Python re module? I'm asking because I've tested regex with unescaped { using the python command line and it does seem to work 

Yes, we use `re`.  Maybe what you are doing works, maybe it doesn't.  I don't know.  I always explicitly escape those, but I see it comes right after `|`, so because it is not followed after part of a pattern, maybe `re` doesn't require those to be escaped.  So, I won't comment on that further.  If you are confident, then I guess that is fine.

> Unless I'm mistaken, I've tried to capture in my regexes, the places where I think JSX differs from HTML (the self-closing tag name and the attributes)

> Just to clarify, when you say "new HTML profile" do you mean creating a new tag-mode, like I'm trying to do or is that something else entirely?

I was speaking generally, and then I mentioned that seemed to be the direction in which you were going. So yes, you seem to be creating a new profile.

> I've just noticed that on my machine, none of the tags (html, cfml, etc) appear as a rules But BH still highlights tags without problem in an HTML file...

I believe the `angle` rule is what you are looking for.  It includes the tag `bh_plugin`.  Maybe if you move it before curly you will have some success?

**Comment by teehemkay** [comment]
OK, quick updated. I've now spend spent an inordinate amount of time on this but to no avail.
I think I'm going to give up on this one.

Thanks again for you help and please feel free to close the issue if you wish.

**Comment by facelessuser** [comment]
If you have a branch somewhere, maybe you can reference it here and someone can look at it in the future.  I am personally less likely to look at things unless I have an actual branch.

I understand you personally may be done with work on it, but I know there are a number of people who'd like to see this feature.  Maybe your starting point will be enough to get someone to finish it.  I guess if you were doing it all in local settings files, that isn't as easy to link as a fork.

In general, I'll say this about JSX, it is often not guaranteed that tags will be ordered and match like they do in HTML as you can store away parts in to variables in any order.  It may have always suffered issues to some extent.  It's why I have never tried to match tags in JS strings.
