### ISSUE TITLE
[REXX] No highlight with user settings

### ISSUE THREAD

**Issue by Xerocry** [facelessuser/BracketHighlighter#430]
## Description
Trying to add user setting for REXX language for do-end wrap highlighting.
But it's not working. Example was taken from Ruby.

## Support Info
- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.25.0
- Install via PC: True
- mdpopups ver.: 2.1.1
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

REXX version: v1.0.3

## Steps to Reproduce Issue

1. Install BH
2. Install REXX
3. Add to user config:
```
{       "wrapping": [
        {
            "enabled": true, 
            "language_list": ["REXX"], 
            "language_filter": "whitelist", 
            "entries": [
                {"name": "REXX: do", "brackets": ["do", "end${BH_SEL}"], "insert_style": ["indent_block"]}
            ]
        }
    ]
}
```

**Comment by facelessuser** [comment]
Not sure.  You'd have to point me at the package you use for REXX as I know nothing about it.  Not sure if case is important, but remember that the language_list should be the file name minus the extension, not what appears in the bottom right hand corner of Sublime when the syntax is loaded.

**Comment by Xerocry** [comment]
https://packagecontrol.io/packages/REXX
I've tried to point different cases and names, but still no result..

**Comment by facelessuser** [comment]
If you want me to personally verify this, I need you to update the opening post with general version info so I can confirm what version of BH and dependencies you are using. Also so I can verify what system you are on etc.

If you forgot what the issue template was asking for, you can find the template here: https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by facelessuser** [comment]
Thanks for the update.  I will take a look when I get a chance.

**Comment by facelessuser** [comment]
I had no problems with this.  What I did was copy `bh_wrapping.sublime-settings` to my User folder and added your rule to the existing settings (you can't jus drop what you have on the opening post into User, you copy the original and add yours to the existing settings).

Created a file set to REXX and add the text `test`. Selected `test` and ran the option `BracketHighlighter: Wrap Selections with Brackets`.  Selected `REXX: do` and it wrapped test.

I see no issues.

**Comment by Xerocry** [comment]
Yeah, it wrap something in do-end, but I want to **highlight** do-end construct, like in Ruby!

**Comment by facelessuser** [comment]
Okay, so you just want to highlight brackets?  That really wasn't clear from the issue.  You will have to look at `bh_core.sublime-settings` and add REXX rules.  Also read the the related docs http://facelessuser.github.io/BracketHighlighter/customize/#configuring-brackets.

I make clear in the documentations that I don't have time to learn everyone's favorite languages to write rules for them.  But I can give pointers if you get stuck.

**Comment by facelessuser** [comment]
I'm going to go ahead and close this.  If you start going down the road of creating bracket rules and get stuck, feel free to ask questions.  Just make sure you provide as much info as possible.
