### ISSUE TITLE
Doesn't work in HTML (Liquid). 

### ISSUE THREAD

**Issue by radmedov** [facelessuser/BracketHighlighter#434]
## Description

Doesn't work in HTML (Liquid). 
Give me advice how to set it up, please.
Thank you.

**Comment by lang-ji** [comment]
me too..

**Comment by facelessuser** [comment]
1. Issues need to follow the template.

2. The documentation explains how to add new rules etc.

    -  http://facelessuser.github.io/BracketHighlighter/customize/#configuring-brackets
    - http://facelessuser.github.io/BracketHighlighter/customize/#tag-plugin-settings

    Take a look at both these settings as this is where languages are configured generally:`bh_core.sublime-settings`, and this is where additional tag specific settings are configured:`bh_tag.sublime-settings`.

For additional help, please update the opening post to follow the template guidelines: https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md. Take a look at the documentation, and existing examples in the settings files.

If after all that, you are still confused and have a specific question with something in particular covered in the the examples and documentation, you can ask those questions here, but provide information of what you are currently trying, and please be specific with your questions as my answer for for vague, broad questions is generally to "read the manual".

**Comment by facelessuser** [comment]
As there is no actionable item here, I am closing this issue.  In general, support for new languages is provided by the community, not me directly (unless I specifically have an interest in said language).

Liquid may not be easy to add as I imagine it is more a template language that breaks HTML format.  There are many, many different template languages, and they cannot all be supported with one rule.  In general, different HTML profiles would need to be set up.  Another issue is it seems most people want their specific template language also recognized as basic HTML syntax.  Again this is related to the fact that one profile cannot be provided that uses the HTML syntax but also handles everyone's favorite template language.
