### ISSUE TITLE
Swap Brackets replaces quotes

### ISSUE THREAD

**Issue by stdedos** [facelessuser/BracketHighlighter#436]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description

When highlighting quotes, `Swap Brackets` replaces those quotes.

Either make `Swap X` context-aware or disallow brackets to match quote swaps and vice-versa.
Further encapsulating said quotes in brackets (or vice-versa) could be a _feature_

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info
- ST ver.: 3143
- Platform: linux
- Arch: x64
- Plugin ver.: 2.25.0
- Install via PC: True
- mdpopups ver.: 2.1.1
- backrefs ver.: 1.1.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

...

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

## Steps to Reproduce Issue

1. `cd ${1} || {echoErr "Could not cd to '${1}'. Please try again" ; return -1 ; }`
`_____________________________________________________________^ (on the right)`
2. `^+p::Swap Brackets::Curly`
3.`cd ${1} || {echoErr {Could not cd to '${1}'. Please try again} ; return -1 ; }`

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
I don't seem to understand what the complaint is.  Care to elaborate?

You seem to not like that Swap Brackets works as expected?  The current selected brackets get swapped with the selected brackets, but you want it not to?

If you don't like quote highlighting, you can disabling them in your user settings: http://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management.

**Comment by stdedos** [comment]
It is not swapping the brackets, it swaps the quotes _with_ brackets.

Maybe seeing them on top of each other helps:
```
                    V                                        V
cd ${1} || {echoErr "Could not cd to '${1}'. Please try again" ; return -1 ; }
cd ${1} || {echoErr {Could not cd to '${1}'. Please try again} ; return -1 ; }
                    ^                                        ^
```

**Comment by facelessuser** [comment]
I see it, but I am assuming the quotes were highlighted, why is this unexpected? We're you expecting it to wrap instead of replace? If so, you could use the wrap command that wraps a selection.

**Comment by facelessuser** [comment]
Okay, I think we are getting into semantics here, yes quotes are not "brackets".  Bracket Highlighter works on brackets and arbitrary start end markers on blocks. You can configure BH to not operate on anything you don't like, so what I assume you want is achievable in the user settings I pointed out. Or am I still misunderstanding?

**Comment by stdedos** [comment]
When I am `Swap Brackets`-ing, _technically_ I expect to _swap brackets_. I expect the mechanism that detects the replace positions to verify that it's swapping _brackets_ instead of whatever other detection might be in place i.e. IMHO the innermost **bracket** group.

Also _technically_, I was just touching the quotes, so, according to my previous understanding of the definition it shouldn't detect it anyway. But even if I am wrong on the match locality, as you also noted `quotes != brackets`

**Comment by facelessuser** [comment]
As stated previously, BH handles brackets and bracket like objects.  If it helps you can replace the term "bracket" with "start/end block markers".  I am unconcerned with whether or not quotes are *technically* brackets.

BH was designed to handle brackets, tags, and any other custom start end marker generically.  I don't have bracket specific logic in the main code to make maintainability easier.  This is a free plugin, so I keep the features quite generic.

Also BH handles one match (per cursor) at a time, it doesn't recursively find multiple nested brackets around the current currsor(s), so it cannot just select a different bracket (outer or inner most).

If it is troubling that "quotes" are treated as "brackets", you can just disable them and then you won't have to worry about BH applying bracket like functionality to them.  You can even modify your swap settings in `bh_swapping.sublime-settings` (which is covered in the documentation) if you feel some behavior there needs to be modified.
