### ISSUE TITLE
Can`t make it highlight the background color

### ISSUE THREAD

**Issue by alannaidon** [facelessuser/BracketHighlighter#437]
> SublimeText: Build 3126  
> Color Schema: Materialize Theme  
> 

---

I just installed the plugin on sublime and at first I had no highlight AT ALL.  
After research and some tweek, I could make it work very nice but I`d love it to highlight only with background color of the code block.  

Currenctly, all I could do is this:  
![brackets](https://user-images.githubusercontent.com/13774879/31192876-d39b052c-a918-11e7-92ed-f3acb6049b1f.png)
 
### bh_core settings:  
````
{
  "high_visibility_enabled_by_default": true,
  "high_visibility_style": "outline",

  "scope_brackets": [
        // Quotes
      {
            "name": "py_single_quote",
            "open": "(?:u|b|f)?r?((?:'')?')",
            "close": "((?:'')?')",
            "style": "highlight",
            "scopes": ["string", "meta.string"],
            "language_filter": "whitelist",
            "language_list": [
                "Python",
                "PythonImproved",
                "MagicPython"
            ],
            "sub_bracket_search": "true",
            "plugin_library": "bh_modules.pyquotes",
            "enabled": true
        },
         {
            "name": "py_double_quote",
            "open": "(?:u|b|f)?r?((?:\"\")?\")",
            "close": "((?:\"\")?\")",
            "style": "highlight",
            "scopes": ["string", "meta.string"],
            "language_filter": "whitelist",
            "language_list": [
                "Python",
                "PythonImproved",
                "MagicPython"
            ],
            "sub_bracket_search": "true",
            "plugin_library": "bh_modules.pyquotes",
            "enabled": true
        },
        {
            "name": "single_quote",
            "open": "(')",
            "close": "(')",
            "style": "highlight",
            "scopes": ["string", "string.quoted"],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "double_quote",
            "open": "(\")",
            "close": "(\")",
            "style": "highlight",
            "scopes": ["string", "string.quoted"],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "backtick_quote",
            "open": "(`)",
            "close": "(`)",
            "style": "highlight",
            "scopes": ["string.interpolated.ruby", "string.interpolated.backtick.shell"],
            "language_filter": "whitelist",
            "language_list": ["Ruby", "Shell-Unix-Generic"],
            "sub_bracket_search": "true",
            "enabled": true
        },
  ]
}


````

Is there a way to highlight only the background color of this same portion of code when I click on the brackets ? Thanks !!

**Comment by facelessuser** [comment]
1. > I just installed the plugin on sublime and at first I had no highlight AT ALL.

    You have to restart sublime after installing the plugin.  No other action is needed.  If you "got it working", it was most likely because you finally restarted, not because of settings tweaks.

2. Please follow the the template and provide things like the version info of the plugin and its dependencies: https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md

3. > Is there a way to highlight only the background color of this same portion of code when I click on the brackets ? Thanks !!

    I'm not sure what you are asking for.  I see you've enabled high visibility mode.  I see that you are overriding all the scope brackets with your own (why?).  Maybe this is related to point (1.), but if so, none of that was necessary to get BH working.

So I'd remove your scope bracket overrides (remove the entire key).  Provide me with version info stuff per the template (I don't troubleshoot issues without it).  And please clarify what your actually issue is as I am currently uncertain what you are asking.

**Comment by alannaidon** [comment]
> You have to restart sublime after installing the plugin. No other action is needed. If you "got it working", it was most likely because you finally restarted, not because of settings tweaks.  

I did. Many times actually, nothing changed.  

> I'm not sure what you are asking for. I see you've enabled high visibility mode. I see that you are overriding all the scope brackets with your own (why?)  

The reason why I started to tweek and enabled high visibility is exactly because nothing had changed.  
May this be cause by my theme ?    

I installed > Restarted > Nothing changed > started to tweek  

This is what happen with a Fresh Installation + Restart sublime:  
![brackets](https://user-images.githubusercontent.com/13774879/31206378-dc2952f4-a94d-11e7-9e6a-2814a4a77791.JPG)  

You can see the brackets on the line number, but there is no highlight on the code.

**Comment by facelessuser** [comment]
Post version info like I asked please.

Brackets underlined (highlighted) so it is working.

I'm making this invalid until the info I requested is posted.

**Comment by alannaidon** [comment]
### Description  
>... what is the issue / request ?   

When Install the plugin and restart sublime, the plugin doesn't properly. It only shows the brackets on the line number. So I decided to try to tweek the package configuration, without success.  

### Support Info

I'm currently using:  

- Materialize Theme  
- Sublime Build 3126    
- Plugin ver: 2.25.0  
- mdpopups ver: 2.1.1  
- backrefs ver: 2.1  
- markdown ver: 2.6.9  
- pygments ver: 2.1a0  
- jinja2 ver: 2.8  


### Steps to Reproduce Issue  

1- Ctrl + Shift + p > Install Package > BracketHighlighter > Install;  
2 - Restart Sublime Text;  
3 - Without success I changed the config file as shown in the first post.

**Comment by facelessuser** [comment]
> When Install the plugin and restart sublime, the plugin doesn't work properly. It only shows the brackets on the line number.

This is not true.  It is underlining the brackets as well.

> What I want is to highlight all block of code inside selected brackets, like the "line_highlight" but with the brackets.

High visibility mode is always going to be slightly flawed for everyday use as it uses Sublime regions in the API (the only way to accomplish this). You could use the `solid` option (and even modify your color scheme to have a less severe color and have BH use that less severe color for the BH highlighting), and that will highlight the background, but you will loose syntax highlighting and have plain looking text.

This is a Sublime limitation.  I understand what you are wanting, but unless Sublime updates the regions API with an option to highlight backgrounds with a color **and** keep syntax highlighting, it is currently not a good direction as it is will not look good for everyday coding.  You can set solid for high visibility and toggle it on and off when you want to see it which would be more practical.

I more look at high visibility for either people will lower vision, or people that just need to temporarily make it VERY obvious the extend of the bracket content.

A better option is to not use high visibility mode and instead change the highlight style of the brackets to something like solid. Now the brackets will be more visible without obscuring all the syntax highlighting. See documentation: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style.

**Comment by facelessuser** [comment]
I'm either assuming I've answered your question, or there is no plan to ask more questions?

I will mark this stale and close in a couple of days as there is currently no actionable item.
