### ISSUE TITLE
In sublime build3147, underlined display interrupt? Do not know whether to decorate?

### ISSUE THREAD

**Issue by ouweiya** [facelessuser/BracketHighlighter#438]
### This problem is not fixed, through the screen zoom, sometimes also cover up.

![screenclip](https://user-images.githubusercontent.com/28357731/31348033-e6a1ea1e-ad50-11e7-9d6b-3fef54778015.png)

**Comment by facelessuser** [comment]
The template was not followed: https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md. For in depth support, the template is required.

So I'll just say this, I can't control how Sublime renders.  But the thick underline is special in the way it is done (but I can't change how it gets rendered).  If you want a solid like, try `thin_undlerline` (see documentation: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style).
