### ISSUE TITLE
Sublime Updated, content_highlight_bar isn't white anymore.

### ISSUE THREAD

**Issue by Fossil01** [facelessuser/BracketHighlighter#441]
This is driving me nuts. Sublime updated and it reset my theme and color scheme. I have fixed all that but now the Content Highlight Bar is almost the same color as the background of that bar, so hardly visible.

It used to be white, I can't find an option for make the bar white again. Any ideas?

**Comment by facelessuser** [comment]
I need you to follow the template: https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md.

I have no idea what version of anything you are using.

**Comment by Fossil01** [comment]
- ST ver.: 3152
- Platform: osx
- Arch: x64
- Plugin ver.: 2.25.1
- Install via PC: True
- mdpopups ver.: 3.0.0
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
I've actually mentioned this in the forum: https://forum.sublimetext.com/t/dev-build-3152/32710/3?u=facelessuser, but we probably need to create an official Sublime bug report.

**Comment by facelessuser** [comment]
This must be fixed upstream, not in BH.

**Comment by Fossil01** [comment]
Roger

**Comment by facelessuser** [comment]
I've created the official Sublime issue report.  Hopefully the next build will have a fix.  Usually, as long as Jon sees it, issues related to things he's just added get fixed pretty quick.
