### ISSUE TITLE
Not recognizing table tag

### ISSUE THREAD

**Issue by ninja542** [facelessuser/BracketHighlighter#442]
## Description

The plugin does not recognize table tags, which messes up the bracket highlighting for the rest of the document. I tested this with my own file At first, the tags that were surrounding the table were not being paired correctly. Then I commented out all the table tags (including td, th, tr, etc.) and then brackethighlighter started working with all my tags. 

## Support Info

- ST ver.: 3143
- Platform: windows
- Arch: x64
- Plugin ver.: 2.25.1
- Install via PC: True
- mdpopups ver.: 3.0.0
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

```html
<html>
	<head>
		<link rel="stylesheet" href="editabletable.css">
	</head>
	<body>
	<div id="body">
		<div id="app">
			<table>
				<tr>
					<th>x</th>
					<th>y</th>
				</tr>
				<tr v-for="item in coordinates">
					<td v-on:click="edit=true"><div v-show="edit==false">{{item.x}}</div><input v-show="edit" v-bind:value="item.x" v-model.number="item.x" v-on:keyup.esc="update" type="text"></td>
					<td v-on:click="edit=true;"><div v-show="edit==false">{{item.y}}</div><input v-show="edit"  v-bind:value="item.y" v-model.number="item.y" v-on:keyup.esc="update" type="text"></td>
					<td class="delete" v-on:click="deleteRow(item)">
						<svg fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
					    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/>
					    <path d="M0 0h24v24H0z" fill="none"/>
						</svg>
					</td>
				</tr>
			</table>
			<button v-show="edit" v-on:click="addRow"> Add row </button>
			<button v-show="edit==false" v-on:click="edit = true">Edit</button>
			<button id="done" v-show="edit" v-on:click="update">Done</button>
		</div>
	</div>
	<script src="../d3.min.js"></script>
	<script src="https://unpkg.com/vue"></script>
	<script src="editabletable.js"></script>
	</body>
</html>
```
try bracket highlighter. 

Then comment out everything between <table> </table> and now bracket highlighter works

**Comment by facelessuser** [comment]
This doesn't look like pure HTML, what is this?  What syntax do you use for this.  Is this vue?  If so, see: https://github.com/facelessuser/BracketHighlighter/issues/370.

**Comment by ninja542** [comment]
It's html with vue modifiers, so I'm pretty sure it's HTML

**Comment by ninja542** [comment]
I fixed it, apparently <path something something /> doesn't highlight correctly, and I changed it into <path></path> and now everything works

**Comment by facelessuser** [comment]
> It's html with vue modifiers

You do realize that proves my point?  If it isn't in the HTML spec, then it isn't HTML.

If you can point out in the spec that I'm not handling attribute name characters correctly, then I will happily update the rules accordingly.  I'm not always checking for updates in the spec, so I rely on others to help me understand if we aren't properly handling things.  So if what is being done isn't up to spec, please point me at that so we can get it fixed.

**Comment by facelessuser** [comment]
Hmm. That is fair.  I don't have any svg specific logic in there to check that. I think in XHTML mode that may work...but maybe not HTML.

So it appears it the issue wasn't related to attribute names, so that is good, but I've found some discussion that `[a-zA-Z_:][-a-zA-Z0-9_:.]` is acceptable, so I may update attribute names to allow `_` and `.` as well.

**Comment by facelessuser** [comment]
You can edit `bh_tag.sublime-settings` and adjust this behavior for the `path` tag.

```html
    // Optional closing HTML tags. You can use 'null' if it does not require a pattern.
    "optional_tag_patterns": {
        "xml": null,
        "xhtml": null,
        "html": "colgroup|dd|dt|li|options|p|td|tfoot|th|thead|tr",
        "cfml": "cf.+|colgroup|dd|dt|li|options|p|td|tfoot|th|thead|tr"
    },

    // Tags that never have a closing.  You can use 'null' if it does not require a pattern.
    "void_tag_patterns": {
        "xml": null,
        "xhtml": null,
        "html": "area|base|basefont|br|col|embed|frame|hr|img|input|isindex|keygen|link|meta|param|source|track|wbr",
        "cfml": "area|base|basefont|br|col|embed|frame|hr|img|input|isindex|keygen|link|meta|param|source|track|wbr"
    },
```

**Comment by facelessuser** [comment]
If you have a list of svg tags like path that may not ever have a closing, we can add all of them if required.

**Comment by ninja542** [comment]
I think all the svg tags could either be self closing or explicitly closed with another tag. (MathML too apparently, but idk if that's relevant)

So I guess there are two ways, you can make the highlighter skip the closing tag or you can make the highlighter highlight the ending `/>`

I would personally like to have the end highlighted but it might not make sense to other people, maybe make it a preference flag?

I think that you should add the XHTML highlighting stuff into HTML for the SVG and MathML although that might be a bit of an edge case. But it'll be more general and there's a lot of tags in SVG, and it seems like every svg tag can self close, so you don't have to code every single svg tag into your plugin.

**Comment by facelessuser** [comment]
> I think that you should add the XHTML highlighting stuff into HTML for the SVG and MathML although that might be a bit of an edge case. But it'll be more general and there's a lot of tags in SVG, and it seems like every svg tag can self close, so you don't have to code every single svg tag into your plugin.

Unfortunately, I do need to know all the tags.  BH scans a window of text at a time, so it might not know it is inside an `<svg>` tag.  It needs to be able to identify tags that are self closing.  This can be done in the `self_closing_tag_patterns` option in the settings, but I will need to know the tag names.

I found a list here: https://github.com/jonschlinkert/self-closing-tags/blob/master/index.js.  Not sure how accurate or how these were obtained.  I know there are many more SVG tags, but it is probably unheard of some being self closed.  Anyways, this may be a good start.

**Comment by facelessuser** [comment]
SVG self closing tags added: https://github.com/facelessuser/BracketHighlighter/commit/cec05437e8601fa2fccaf91eb9dd1fe4604f9751.

If you come up with more, feel free to add them via a pull request.  MathMl tags would also be appreciated.

As far as this issue is concerned, I think we have SVG working.

**Comment by ninja542** [comment]
thank you!
