### ISSUE TITLE
Brackets don't highlight inline; only gutter indicators showing

### ISSUE THREAD

**Issue by benfrain** [facelessuser/BracketHighlighter#443]
## Description

Brackets don't highlight inline; only gutter indicators are showing. Tested in HTML/CSS/TS.

To be clear, here is a grab to illustrate:

<img width="852" alt="screen shot 2017-10-24 at 13 20 02" src="https://user-images.githubusercontent.com/1318466/31946521-ee6bd348-b8c9-11e7-94f5-d8cba56eadb5.png">

I used to see brackets themselves highlighted alongside the gutter indicators.

Here is the only relevant part of the console I could see:

```
Package Control: All dependencies have been satisfied
using gpu buffer for window
Unable to open /Users/benfrain/Library/Application Support/Sublime Text 3/Packages/BracketHighlighter/bh_core.sublime-settings
Unable to open /Users/benfrain/Library/Application Support/Sublime Text 3/Packages/User/bh_core.sublime-settings
```

## Support Info

```
- ST ver.: 3152
- Platform: osx
- Arch: x64
- Plugin ver.: 2.25.1
- Install via PC: True
- mdpopups ver.: 3.0.2
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

## Steps to Reproduce Issue

1. Position caret next to a bracket in HTML/CSS/TS file 
2. Observe that gutter indicators show, but not bracket indicators

**Comment by facelessuser** [comment]
The underline is still there, it is just really, really faint as it is almost the same color as the background.  But this is not a BH issue (not directly). This is actually an upstream Sublime issue: https://github.com/SublimeTextIssues/Core/issues/2020.

With that said, I will cut a release this morning that uses the `thin_underline` style as default to mitigate this issue temporarily.  Once Sublime fixes the issue, I will use the thicker underline style again by default.

**Comment by facelessuser** [comment]
New release cut with `thin_underline` as the default style.  It will now be visible, but a little less due to the line being so thin. I'll await Sublime Text to fix the issue 2020 before returning the original style.

**Comment by benfrain** [comment]
@facelessuser brilliant, thanks for the swift resolution. Back up and running perfectly now 👍
