### ISSUE TITLE
REQUEST:  simpler color change capability

### ISSUE THREAD

**Issue by iansebryk** [facelessuser/BracketHighlighter#445]
FEATURE REQUEST:

please provide a simpler method of overriding your current colour schemes... because... DAMN. 😱 
i appreciate what it currently does, incorporating scope colouring, but drilling that deep just to change the default WHITE to another colour, is torture.  for those that like it, keep it, but perhaps give the ability to simple set the color in the user prefs to a simple hex override if it is there.  for example:

```
"bracket_styles": {
    "default": {
      "style": "solid",
      "color": "#FF2600"  <-- this would *override* brackethighlighter.default, for example
}
```

this way general-use methodology is retained, usablity skyrockets, and the uber-geek factor for those who like/want/need it remains.  right now, it's a great tool, but 'customizable' is really more a faint nod at this point; especially if you aren't aware of scope definitions or don't want to spend time digging for it.  don't get me wrong, i love this tool, i just want to love it more by not having to think about how to make it work for me, selfish bastard that i am.  😆 

thanks for all your hard work. 🥇 and forgive me if what i'm asking is just flat out not possible within the framework.

**Comment by facelessuser** [comment]
1. In the future, all issues are required to follow the template. By making everyone follow the template, it ensure the ones who really need to give me more info get it to me and I don't have to argue with people whether they feel they've provided me with enough info or not.

2. > please provide a simpler method of overriding your current colour schemes... because... DAMN. 😱

    I realize that this methodology seems convoluted, but I didn't come up with this way because I like convoluted things; it's just what the Sublime API requires.  If I could get away with `#FF2600`, I would gladly embrace that.

**Comment by facelessuser** [comment]
As there is no actionable item here, I am closing this issue.

**Comment by r-stein** [comment]
I think with the newest dev release from yesterday (Build 3153) you can define colors by names, i.e. use the `region.redish` to add the red color. Hence you can set the scope to `"color": "region.redish"` / "color": "region.yellowish" to set the corresponding color.

**Comment by facelessuser** [comment]
@r-stein are `region.redish` auto generated?

**Comment by r-stein** [comment]
I guess so, because it is available for every of my colorschemes.

**Comment by facelessuser** [comment]
Nice! Good to know.  Unfortunately migrating to this is a bit tricky as now there is a long standing convention for BH that people have adopted.  I'd love to just assign things like `region.redish` by default, but I know there are color schemes configured to specifically target the old `brackethighlighter.curly` etc.

Also, it would need to be conditional to 3152+, but at least people can customize it themselves using those scopes.  I should maybe put a mention in the docs about it.

**Comment by r-stein** [comment]
It think if you use something like `view.add_regions(..., "region.redish brackethighlighter.default", ...)` it will only use red if there is no color for `brackethighlighter.default`, so that should not be so problematic.

**Comment by facelessuser** [comment]
:thinking: That might work.  I'll have to play with that.

**Comment by facelessuser** [comment]
So, I'm going to utilize the new regions for recent Sublime builds to provide colors out of the box.  With new color scheme support, it is super easy to change colors, or add existing ones with a simple override file in `User`.  Obviously this doesn't translate back to the stable branch yet, but that is fine.  If people are using color schemes with the old example, they should still work as well.

**Comment by facelessuser** [comment]
While all of my examples show `brackethighlighter.some_scope`, I've apparently never actually defaulted the settings to these except for `brackethighlighter.default`.  Currently, I also require that you override the entire `bracket_style` option to change anything, so as long as I default `brackethighlighter.default` to `region.yellowish brackethighlighter.default` (or whatever), I should be fine.  The rest I can directly set to `region.redish` etc.

Moving forward, I will add a `user_bracket_styles` which will allow you to specify only what you wish to override so you no longer have to copy everything.  Anyone who overrides the old way will be unaffected even if I change the defaults.  So this will actually work quite well moving forward.

**Comment by facelessuser** [comment]
This is addressed (as much as I can for now) on the main branch.
