### ISSUE TITLE
Package Discrepancy Between Machines

### ISSUE THREAD

**Issue by corneliusio** [facelessuser/BracketHighlighter#450]
## Description

I'm having an issue with BracketHighlighter seemingly being on two different releases on two different machines, despite 2.26.0 being installed on both of them.

I currently use to machines primarily, a Macbook Air and an iMac.

I keep configuration between these machines about as synced as humanly possibly for development purposes, this includes all of my Sublime settings.

Both are running **macOS 10.13.1**, **Sublime Text 3 Build 3153,** and **BracketHighlighter 2.26.0**.

When my Air updated BH to 2.26.0, there was clear update to the plugin, such as the BH Package Settings menu updating and there being colors for the gutter indicators.

However, on my iMac, there was no changes, most notably the older Package Settings menu items are still present.

**iMac**
![screen shot 2017-11-07 at 9 54 51 am](https://user-images.githubusercontent.com/4140885/32503935-2ea89d3a-c3a4-11e7-9d88-215cf78ae82f.png)

**Air**
![screen shot 2017-11-07 at 9 56 32 am](https://user-images.githubusercontent.com/4140885/32503954-3bf79ffe-c3a4-11e7-8f84-9e0a5ac894b2.png)

## Support Info
There are no errors in the console that I can find, and since the machine that seems to be having the issue (the iMac) doesn't show the updated Package Settings menu, I can't run the Support Info command.

## Steps to Reproduce
I have removed the plugin (from both machines) and reinstalled (via Package Control) multiple times, as well as made sure I have no old config files, restart Sublime, and restart my machines. (as well as about every combination of those I could think of).

**Comment by facelessuser** [comment]
This is not a BH issue.  I imagine somehow Package Control is messed up for you, or your local install of packages is messed up.  All I do is provide the release and Package Control downloads it for you.  I have no more control than that.

I would check if you have more than one BH installed.  Check `Sublime Text 3/Packages/User` and `Sublime Text 3/Installed Packages`.  It is possible you have more than BH installed and the unpacked one is overriding the other.

Also please don't post issues without following the template.  I expect people to providing the info from the Support command as well to see versions of package and package dependencies, and whether they are installed through package control, etc.  Thank you.

**Comment by facelessuser** [comment]
That's the thing. There is no BH install script. Package Control just downloads the latest tag. For BH ST3, it downloads the latest tag prefixed with `st3-`.

As for the template, it instructs you to run a support command to get the general version info to paste into the issue, but I do appreciate the effort.

**Comment by facelessuser** [comment]
Also, when checking Package Control, it appears to show the latest tag: https://packagecontrol.io/packages/BracketHighlighter.

You can try and force an update by going to `Package Control: Upgrade package`.  If that doesn't work, I'd take this issue to Package Control.  I'd have to analyze your Sublime install to understand further why your install hasn't upgraded or is installing the wrong version, but that really is beyond the scope of BH and is better suited as a Package Control issue.

**Comment by green-lizzy** [comment]
@corneliusio I just had brackethighlighter silently fail to install because it failed to pull in dependencies from bitbucket.   It was evidentially  a transient problem with bitbucket because a retry an hour later succeeded.
