### ISSUE TITLE
Brackethighlighting Doesn't Follow Focus With Multiple Views Open

### ISSUE THREAD

**Issue by TruePath** [facelessuser/BracketHighlighter#454]
## Description

**BUG:** If multiple views are opened into the same file the highlighted brackets aren't always selected based on the cursor position in the view currently in focus (i.e. being edited).

## Support Info

- ST ver.: 3154
- Platform: osx
- Arch: x64
- Plugin ver.: 2.26.0
- Install via PC: True
- mdpopups ver.: 3.1.3
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open a file with multiple sets of brackets into it.
2. Go to File > New View Into File.
3. Move the cursor into a set of brackets in the first view.
4. Switch to the second view and move the cursor into a different set of brackets.
5. Return to the first view and move the cursor into yet another set of brackets.
6. Switch back to the second view and move the cursor into yet another set of brackets.

#### Expected Behavior ####

The brackets are highlighted in the view currently in focus based on the movement of the cursor in that view.

#### Observed Behavior ####

In one view bracket highlighting will work correctly.  In the other view (after working correctly for one set of brackets) which brackets are highlighted won't change as thee cursor is moved.  In other words it acts like only the last cursor position in one of the views matters and ignores cursor movement in the other.

(If you are having trouble reproducing  I had high visibility mode enabled and was editing a TeX file but I believe this is easily reproducible)

**Comment by facelessuser** [comment]
This is because "cloned" views always pass a None in for the view in the view listener.  I can get the active view in this case, but I need to know that I'm not in a widget or something like that.  I haven't figured out (or taken the time to figure out) a way to reliably know that I'm in a cloned view yet.

**Comment by TruePath** [comment]
Thanks for the reply (and the great plugin).  Any chance you could do something simple to just disable highlighting in the cloned view?  Would you like me to suggest an edit to the docs so other users don't have to fight with the settings for a long time before realizing what is going on?

**Comment by facelessuser** [comment]
I've actually figured out how to get the highlighting working in cloned views. So I'll have a fix for this soon.
