### ISSUE TITLE
default.style.color='#ff0000',but it's still white

### ISSUE THREAD

**Issue by sin911** [facelessuser/BracketHighlighter#461]
like this picture
![cd2](https://user-images.githubusercontent.com/16552337/33202212-b0809408-d136-11e7-8bfa-cede42264c57.jpg)

how can I change this color?thank you

---------------------------
Sublime Text
---------------------------
- ST ver.: 3143
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.0
- Install via PC: True
- mdpopups ver.: 3.2.0
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
Please read http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style.

Particularly:

> Often I am asked why you can just add a color directly like "color": "#D04321". This is not a decision made by me, but is a limitation of the Sublime API, specifically with region coloring (which is what BH uses to highlight brackets). Sublime needs a scope that exists in your color scheme file. If finds the rule regarding that scope, and applies the color specified in that rule.

**Comment by sin911** [comment]
thank you~
