### ISSUE TITLE
Lua - wrong scope highlighting in while loop

### ISSUE THREAD

**Issue by bofm** [facelessuser/BracketHighlighter#466]
It looks like `while` loop scope is highlighted wrong with the built-in Lua syntax. The second `end` keyword is excessive and is not part of the while loop. And there is the same problem with `for` loop.
![](https://forum.sublimetext.com/uploads/default/original/3X/e/0/e01d39b2ca2ef205940e5f0d767a62a610a72fe1.png)
![](https://forum.sublimetext.com/uploads/default/original/3X/6/2/62b6fbfc1f2fe47e6aad4f310fc8d5c4f9bbadd0.png)

**Comment by facelessuser** [comment]
Next time please use the template.

I don't use Lua, so you're going to have to explain to me how BracketHighlighter is supposed to behave.

Since i don't have time to research languages I don't use, you will have to either issue a pull request, or explain exactly what the issue is.

I'm going to guess that we are highlighting `while` *and* `do` as a block start. Should `do` be ignored in all cases? Even outside a while loop?

**Comment by bofm** [comment]
Thanks for the reply.

We should ignore `do` as a block start in these cases:
```lua
while (...) do
  (...)
end

for (...) do
  (...)
end
``` 

but we should consider `do` as a bock start in this case:
```lua
do
  (...)
end
```

And the mixed case:
```lua
while (...) do  -- this is a part of the while loop syntax
  do  -- this is a "do-end" block start (used for variable scoping purposes)
    (...)
  end
end
```

I could try to play with the regexes if you pointed me to where I should change them :)

**Comment by facelessuser** [comment]
Would it be a fair assumption to say that when `do` is only preceded by whitespace it is safe to include it?

> I could try to play with the regexes if you pointed me to where I should change them :)

It is covered in the documentation: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-brackets.

But remember, there can be only one capturing group. Non capturing groups are fine.  Sometimes we have to implement a plugin hook to strip out things due to the one capture group limit.

**Comment by bofm** [comment]
> Would it be a fair assumption to say that when do is only preceded by whitespace it is safe to include it?

Cannot answer, but this is valid:
```
while (...) do (...) do (...) end end;
for i=1,10 do do print(i) end end;
```

**Comment by facelessuser** [comment]
Ugh.  Well, what I need is a reliable way to tell when we can capture`do` and when we can not.  BH is unaware of language context except through either the regex, or additional plugin hooks.

If we are not able to quantify the cases, we can't write a rule to fix this.

Okay, maybe this.  Is `while` **always** followed by a `do` we shouldn't capture?  If so we could extend the while portion of the pattern to something like`while\s+.+?\bdo\b`.  We'd have to add a hook to strip everything after `while` once we capture it, but then we'll have the `while`, and we'll be able to throw away that `do` as it is already captured.

**Comment by bofm** [comment]
Yes, that should work. And the same for `for` loop.

**Comment by facelessuser** [comment]
Replace `BracketHighlighter\bh_modules\luakeywords.py` with:

```py
"""
BracketHighlighter.

Copyright (c) 2013 - 2016 Isaac Muse <isaacmuse@gmail.com>
License: MIT
"""
from BracketHighlighter.bh_plugin import import_module
lowercase = import_module("bh_modules.lowercase")

LOOPS = ('while', 'for')


def validate(*args):
    """Check if bracket is lowercase."""
    return lowercase.validate(*args)


def post_match(view, name, style, first, second, center, bfr, threshold):
    """Strip trailing while garbage."""

    if first is not None:
        # Strip whitespace from the beginning of first bracket
        open_bracket = bfr[first.begin:first.end]
        for key in LOOPS:
            if open_bracket.startswith(key):
                first = first.move(first.begin, first.begin + len(key))
    return first, second, style


def compare(name, first, second, bfr):
    """Differentiate 'repeat..until' from '*..end' brackets."""
    brackets = (bfr[first.begin:first.end], bfr[second.begin:second.end])
    return (brackets[0] == "repeat") ^ (brackets[1] == "end")
```

Change lua rule in `bh_core.sublime-settings` to:

```js
        // Lua
        {
            "name": "lua",
            "open": "(?:(?<=[\\s;])|(?<=^))(if|(?:while|for)\\s+.+?\\bdo\\b|function|do|repeat)\\b",
            "close": "(?:(?<=[\\s;])|(?<=^))(end|until)\\b",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.luakeywords",
            "language_filter": "whitelist",
            "language_list": ["Lua"],
            "enabled": true
        },
```

Tested on:

```lua
while (...) do
  (...)
end

for (...) do
  (...)
end

while (...) do  -- this is a part of the while loop syntax
  do  -- this is a "do-end" block start (used for variable scoping purposes)
    (...)
  end
end

while (...) do (...) do (...) end end;
for i=1,10 do do print(i) end end;
```

Let me know if you find issues.  If it is fine, let me know and I can get a patch in when I get time, or just issue a pull request with these changes.

But please let me know once you've had a chance to do some testing whether you found additional corner cases.

**Comment by facelessuser** [comment]
Ignore some of the comments in the BH hook.  I copied and pasted some of that code from another hook.

**Comment by facelessuser** [comment]
Hmm...we'll lose the ability to highlight brackets between `while` and `do`...I think I have an idea though.

**Comment by facelessuser** [comment]
I think we need a new hook on for when a new match is starting.  I figure this flow could work:

- Reset any trackers
- On `while` or `for` validation, look ahead in the `validate` hook and track where the next `do` (if any) is.
- On `do` validate, check that it is not tracked and clear the tracker afterwards.

I think this could work.  This can give us a little context and prevent us from capturing what we want to scan later.

I play with this later tonight.

**Comment by bofm** [comment]
Hi, I am going to test it but I cannot figure out how to manually install BracketHighlighter from master branch with all the dependencies. Could you please advise or maybe point me to the related docs or Sublime forum thread?

**Comment by bofm** [comment]
> On do validate, check that it is not tracked and clear the tracker afterwards.

Still don't understand `check that it is not tracked and clear the tracker afterwards` part.

**Comment by bofm** [comment]
I think we should track `while` ,`for`, `end` keywords as we scan the buffer and put "loop scope open " and "loop scope close" events on a stack. Whenever we get `do` we should check if there is an open loop scope on the stack and decide whether to ignore the `do`.

**Comment by facelessuser** [comment]
> I think we should track

Exactly how it gets done will be decided once I get the hook in. The previous suggestion was made based on previous thinking of looking ahead for the `do`.  Regardless of what gets tracked, we still need the hook.

I think we may still get weird corner cases as BH works in a sliding window.

Unfortunately, lua context seems to be best understood scanning from the start of the file than analyzing a snippet. So I'll just have to play around and find the least bad idea.

**Comment by FichteFoll** [comment]
As a workaround idea, how about ignoring `while` and `for` and just put the markers on their `do` that will eventually follow?

**Comment by facelessuser** [comment]
Ha! Now we're thinking! I'm pretty sure I've done that with other languages. Wonder why I didn't come up with that here? To close to the problem I guess...

**Comment by bofm** [comment]
Hm, that would work but visually the highlighted ‘do’ which is usually on the right hand side of the screen would not be very noticable for the eyes comparing to the properly highlighted “while|for”.

**Comment by facelessuser** [comment]
> Hm, that would work but visually the highlighted ‘do’ which is usually on the right hand side of the screen would not be very noticable for the eyes comparing to the properly highlighted “while|for”.

Meh. BH can't waste time processing the file from the beginning, so it uses a sliding window.  Sliding window may not always capture a `while` or `for` before a `do` leading to unreliable highlighting in certain cases.  The current syntax highlighter doesn't scope a `while...do` different than a `do`, so I don't have any context.

Highlighting `do` makes the most sense.  If the syntax highlighter ever scopes the `while..do` differently, I can use that to make decisions.  There will be some people bothered by `while` and `for` not getting highlighted, but that is the best that can be done.  I'm okay with it, so I'll sleep fine 🙂 .  It's better than incorrect or none at all.

I'm open to better suggestions, but right now, highlighting `do` is the most reliable and best suggestions.

**Comment by FichteFoll** [comment]
When I (or someone else) take the time to rework the Lua syntax, this is most likely something that would happen.

**Comment by facelessuser** [comment]
@FichteFoll, yeah, that is probably the *real* way to give people what they want.  Scoping is where context should really be acquired from since the syntax processing is context aware.  I'll be more than happy to utilize that for proper `while|for` highlighting (if/when available), but until then, I think sticking to `do` is the appropriate compromise.
