### ISSUE TITLE
Match Bracket Pair Colorizer style

### ISSUE THREAD

**Issue by ellipticaldoor** [facelessuser/BracketHighlighter#467]
I just found this package and Im wondering if it would be possible to match the same behaviour with BracketHighlighter

https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer

![image](https://user-images.githubusercontent.com/3449006/36075143-341a8a0a-0f42-11e8-83a9-4c20a7ce33d0.png)

**Comment by ellipticaldoor** [comment]
I just found this https://github.com/facelessuser/BracketHighlighter/issues/423

**Comment by facelessuser** [comment]
Okay, if you were looking for features like Rainbowth, then my answer is the same as I gave in #423.

**Comment by ellipticaldoor** [comment]
Yep, that's why I closed. Thank you.

Though very good plugin!! I'm going to use it though.
