### ISSUE TITLE
Install fails because of dependencies

### ISSUE THREAD

**Issue by eugenr2** [facelessuser/BracketHighlighter#469]
## Description

When trying to install BracketHighlighter via PackageControl I see the following messages in console:

```
Package Control: Fetching list of available packages and dependencies
  Platform: linux-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: Fetching list of available packages and dependencies
  Platform: linux-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: The dependency 'pygments' is not available
Package Control: The dependency 'pygments' could not be installed or updated
```
Then the install fails, no package gets installed.
This happens on a fresh install of ST.  Any idea what could be the cause of this issue?

**Comment by facelessuser** [comment]
Package Control is having issues with dependencies: https://github.com/wbond/package_control/issues/1334

**Comment by eugenr2** [comment]
Thank you for answering.  I'll keep an aye on that thread.
