### ISSUE TITLE
Not installing console says Pygments not found

### ISSUE THREAD

**Issue by Shahin27** [facelessuser/BracketHighlighter#470]
Can't install BracketHighlighter. 
It just stops installing nothing else.
In the console, it says Pygments not found. Not sure what it is. Tried online to find solution can't find anything.
--
Tried on
> Sublime text 3 
> version: 3.0
>build: 3143

**Comment by facelessuser** [comment]
See duplicate issue: https://github.com/facelessuser/BracketHighlighter/issues/469
