### ISSUE TITLE
There is a way to disable brackets always on the gutter

### ISSUE THREAD

**Issue by ellipticaldoor** [facelessuser/BracketHighlighter#472]
There is an option for disabling the brackets on the gutter always?

I can't find it

**Comment by facelessuser** [comment]
Please follow the issue template in the future.

Please read http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style which should answer your question.  There is no global option, but you can tweak your highlight style for each bracket that you don't want to show icons for.

**Comment by facelessuser** [comment]
I'm assuming this question was answered, so closing.
