### ISSUE TITLE
support "Tilda" in javascript

### ISSUE THREAD

**Issue by mrG0bliN** [facelessuser/BracketHighlighter#477]
what about tilda? its popular tools in ES6, have plans for the future?
![](https://image.ibb.co/dGQspx/image.png)

**Comment by facelessuser** [comment]
1. Please follow the issue template when creating any issues in the future.  I generally will close issues that are not following the template.

2. I don't use JavaScript very much, so adding tilde is very low priority to me.  I general, I leave new bracket support up to the community while I focus on the core code.  The exception is when it touches a language I use a lot, and I also have interest in adding said bracket.

I will leave this issue open until either a) someone issues a pull request addressing this issue or b) I get around to doing it myself.

**Comment by mrG0bliN** [comment]
@facelessuser thank you very much for the answer

**Comment by facelessuser** [comment]
I did actually go ahead and add this support for default JavaScript.  Should be available in next release.
