### ISSUE TITLE
Laravel Code breaks html tag detection depending on cursor position

### ISSUE THREAD

**Issue by FeBe95** [facelessuser/BracketHighlighter#480]
## Description

Some language specific special characters break the detection of closing html tags, but only if the cursor is placed at specific positions.
Happens with and without the Laravel Blade Highlight package enabled.
The ST3 native tag detection (dotted underline) works as expected (not with multiple selections though)

## Support Info

- ST ver.: 3143
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.2
- Install via PC: True
- mdpopups ver.: 3.3.2
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

Example code:
```
<div>
    <span @if($foo == 'bar') selected @endif>foobar</span>
</div>
```

Different cursor positions:
![grafik](https://user-images.githubusercontent.com/7470739/38455391-b6b1531c-3a77-11e8-9428-98ce37f76cb4.png)
![grafik](https://user-images.githubusercontent.com/7470739/38455393-c2c38396-3a77-11e8-8d08-427442b8f1c8.png)
![grafik](https://user-images.githubusercontent.com/7470739/38455377-8bc64c02-3a77-11e8-9289-575e3fdb6f9e.png)

Simplest code that breaks the highlighting (incorrect syntax though):
![grafik](https://user-images.githubusercontent.com/7470739/38455440-68126ae2-3a78-11e8-8655-39bba16278cc.png)

Working code:
![grafik](https://user-images.githubusercontent.com/7470739/38455418-27bf8f92-3a78-11e8-93dc-40aab2ed6489.png)

**Comment by facelessuser** [comment]
This is because Laravel is not HTML and breaks HTML syntax.  BracketHighlighter currently only highlights HTML, not Laravel.

**Comment by facelessuser** [comment]
There would need to be Laravel specific support added. Ideally not to the default HTML.  The more various template support added to HTML, the less reliable HTML tag detection would most likely become, and the harder it would be to keep the quality up as there would be conflicting template rules etc.

Anyways, as I don't use Laravel, this would have to be included via pull request by the community.
