### ISSUE TITLE
[Feature Request] Highlight brackets with their own color

### ISSUE THREAD

**Issue by papadokolos** [facelessuser/BracketHighlighter#485]
## Description
It is really nice that each type of bracket/brace/paren/etc.. is highlighted with a specific and unique color. However, it will be even nicer if the color of the highlight would be the same as the color of the character being higlighted.

For example, when a pair of quotes is colored in yellow (by the color scheme), BracketHighlighter will highlight the pair with a yellow underline. When a pair of braces get a purple color by the color scheme, BracketHighlighter will highlight the braces in purple color as well.

## Suggested approach for implementation
This can be done by inheriting the scope of the highlighted character.

I managed to implement it by myself. But my implementation only supports the first highlighted pair, and doesn't blend very nicely with the code...

Would love to hear your thoughts about this. Thank you for this amazing plugin!

**Comment by facelessuser** [comment]
I can understand the appeal of this, but the current code is optimized to set all like bracket types in one shot.  For the sake of maintenance, I don't think this is something I'm currently interested in doing.

 > Thank you for this amazing plugin!

No problem :).
