### ISSUE TITLE
else support

### ISSUE THREAD

**Issue by lab313ru** [facelessuser/BracketHighlighter#487]
For example, there is some makefile case:
```
ifeq OS
VAR1:="help1"
else
VAR1:="help2"
endif
```
Now it is impossible to customize this.

**Comment by facelessuser** [comment]
Why is this impossible? There isn't enough information for me to really understand the request/issue being described.

**Comment by lab313ru** [comment]
I mean it is only possible to define
if-else,
else-endif,
if-endif

But I need to highlight if-else-endif together.

Isaac Muse <notifications@github.com> 1 июля 2018 г. 15:04:48 написал:

**Comment by facelessuser** [comment]
Every if/else has an end. BH only highlights openings and closings. Better put, BH highlights brackets and bracket like conventions which is often leveraged to highlight if and if/else blocks. It will only highlights the start and end of an if/else block (if configured correctly), it will not highlight the 'else' in the middle if that is what you are requesting. I have no intentions to add such functionality as BH is only meant to target starts and ends.

**Comment by lab313ru** [comment]
For now it doesn't work at all, because there is no Makefile brackets highlighting, so I added such definition. And it is doesn't work.
`		{
			"name": "makefile_defs",
			"open": "^(if|ifdef|ifndef|ifeq)\\b",
			"close": "^(endif|else)\\b",
			"style": "default",
			"scope_exclude": ["string", "comment"],
			"language_filter": "whitelist",
			"language_list": ["Makefile"],
			"enabled": true
		},
`

**Comment by facelessuser** [comment]
Right, and I leave adding new language support up to the community so I can focus on the core code. With that said, you should not at else to the end definitions as else is not an end. It is a middle. BH targets beginnings and ends.

**Comment by lab313ru** [comment]
`Else-endif` block is the same as `if !(cond)`-`endif`, so it is the same as "beginning".
so supporting such blocks will be good feature.

For example if you have huge `if-else` block and then you have `else-endif` block it will be very difficult to analyze such blocks.

**Comment by facelessuser** [comment]
BH doesn't highlight else and has no intentions of doing this. Then you have ends that are also beginnings, and BH looks for clear beginnings and ends.

I understand that huge elseif blocks do not get a huge benefit from the highlighting, but BH was not designed for highlighting language if/else blocks, it is just commonly leveraged for that. It will show you the start of the entire block and the end as it is designed to show you the start of a bracketed group and the end.
