### ISSUE TITLE
Ignore_threshold not working in BracketHighlighter in Sublime 3

### ISSUE THREAD

**Issue by eduard-tkv** [facelessuser/BracketHighlighter#489]
## Description

... what is the issue ?

Ignore_threshold not working in BracketHighlighter in Sublime 3. I tried increasing the threshold or tried ignoring it, it still doesn't work. Keeps saying "Matching bracket not found" (in an HTML file). I have a user settings file, and then I go to Preferences->Package Settings->BracketHighlighter->Bracket Settings

...

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

- ST ver.: 3176
- Platform: windows
- Arch: x32
- Plugin ver.: 2.27.4
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open a large HTML file
2. Try matching brackets beyond 5k char threshold
3. Set ignore_threshold in user settings file to true

![bracketsubmlie](https://user-images.githubusercontent.com/3612663/42466739-64500a04-8375-11e8-99d3-7d16a8f156b0.png)

**Comment by facelessuser** [comment]
It seems to work for me.  I don't recommend enabling `ignore_threshold` unless you want BH to lock up and slow things down in really big files though.

**Comment by eduard-tkv** [comment]
Can't make it work. What's weird is that bracket_styles work but ignore_threshold in the same file doesn't work. Will try to reinstall Sublime.

**Comment by eduard-tkv** [comment]
Tried reinstalling Sublime, removing/installing BH, still no luck... Back to VS Code then...

**Comment by eduard-tkv** [comment]
I didn't know about the console. It says "Unable to open /C/Users/{UserName}/AppData/Roaming/Sublime Text 3/Packages/BracketHighlighter/bh_core.sublime-settings". Where supposed to be bh_core.sublime-settings? How come it finds it when I go Preferences->Package Settings->BracketHighlighter->Bracket Settings? Any ideas?

**Comment by facelessuser** [comment]
> t says "Unable to open /C/Users/{UserName}/AppData/Roaming/Sublime Text 3/Packages/BracketHighlighter/bh_core.sublime-settings".

Okay, at least we know there is something wrong on your system.

How did you install BracketHighlighter?  I'm assuming you used package control? You didn't also check it out locally with git did you?

When you installed it, did you restart Sublime Text?  If you didn't, you definitely need to do that.

I would probably try uninstalling BracketHighlighter reinstall, restart Sublime, and then try it out again.

**Comment by eduard-tkv** [comment]
I installed using package control. Still not working, will give it another clean go whenever I have time. Thanks for the tip. You may close the issue. Thanks

**Comment by facelessuser** [comment]
No problem.
