### ISSUE TITLE
In light theme, can't have solid highlighting with white background

### ISSUE THREAD

**Issue by CuriousPhilomath** [facelessuser/BracketHighlighter#491]
## Description

I'm using a theme ("Eiffel (SL)") that uses a white background. Until recently, I had been using an older version of Sublime Text 3 (3160), and my highlighting simply changed the colour of my brackets and quotes to the colours I had specified in the `Eiffel (SL).tmTheme` file.

However, I recently upgraded to ST3 version 3176 and now I can only get highlights in (what used to be called) 'reverse field': i.e. the *background* in the colour I specified and the *foreground* (the actual glyph) in my theme's background colour (which I believe is white).

## Support Info

- ST ver.: 3176
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.4
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

Using the Eiffel (SL) light theme:

1. Create user-defined BH settings file (`bh_core.sublime-settings`) and in it, add the following:
```
    "user_bracket_styles": {
        "curly": {
            "color": "brackethighlighter.curly",
            "style": "solid"
        }
    }
```

2. Create user-defined colour scheme file (`Eiffel (SL).sublime-color-scheme`) and in it, add the following:
```
{
    "rules": [
        {
            "scope": "brackethighlighter.curly",
            "foreground": "#44CC44"
        }
    ]
}
```

At this point, I expect my highlighted curly brackets to show as green, but instead, they are shown as a green square around a white brace.

I tried changing `"foreground"` to `"background"` and got the same result.

The same results occur for other region styles (e.g. quotes, round brackets, etc) as well.

I didn't see this issue in the list, so I apologize if I missed it.

**Comment by facelessuser** [comment]
@CuriousPhilomath, BracketHighlighter does not control how Sublime renders colored regions, we simply use Sublime's API to create the region with the given scope.  You will have to play with foreground and background colors in your color scheme file yourself to see if you can find some combination that does what you want it do.

As far as BracketHighlighter Documentation goes, we mainly show simplistic examples, to control both foreground and background colors, you will have to experiment yourself.  Maybe this previous issue will help you get closer to what you are looking for: #483.

**Comment by CuriousPhilomath** [comment]
Thanks for the feedback and the reference. That issue does help. Thanks!
