### ISSUE TITLE
anonymous function in lua cause matching broken

### ISSUE THREAD

**Issue by haolly** [facelessuser/BracketHighlighter#493]
---

## Description

... what is the issue / request ?

The anonymous function in lua cause matching bracket could not be found
![image](https://user-images.githubusercontent.com/2383231/43707021-87c21740-9999-11e8-835f-466a75f38934.png)

See the image above.
If I comment out line 113-114, it works fine, see below:

![image](https://user-images.githubusercontent.com/2383231/43707086-b5652246-9999-11e8-9ec8-1e2ff7de47c0.png)

## Support Info

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

 - ST ver.: 3176
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.4
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
Can you post a copy pastable example?

**Comment by haolly** [comment]
@facelessuser  try this:
```lua
local mt = {}
function mt:fine()
	self.update_id = global.updater:register(function(_, dt)
		self:update(dt)
	end)
end
```
