### ISSUE TITLE
Trying to tweak this code, to fold all code in a file

### ISSUE THREAD

**Issue by jokoon** [facelessuser/BracketHighlighter#497]
This comment has config and shortcuts so that BracketHighlighter can fold text in a compact manner (see issue):

https://github.com/SublimeTextIssues/Core/issues/101#issuecomment-363109020

I was wondering if it was possible to have that shortcut or another to fold all function that are on the same level, or maybe everything, similarly to fold-all shortcuts in sublime text. Do I need to change some values to make it work?

**Comment by facelessuser** [comment]
BracketHighlighter is optimized to target the bracket directly surrounding the cursor(s). Unfortunately, at no time, does BracketHighighter have an understanding of all brackets.  This is not something I have particular interest in changing, and currently have no suggestions currently to make it do such as it would require very big changes.

**Comment by facelessuser** [comment]
Closed as answered
