### ISSUE TITLE
Matching <![CDATA[ tags in XML?

### ISSUE THREAD

**Issue by sharunkumar** [facelessuser/BracketHighlighter#498]
## Description

I have been trying to add the cdata tag as a bracket. this is the entry I have added to my settings:
```
...
        //XML
        {
        	"name":"xml_cdata",
        	"open":"(<!\\[CDATA\\[)",
        	"close":"(\\]\\]>)",
        	"style":"default",
            "language_filter": "whitelist",
        	"language_list": ["XML"],
        	"scope_exclude": [
        		"comment"
        	],
        	"enabled":true
        },
...
```

However, the "Matching Bracket" error message pops up. Perhaps this is conflicting with other brackets?

## Support Info

- ST ver.: 3176
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.4
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Add the above mentioned configuration to bh_core.sublime-settings
2. Create a new XML file and make a CDATA tag:

```
<![CDATA[

]]>
```

3. Error message shows

**Comment by facelessuser** [comment]
I just finally looked at this.  Do you have the full setup of your personal BracketHighlighter settings?  Order can be important and such. The small snippet provided doesn't really let me know how everything is setup.

**Comment by facelessuser** [comment]
@sharunkumar, this rule needs to come before the square bracket rule, that is why it is having issues.  The square bracket rule consumes the closing `]` before the XML rule ever gets there.

**Comment by facelessuser** [comment]
I will consider this answered. Feel free to reopen if you have more questions.

**Comment by sharunkumar** [comment]
Hi thanks for your answer! I will try adding this before the square bracket rule.
