### ISSUE TITLE
Trips on @ characters in HTML attributes

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/BracketHighlighter#505]
## Description

BracketHighlighter doesn't handle tags with `@` characters in attributes. While they are probably invalid HTML (didn't check), supporting them regardless should be trivial and not break anything in the process.

I'm using the default HTML syntax and `@` characters are for Vue.js templates

![2018-11-09_19-10-13](https://user-images.githubusercontent.com/931051/48280261-6607b600-e453-11e8-967b-9a9e333a1ebe.png)

![2018-11-09_19-10-25](https://user-images.githubusercontent.com/931051/48280262-6607b600-e453-11e8-9147-eb960e5c224e.png)

```html
  <button class="ui button compact small right floated"
      v-bind:class="{ primary: booleans.hideSelectActive }"
      @click="toggleHiddenEntries">
    {{ booleans.hideSelectActive
       ? "Hide shows"
       : "Select shows" }}
  </button>
```

## Support Info

- ST ver.: 3180
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.4
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
I've generally been resistant to adding such special attribute chars to HTML and have been encouraging people to create a vue profile in the settings to be used with vue syntax.  I was unaware that the default HTML syntax allows `@` in attributes. What all does the default syntax allow in attributes? If I start adding in syntax for one template (or HTML derivative) language, I will get an influx for others.  If I knew more about what the default syntax allows, maybe I can just match that.

**Comment by FichteFoll** [comment]
https://github.com/sublimehq/Packages/blob/289782ff2e4cb58de171579c7fc86fe00d280619/HTML/HTML.sublime-syntax#L13

This, probably.

**Comment by facelessuser** [comment]
Yes `:` is handled by BH to cover namespaces that can occur in HTML5 with embedded XML content. Sublime syntax allowance is a bit more permissive than I'd like, but maybe I should just came and allow some of these other symbols. Is `@` the only needed one? I assume it is restricted to only attributes?

**Comment by FichteFoll** [comment]
Yes, I believe `@` is the only other attribute character used by Vue and is short for `v-on:`, just like a leading `:` is short for `v-bind:`. Only for attribute names.

**Comment by facelessuser** [comment]
Okay, when I get a chance I'll make the adjustment.
