### ISSUE TITLE
Bracket Highlighter doesn't work after PackageControl install

### ISSUE THREAD

**Issue by anneCarlson** [facelessuser/BracketHighlighter#506]
## Description
In sublime text 2, I installed BracketHighlighter using package control. In the console, I get the following errors:

```
ignored packages updated to: [BracketHighlighter, PHP, Vintage]
found 1 files for base name Default.sublime-theme
reloading /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
theme loaded
reloading /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
ignored packages updated to: [PHP, Vintage]
found 1 files for base name Default.sublime-theme
reloading /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_core.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./bh_core.py", line 13, in <module>
    import BracketHighlighter.bh_plugin as bh_plugin
ImportError: No module named BracketHighlighter.bh_plugin
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_logging.py
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_plugin.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./bh_plugin.py", line 15, in <module>
    from BracketHighlighter.bh_logging import log
ImportError: No module named BracketHighlighter.bh_logging
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_popup.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./bh_popup.py", line 13, in <module>
    from BracketHighlighter.bh_logging import log
ImportError: No module named BracketHighlighter.bh_logging
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_regions.py
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_remove.py
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_rules.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./bh_rules.py", line 7, in <module>
    from backrefs import bre
ImportError: No module named backrefs
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_search.py
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_swapping.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./bh_swapping.py", line 9, in <module>
    import BracketHighlighter.bh_wrapping as bh_wrapping
ImportError: No module named BracketHighlighter.bh_wrapping
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_wrapping.py
Reloading plugin /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/support.py
found 16 files for base name Default.sublime-keymap
found 44 files for base name Main.sublime-menu
reloading /Users/annecarlson/Library/Application Support/Sublime Text 2/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
```

I edit Preferences.sublime-settings so all the bracket matching settings are set to false, as in the install guide.

I restart sublime, and the package does nothing (no highlighting with cursor). If I go to BracketHighlighter preferences, several options are greyed out:
![screen shot 2018-11-27 at 2 15 06 pm](https://user-images.githubusercontent.com/1570088/49105594-fe24de00-f24e-11e8-8c18-2040e965ba26.png)

I have no other  3rd party syntax highlighting package installed to my knowledge. I had rainbowth installed a while ago but uninstalled with package control when it didn't work with sublime 2.

## Support Info

- ST ver.: 2221
- Platform: osx
- Arch: x64
- Plugin ver.: 2.27.5
- Install via PC: True
- mdpopups ver.: Version could not be acquired!
- backrefs ver.: Version could not be acquired!
- markdown ver.: Version could not be acquired!
- pygments ver.: Version could not be acquired!
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Install BracketHighlighter with package control
2. Update references.sublime-settings so all the bracket matching settings are set to false, as in the install guide.
3. Restart sublime

**Comment by facelessuser** [comment]
Package Control should not be installing BH. I don't actively support ST2 on Package Control anymore. You can see that Package Control site shows only ST3 support: https://packagecontrol.io/packages/BracketHighlighter.

I do have a ST2 branch available, but some manual installation is required.

**Comment by anneCarlson** [comment]
Oops! Thank you!

**Comment by OlehCherenkov** [comment]
> Package Control should not be installing BH. 
Hi, i have same problem

plugins loaded
SublimeLinter: debug mode: off 
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: Loading PyV8 binary from https://raw.github.com/emmetio/pyv8-binaries/master/pyv8-linux64-p3.zip
Package Control: No updated packages
ignored packages updated to: ["BracketHighlighter"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/facelessuser/BracketHighlighter/zip/st3-2.11.0.
error: Package Control

Unable to download BracketHighlighter. Please view the console for more details.
How can i install BH now?

**Comment by facelessuser** [comment]
You've provided me with no info on what version of Sublime you are using. Please provide that information. It seems odd that it is trying to download such an old version though. Depending on more info, this may be   a Package Control issue.

**Comment by facelessuser** [comment]
Also, please open a new issue as your issue may be very different than the opening post.

**Comment by OlehCherenkov** [comment]
> You've provided me with no info on what version of Sublime you are using. Please provide that information. It seems odd that it is trying to download such an old version though. Depending on more info, this may be a Package Control issue.
>
I installed BH by webarchive channel package control =) Tnx
- ST ver.: 3176
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.4
- Install via PC: True
- mdpopups ver.: 3.3.4
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
I'm not sure what webarchive is.

**Comment by facelessuser** [comment]
I'm closing this as the original issue was answered.  In additional issues should be opened in a new issue.
