### ISSUE TITLE
Incompatability with WrapAsYouType

### ISSUE THREAD

**Issue by dhelonious** [facelessuser/BracketHighlighter#508]
## Description

I started using a fairly new plugin called [WrapAsYouType](https://github.com/btrekkie/WrapAsYouType) for automatic hard wrapping in source code comments. However, BracketHighlighter seems to break the intended behavior of the wrapping (see [WrapAsYouType issue #2](https://github.com/btrekkie/WrapAsYouType/issues/2#issuecomment-443836298)) by [messing with the regions](https://github.com/btrekkie/WrapAsYouType/issues/2#issuecomment-443866988).

I think that this issue is related to #431. If I understood correctly, the issue described there is the same which is described by the author of WrapAsYouType. As it is not only impacting performance but may cause trouble with other packages, I thought a seperate issue is justified. So far, WrapAsYouType is the only plugin I use that is affected by this.

## Possible solution

The author of WrapAsYouType suggested that storing whether BracketHightlighter is busy os not in a variable instead of settings (see [here](https://github.com/btrekkie/WrapAsYouType/issues/2#issuecomment-444283452)). I tested this by introducing a single global variably for that purpose. Though, this does not completely solve the issue for me, it is occuring much, much less often than before.

I understand, that there might be no simple solution for using global variables instead of settings, as mentioned [here](https://github.com/facelessuser/BracketHighlighter/issues/431#issuecomment-324758481). The purpose of this post is rather to inform you about this issue.

## Additional information

Here I provide some information on my Python syntax settings, which could be useful if someone wants to recreate the issue. I'm using [MagicPython](https://packagecontrol.io/packages/MagicPython) with the following WrapAsYouType settings:

```json
{
	"wrap_as_you_type_paragraphs":
	[
		{
			"first_line_regex": "^.*TODO:.*$",
            "selector": "comment.line",
			"single_line": true
		},
        {
            "first_line_regex": "^(\\*?\\*?[a-zA-Z_][a-zA-Z_0-9]*|[a-zA-Z_][a-zA-Z_0-9]*\\[.+\\]|[a-zA-Z_][a-zA-Z_0-9]* \\([^\\)]+\\)): ",
            "indent": "    "
        },
        {
            "first_line_regex": "^((>>>|\\.\\.\\.)( |$)|<BLANKLINE>$)",
            "single_line": true
        },
        {
            "first_line_regex": "^(\"\"?|''?)$",
            "single_line": true
        }
	],
	"wrap_as_you_type_sections":
	[
		{
			"selector": "comment.block - punctuation.definition.comment",
			"wrap_width": 80
		},
		{
			"combining_selector": "source - (comment | constant | entity | invalid | keyword | punctuation | storage | string | variable)",
			"selector": "string.quoted.docstring",
			"wrap_width": 80
		},
		{
			"combining_selector": "source - (comment | constant | entity | invalid | keyword | punctuation | storage | string | variable)",
			"line_start": "#",
			"selector": "comment.line",
			"wrap_width": 80
		}
	]
}
````

## Support Info

- ST ver.: 3176
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.5
- Install via PC: True
- mdpopups ver.: 3.3.4
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

This issue is not limited to a specific OS, as it occurs on all of my machines with either Windows or Linux.

## Steps to Reproduce Issue

1. Install [WrapAsYouType](https://packagecontrol.io/packages/WrapAsYouType)
2. Configure syntax-specific settings as in the [Readme](https://github.com/btrekkie/WrapAsYouType/blob/master/README.md) (see above for a Python example)
3. Type something that is wrapped by WrapAsYouType

**Comment by facelessuser** [comment]
So, I don't understand, how is BH "messing with the regions". I'm not understanding how BH is breaking indentation.

Are we just not happy with performance? I can see that being related to #431.

**Comment by dhelonious** [comment]
The problem is, that BH does something, which makes Sublime Text delete stored regions. I think it is a bug in Sublime Text itself, which, however, seems to occur, because BH changes the view settings very often. I can imagine, that this API feature is not intended to be used in such a way.

The problem is nicely illustrated in [this code snippet](https://github.com/btrekkie/WrapAsYouType/issues/2#issuecomment-443866988):
```python
import sublime
import sublime_plugin

class BreakWrapAsYouType(sublime_plugin.EventListener):
    def on_selection_modified(self, view):
        def break_wrap_as_you_type():
            view.settings().set('foo', True)
            view.settings().set('foo', False)
        sublime.set_timeout(break_wrap_as_you_type, 0)
```

This should break any package, which heavily relies on regions (as WrapAsYouType).

**Comment by facelessuser** [comment]
> This should break any package, which heavily relies on regions (as WrapAsYouType).

I will have to investigate this.  BH uses regions as well, and I have never seen regions disappear due to how it does things.  I also use multiple plugins that use regions, all of which I haven't experienced regions being removed.

I'm not saying there isn't a link somehow between BH and WrapAsYouType, but WrapAsYouType is a very new plugin, the first that has complained that BH is causing regions to be removed. Performance, as I stated earlier I understand. But I am suspicious of what WrapAsYouType is doing specifically.

I will play with the snippet you've provided.  You haven't exactly explained what I should experience using the above snippet though.  Is it meant to mimic how BH is breaking things?  Or something WrapAsYouType is employing?

**Comment by dhelonious** [comment]
Thank you for investigating this issue. I don't really understand it either. Except for WAYT I did not notice any problems so far, although I used and still use quite a lot of packages (and many of yours). I could not find anything special in the source code of WAYT, but I'm fairly inexperienced. I also failed to reproduce this issue of WAYT with a test plugin using regions. So I really do not understand what distinguishes WAYT.

Some addition explanation for the issue: WAYT will wrap text paragraphs according to some width. However, if line breaks are inserted manually, WAYT will preserve these line breaks. It uses a region called `"wrap_as_you_type_explicit_line_break"` to remember intended line breaks as long as the cursor is not moved manually. This region seems to be erased when a setting is set very often, which results in [the behavior shown in this gif](https://github.com/btrekkie/WrapAsYouType/issues/2#issue-384003756).

From the description of #431:

> It seems that every time I moved the cursor, BH changes the value of a view setting bracket_highlighter.busy twice, from False to True then False again.

If I'm not mistaken, this is effectively what the snipped above does?

**Comment by facelessuser** [comment]
Hmm.  It is possible that WAYT is greatly abusing regions and forcing us into some corner case.  I find it interesting that WAYT is the only plugin experiencing this issue, and the response is that everyone else is at fault, even though this issue has never been experienced by other plugins.

Now, that doesn't mean we aren't contributing in some way to the issue.  I'll need to try and reproduce this issue outside of WAYT and BH.  I don't want to debug WAYT, and I need to verify that what BH is doing can somehow break regions.  If it does, I would still argue it is a Sublime bug, but maybe we could mitigate the issue.

I'll be honest, this is low priority for me as only WAYT is experiencing this issue.

**Comment by dhelonious** [comment]
I see your point, it is quite suspicious. If there is something I can do to help you, then let me know.

I also see this issue as low priority. For everyone who wants to use WAYT along with BH (without which I cannot live anymore 😉), there is now a `"wrap_as_you_type_passive"` setting which kind of solves the issue by disabling some functionality of WAYT.

**Comment by facelessuser** [comment]
Great.  Not sure when I'll look at this, but I'll let you know if there is anything else I need.

**Comment by facelessuser** [comment]
I never was able to come to any action for this issue, so closing it as it is pretty stale. We'll see if it ever surfaces again.
