### ISSUE TITLE
InvalidCertificateException - sublimeText3 

### ISSUE THREAD

**Issue by ftslo** [facelessuser/BracketHighlighter#511]
Not sure if this is the correct channel to post this issue.

Ever since updating to Mac OSX Mojave 10.14.2, SublimeText 3 has displayed the following console notifications on start up of the program.

## Description

```
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/facelessuser/BracketHighlighter/zip/st3-2.27.6.
error: Package Control

Unable to download BracketHighlighter. Please view the console for more details.

```
Is this something that is handled by the plugin writer or by SublimeText or GitHub? Thanks.

## Support Info

Mac OSX Mojave 10.14.2, SublimeText 3 

## Steps to Reproduce Issue

1. Update Mac to 10.14.2
2. Open SublimeText3
3. Not be able to access BracketHighlighter Package

**Comment by facelessuser** [comment]
You will have to take this over to [Package Control](https://github.com/wbond/package_control). I do not control certificate handling on a user's system. My code is hosted on GitHub, which is where Package Control retrieves it from, and I do not control GitHub's certificates either.
