### ISSUE TITLE
Advice on how to match "if" and "for" keywords in Julia language

### ISSUE THREAD

**Issue by fsaad** [facelessuser/BracketHighlighter#513]
## Description

I am writing to seek advice on how to fix my settings so that they correctly match "if" and "for" keywords in the [Julia language](https://julialang.org/).

Much like Bash, Julia has a collection of keywords: `for`, `while`, `if`, `try`, `function`, `begin`, and `module`, which must be matched with the `end` keyword.

Towards this end I have defined the following in my `bh_core.sublime-settings` file:
```
        // Julia
        {
            "name": "julia",
            "open": "\\b(begin|do|function|module|try|for|if)\\s",
            "close": "(?:(?:;|^)\\s*)\\b(end)(?=;|\\s|$)",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "language_filter": "whitelist",
            "language_list": ["Julia"],
            "sub_bracket_search": "true",
            "enabled": true
        },
```

So far the bracket matching works quite well, for example all the code in the example below is matched correctly by BracketHighlighter.

![image](https://user-images.githubusercontent.com/5721897/51792052-33c84380-217a-11e9-9186-1e44f2b7a740.png)

## The Problem

The main issue is that my rules do not account for the special that `if` and `for` keywords are used to manage the control flow in a list or generator comprehension, in which case they do _not_ require an `end`. For example in the following code:
```julia
x = [do_function(i) for i in 1:10 if i / 2 > 2]
w = Dict(i => func(i+1) for i in 1:10 if g(i))
```
both `for` and `if` do not need an `end` but my settings fail since I haven't handled this case.

I'm wondering what are some ways that I can write custom rules for `if` and `for` that capture this case. The design space is quite large e.g. in the following code the first `for` needs and `end` but the second one does not:
```julia
x = [
    begin
        x = 0
        for x in 1:i
            x += i
        end
    end
    for i in 1:10
]
```
since the first `for` is scoped within a `begin`...`end` block, not a list comprehension.

Maybe the only way to handle this case properly is to write a Julia parser but I thought to check here before doing that.

## Support Info

- ST ver.: 3176
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.6
- Install via PC: True
- mdpopups ver.: 3.4.0
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by fsaad** [comment]
@facelessuser Thanks for the quick follow-up.

> Most likely, only highlighting if and for blocks that start a line (accounting for whitespace) may be all you need.

The main challenge here is that non-block `if` and `for` can (and often do) still start a new line, as in the following example:
```julia
x = [
   some_very_long_function_name(y, "hi", 10, i)
   for i=1:10
   if conition_on_iterator(i)
]
```
although I might be misunderstanding what it means to start a line accounting for whitespace.

**Comment by fsaad** [comment]
I checked the [`Julia.sublime-syntax`](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax) file using the [ScopeHunter](https://github.com/facelessuser/ScopeHunter) to check what is happening in the block and non-block versions and they seem to be in the same syntax scope.

**Comment by facelessuser** [comment]
Hmm, you may need a bh_plugin to figure out content.

**Comment by facelessuser** [comment]
Closing this as there is no action for BH take.
