### ISSUE TITLE
[bug] fails to find brackets when bracket chars are in strings (JSON)

### ISSUE THREAD

**Issue by acheronfail** [facelessuser/BracketHighlighter#516]
## Description

Apologies if this is a known behaviour, but I didn't find any similar issues.

BH fails to match brackets when some bracket characters are inside strings.
This is within the default JSON syntax.

## Steps to Reproduce Issue

1. Open a JSON file
2. Create an object inside an array
3. Have a key containing a bracket `[` or `]`
4. Repeatedly call BH's "Jump to left/right bracket" commands

See the attached GIFs of my example:

**WITHOUT `]` in string = working as intended**
![bh-working](https://user-images.githubusercontent.com/34289614/52535030-4c9d3f80-2d9d-11e9-8241-69ec22d09a37.gif)

**WITH `]` in string = seems to fail to find brackets**
![bh-broken](https://user-images.githubusercontent.com/34289614/52535034-5cb51f00-2d9d-11e9-8392-1d4ccb94a8ca.gif)

To me, this seems to be broken behaviour. Shouldn't BH just be skipping the characters within the string itself since they're not actually a part of the brackets? 🤔 

## Support Info

```
- ST ver.: 3189
- Platform: osx
- Arch: x64
- Plugin ver.: 2.27.6
- Install via PC: True
- mdpopups ver.: 3.4.0
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

**Comment by facelessuser** [comment]
What syntax file are you using? BH uses scopes to avoid strings, if the string scope isn't used for strings then it won't avoid strings. This is why plain text isn't enabled by default for BH. We can't get proper context in plain text without parsing the whole file, which is too expensive.

**Comment by facelessuser** [comment]
Never mind, I see you said JSON syntax. I'll to it out, but you screenshot doesn't look highlighted by JSON.

**Comment by acheronfail** [comment]
I agree my syntax theme is confusing, here it is with Marinara: 
![bh](https://user-images.githubusercontent.com/34289614/52535118-b2d69200-2d9e-11e9-9ac2-2bc1096f2b23.gif)

It's the default JSON syntax.

**Comment by acheronfail** [comment]
I've mapped this command to a hotkey:

```json
{
  "args": {
    "lines": true, 
    "no_block_mode": null, 
    "no_outside_adj": null, 
    "plugin": {
      "args": {
        "select": "left"
      }, 
      "command": "bh_modules.bracketselect", 
      "type": [
        "__all__"
      ]
    }
  }, 
  "command": "bh_key", 
  "keys": [
    "alt+["
  ]
}
```

**Comment by acheronfail** [comment]
Also, if it helps, these are the scopes in that string:

<img width="426" alt="screen shot 2019-02-11 at 01 48 37" src="https://user-images.githubusercontent.com/34289614/52535165-355f5180-2d9f-11e9-9595-42bf11279f36.png">

**Comment by facelessuser** [comment]
I cannot reproduce this

![screenshot 2019-02-10 07 47 26](https://user-images.githubusercontent.com/1055125/52535163-4f018a00-2d08-11e9-956a-a6cf0fe78ac6.png)

Are you sure you don't have some custom BH rules?

**Comment by facelessuser** [comment]
If you want me to test your specific code, please post it as something I can copy & paste.

**Comment by acheronfail** [comment]
> If you want me to test your specific code, please post it as something I can copy & paste.

I think you've reproduced it fine enough, since the screenshot you posted above doesn't work on my machine.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/34289614/52535179-6ccdfe00-2d9f-11e9-9625-2909d9af42c7.png">

I think it might actually be a custom rule, let me verify.

**Comment by acheronfail** [comment]
Ah yep. It was my custom rules. 🤦‍♂️ 

Appreciate the quick response and help, though!
Sorry for wasting your time!

**Comment by facelessuser** [comment]
No problem.
