### ISSUE TITLE
Error trying to parse settings in bh_core.sublime-settings

### ISSUE THREAD

**Issue by jedrekdomanski** [facelessuser/BracketHighlighter#520]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description

I used the settings provided in the documentation http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style
to overwrite the color settings but it's giving me an error:
`Error trying to parse settings :Unexpected trailing characters in Packages/User/bh_core.sublime-settings` when I save the file. Any idea why?

![image](https://user-images.githubusercontent.com/5911945/56827492-49bfd000-685f-11e9-8b97-69de9a1cdf47.png)

... what is the issue / request ?

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

...

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

## Steps to Reproduce Issue

1. First step...
2. Second step...
3. Third step...

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
You have not provided the information that the template asked for. I'm not sure what Sublime version you are on, what version of BracketHighlighter you have.  In addition, you've posted an error about parsing the settings file, but you haven't provided the settings you used. Unfortunately, without more information, I cannot offer any support.

My best guess is you entered malformed data in the settings file 🤷‍♂ .

**Comment by jedrekdomanski** [comment]
I am using Sublime Text 3, the latest version of BH I suppose since I've just installed it and the settings are from the documentation. I am not sure what might be wrong in this JSON file.

```json
    "user_bracket_styles": {
        "default": {
            "icon": "dot",
            "color": "region.yellowish brackethighlighter.default",
            "style": "underline"
        },
        "unmatched": {
            "icon": "question",
            "color": "region.redish",
            "style": "outline"
        },
        "curly": {
            "icon": "curly_bracket",
        }
    }
```

**Comment by jedrekdomanski** [comment]
I think I know what the problem was, the config is not wrapped around {} which makes it an invalid JSON format.

**Comment by facelessuser** [comment]
Yeah, the `user_bracket_styles ` key needs to be part of a dictionary or it is just a stray string.
