### ISSUE TITLE
Help to support Naomi?

### ISSUE THREAD

**Issue by kud** [facelessuser/BracketHighlighter#532]
Hey,

Could you help me to support Naomi (https://github.com/borela/naomi) by any chance? for each type of settings.

The tmLanguage and the scopes are differents that "classic" sublime text syntax like

`JavaScript (Naomi)` or `HTML 5 (Naomi)` or `source.jsx meta.tag.other.component.html.jsx.jsx1 entity.name.tag.component.jsx.jsx1`

Thank you!

**Comment by r-stein** [comment]
Can you please be a little bit more specific about the support you want? From looking at the package it mostly provides syntax definitions and a few commands.

**Comment by facelessuser** [comment]
In general, if the "custom" languages are similar enough to what is already supported, you simply need to add the languages in the appropriate rules.  I'd check out the documentation for more info. I notice some references to JSX, and I have not added any support for JSX. If you add support for languages using JSX, you may notice quirks as JSX syntax is not true HTML syntax.
