### ISSUE TITLE
A Fix For Documentation: Colour Customization

### ISSUE THREAD

**Issue by iansebryk** [facelessuser/BracketHighlighter#541]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description

in your documentation on [Specifying Custom Colors in Schemes](https://facelessuser.github.io/BracketHighlighter/customize/#example-specifying-custom-colors-in-schemes), it reads:

> In Sublime 3152+, you can use the new color format to create an override color scheme instead of directly editing your color scheme. To append your new rule (or override an existing rule) you can create a .sublime-color-scheme file in your Packages/User folder.

this is actually semi-accurate and incomplete; likely the cause of much frustration!  what should be added is that the `.sublime-color-scheme` file NEEDS TO BE PREFIXED WITH YOUR ACTIVE THEME NAME, thusly:  **`Monokai.sublime-color-scheme`**.

currently i'm finding many are creating the file `.sublime-color-scheme` and wonder why it isn't working, myself included.  frustrated at these attempts, you're likely bombarded with requests for help on this; i know i've asked myself a few times and have spent HOURS trying to figure out why it wasn't working.  it wasn't until i combed through a related post earlier today that i twigged to the fact that the file was _incompletely_ named.  once i realized that, i re-read the documentation again and found that nowhere does it mention this critical requirement.  once applied, of course everything works just fine.

a modification of the documentation such as the following would probably save everyone a lot of headache.
>In Sublime 3152+, you can use the new color format to create an override color scheme instead of directly editing your color scheme. To append your new rule (or override an existing rule) you can create a *\<theme-name\>.sublime-color-scheme* file in your Packages/User folder.

anyway.  in the end, i absolutely love the plugin and appreciate the amount of work gone in to making it the staple that it is.  i hope this helps to make it more enjoyable for those who use it.

## Support Info

- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.7
- Install via PC: True
- mdpopups ver.: 3.5.0
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. NOTHING
2. REQUIRED
3. HERE

**Comment by facelessuser** [comment]
> currently i'm finding many are creating the file .sublime-color-scheme and wonder why it isn't working, myself included.

🤦‍♂ This is fair. I usually make these comments, because I know what it means, but not everyone else does.

Pull requests are always welcome, but if not, I'll get to it when I have a moment.

**Comment by iansebryk** [comment]
i hear ya.  writing manuals is a tiresome thing.  yours is, honestly, amazing.  if i can scrape some time next week, i'll pull and fix for you.  been so busy lately this colour thing had to be addressed.  the big white blob was driving me batty.  :)  turned out my dementia about it yeilded good fruit this time.
