### ISSUE TITLE
Bug found using `content_highlight_bar`

### ISSUE THREAD

**Issue by erenard** [facelessuser/BracketHighlighter#542]
## Description
Bug found using `"content_highlight_bar": true,`:

When the line don't use the same tabulations types:
![image](https://user-images.githubusercontent.com/128057/74811599-1bc9e180-52f2-11ea-8e10-a4d17b9a2726.png)

The vertical bar highlighting is faulty:
![image](https://user-images.githubusercontent.com/128057/74811686-4e73da00-52f2-11ea-9174-7b3122859b3e.png)

The vertical line could be correctly drawn since the fault happen in the spaced tabulation line.

## Support Info
- ST ver.: 3211
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.7
- Install via PC: True
- mdpopups ver.: 3.5.0
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. Have different kind of tabulations, use a new sublime-project file for exemple
2. Activate content_highlight_bar

**Comment by facelessuser** [comment]
Yeah, this is a bug. I'll have to refresh on how we calculate and insert those regions. It should be fixable, but I'll have to review how we insert this.

@gir-bot remove S: triage
@gir-bot add T: bug, S: confirmed

**Comment by facelessuser** [comment]
Bug has been identified and a fix issued.
