### ISSUE TITLE
homepage redirects to HexViewer

### ISSUE THREAD

**Issue by jabbalaci** [facelessuser/BracketHighlighter#543]
When visiting https://facelessuser.github.io/BracketHighlighter/ , I get the page of HexViewer, see https://i.imgur.com/qF4N2eF.png .

**Comment by facelessuser** [comment]
Whoops! Probably a copy paste thing.

**Comment by facelessuser** [comment]
Was a copy paste issue with the deploy script, it is now fixed.

@gir-bot remove S: triage
@gir-bot add T: bug, S: confirmed
