### ISSUE TITLE
Lua - wrong highlighting

### ISSUE THREAD

**Issue by sfmict** [facelessuser/BracketHighlighter#548]
![123](https://user-images.githubusercontent.com/15520489/76345886-2ab21b80-6315-11ea-89a2-734c57593922.png)
```lua
if a < .5 then
	asd
else
	asd
end
```

**Comment by facelessuser** [comment]
I am no expert in lua, I'm am open to pull requests and or detailed suggestions as to why the current Lua highlighting is not working and how we can move forward.

@gir-bot remove S: triage
@gir-bot add T: bug, S: more-info-needed

**Comment by sfmict** [comment]
Between “if” and “then” if the number starts with “.” highlighting does not work correctly.

**Comment by facelessuser** [comment]
Your syntax highlighter looks wrong. That may be why.

**Comment by facelessuser** [comment]
Works for me in Sublime's default Lua highlighter. I'd use Sublime's highighter:

![lua](https://user-images.githubusercontent.com/1055125/76349266-498dbf00-62cf-11ea-9284-c6b83bd0b620.png)

@gir-bot remove T: bug, S: more-info-needed
@gir-bot add T: support

**Comment by sfmict** [comment]
![123](https://user-images.githubusercontent.com/15520489/76350130-40770f00-631c-11ea-8ea4-cb8400b496b6.png)
Downloaded and launched a new sublime (portable)

**Comment by facelessuser** [comment]
What version of Sublime are you using?  I don't use Lua, so I don't have any special Lua packages installed.

**Comment by sfmict** [comment]
sublime version 3.2.2 build 3211

**Comment by facelessuser** [comment]
This is why the issue template asks you to provide version info. In the future, please provide this information up front.

Sublime 3 has a broken Lua syntax. I am currently using Sublime 4 dev release. So this issue will be fixed there. There is nothing I can do except say maybe try Sublime Text 4 dev release :man_shrugging: . Or try and fix the Lua syntax locally. BH needs the context from a correctly highlighted Lua file.

**Comment by sfmict** [comment]
Thanks for answer, I'll try version 4.
