### ISSUE TITLE
Remove references to whitelist/blacklist

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/BracketHighlighter#553]
The request is coming, so might as well get ahead of it 🙂.

We will probably go with what has been mentioned elsewhere and use `allowlist` and `blocklist`. We could use something like `denylist` or `disallowlist` as alternatives, but one of these options should replace `blacklist`.

**Comment by Narretz** [comment]
This should have been in a major release, or at least highlighted (heh) much bigger in the release notes, as this makes Brackethighlighter stop working if you use the options in the User Settings.

**Comment by facelessuser** [comment]
True. Well, what's done is done 🤷‍♂️.
