### ISSUE TITLE
PHP opening and closing tags do not get highlighted

### ISSUE THREAD

**Issue by jbslettebak** [facelessuser/BracketHighlighter#560]
## Description

How can I make it so that opening and closing PHP tags get matched and highlighted? Currently, only the curly braces within a PHP expression get highlighted, but not the opening and closing tags themselves. 

## Support Info

- ST ver.: 3207
- Platform: osx
- Arch: x64
- Plugin ver.: 2.28.0
- Install via PC: True
- mdpopups ver.: 3.7.1
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

- See attached code. None of the 5 opening or closing PHP tags are being matched/highlighted. Any help would be greatly appreciated. 

    <?php
    $fiesta_header = get_field('fiesta_favorites_header');
    if ( $fiesta_header ) { ?>
                                    <tr class="subheader-row">
                                        <td class="subheader specialty-sandwich-subheader"><?php echo $fiesta_header; ?></td>
                                    </tr>
                                    <tr>
    <?php } 
    if( have_rows('fiesta_favorites') ):
        while ( have_rows('fiesta_favorites') ) : the_row(); ?>
                                        <td class="fiesta-favorites-name item-name"><?php the_sub_field('fiesta_favorite_item'); ?></td>
                                        <td class="fiesta-favorites-price item-price"><?php the_sub_field('fiesta_favorite_price'); ?></td>
                                    </tr>
    <?php endwhile;
    else :
        // no rows found
    endif; ?>

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
What syntax are you using? The current rule matches PHP in `HTML` and `HTML 5`:

```js
        // PHP Angle
        {
            "name": "php_angle",
            "open": "(<\\?)(?:php)?",
            "close": "(\\?>)",
            "style": "angle",
            "scope_exclude": ["string", "comment", "keyword.operator"],
            "language_filter": "allowlist",
            "language_list": ["HTML", "HTML 5"],
            "enabled": true
        },
```

I assume you want this matching in `PHP` syntax?

To be honest, I probably didn't notice this as I disable PHP angle highlighting locally. PHP and HTML together often break each other when using complex nesting of one in the other. BH handles them together when in reality PHP is handled in real life separate from the content it is inserted in. TBH, it should probably highlight PHP starts and end only when in PHP syntax and not highlight them HTML syntax.

I may tweak this for the next release, but you can always use an override and enable them in whichever syntax you wish.

**Comment by facelessuser** [comment]
I realize why I don't enable `PHP` angles in PHP files. It conflicts with PHP keywords such as `for` and `endfor` etc. It is more useful having those highlight than `<?php` and `?>`. This is subjective though and can be configured in the settings if you prefer something different.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by jbslettebak** [comment]
That all makes sense. I'll try to configure it and see what kind of results I get. Thanks very much for the response.
