### ISSUE TITLE
The closing round bracket matching exclusion in Case patterns is broken in Bash / Bourne Again Shell.

### ISSUE THREAD

**Issue by vpr111** [facelessuser/BracketHighlighter#567]
## Description
The closing round bracket exclusion in Case pattern doesn't work and breaks the whole scope,
it doesn't matter if there are any other conditional statements preceding or not.

.. No other 3rd party syntax highlighting packages installed.

## Support Info
- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 2.28.1
- Install via PC: True
- mdpopups ver.: 3.7.2
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue
It takes any Case statement form to show the problem, the most simple is ST3's default form:
```
case word in
	pattern ) #< Problem in this round bracket
		;;
esac
```

**Comment by vpr111** [comment]
Appearently the original syntax had been changed, you may merge my pull request here #568

**Comment by facelessuser** [comment]
Hmm, I need to test this in ST3, I'm not seeing this issue in ST4.

**Comment by facelessuser** [comment]
I've confirmed that this issue is ST3 specific and does not occur in ST4, so with that said, we'll need something that works on both.
