### ISSUE TITLE
Can't match tags when there is PHP code within an HTML tag

### ISSUE THREAD

**Issue by MontyHu** [facelessuser/BracketHighlighter#570]
Hi, thanks for making this package for Sublime Text, it's a great and very useful add-on. 

I'm experiencing a problem with highlighting matching tags when there is a PHP snippet placed within an HTML form element, like this: 

	<div>
	  <select name="select" id="MySelect">
	    <option <? if ($obj->option('this_option') == '1') echo "selected" ?>>1</option>
	  </select>
	</div>

When I place my cursor on the first `<div>` tag, a question mark appears next to the line number. 

![Screen Shot 2020-10-12 at 10 10 29 AM](https://user-images.githubusercontent.com/4706620/95773456-5b737e00-0c73-11eb-92ab-3a703d033f5b.png)

But if I place my cursor on the closing div, the tags are able to be matched in that direction for some reason.

![Screen Shot 2020-10-12 at 10 10 45 AM](https://user-images.githubusercontent.com/4706620/95773437-544c7000-0c73-11eb-88a1-c5ce5022dae1.png)

The same happens with the `<select>` tag, it won't match on the first one, but will on the closing tag. 

![Screen Shot 2020-10-12 at 10 27 21 AM](https://user-images.githubusercontent.com/4706620/95774688-b6a67000-0c75-11eb-8f61-aac189371f20.png)

The document type is set to PHP in Sublime Text. If the PHP code snippet within the option tag is removed, then the tags are matched when I place my cursor on the first `<div>`. This happens whether the PHP code snippet begins with `<?` or `<?php`. 

It seems to be the double `>>` brackets at the end of the PHP code snippet along with the closing HTML tag bracket that is tripping up the tag matching in one direction because even an empty PHP snippet causes the same issue: 

	<div>
	  <select name="select" id="MySelect">
	    <option <?php ?>>1</option>
	  </select>
	</div>

Here's the support info for my setup: 

- ST ver.: 3211
- Platform: osx
- Arch: x64
- Plugin ver.: 2.28.1
- Install via PC: True
- mdpopups ver.: 3.7.3
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

Maybe this isn't a bug and can be fixed by changing a setting in BracketHighlighter, but I'm just not sure what setting should be changed to fix this.

**Comment by facelessuser** [comment]
Yup, this is known and expected. As we match a whole and valid tag, PHP syntax messes that up. To be honest, before HTML is parsed, PHP should be parsed, but we can't really do that.

One way to get around this would be to no longer focus on HTML syntax, and just focus on scopes provided by Sublime's syntax highlighter, but those scopes are not sufficient as we'd need to know start tag name from end tag name, and that info is not contained in scopes.

So, yes, PHP and HTML together can mess up tag highlighting. It's unfortunate, but with the current design, that's just the way it is.

@gir-bot remove S: triage
@gir-bot add T: support, S: wontfix
