### ISSUE TITLE
Property  "align_content_highlight_bar" gaps in the line

### ISSUE THREAD

**Issue by olegopro** [facelessuser/BracketHighlighter#571]
Hello. If enable option  "align_content_highlight_bar" = true. I have gaps in the line

![Image alt](https://raw.githubusercontent.com/olegopro/olegopro.github.io/main/brackets.png)

ST ver.: 3211
Platform: osx
Plugin ver.: 2.28.1

**Comment by facelessuser** [comment]
That is a known limitation of the Sublime API. There is nothing we can do about that unless Sublime added some API support for us to use to draw lines. Until then, the best you get is us abusing regions to pull off a fake line.

**Comment by facelessuser** [comment]
@gir-bot add S: wontfix
