### ISSUE TITLE
Underline glitch

### ISSUE THREAD

**Issue by ivanddm** [facelessuser/BracketHighlighter#573]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description

In languages such as Lua or Ruby, the underlines cause some weird vertical lines in between letters. Not sure if this is due to brackethighlighter or some ST4 graphic card related issue. The same happens in a 2019 Mac Mini, as well as a 2013 iMac, both running Catalina MacOS (latest version):

<img width="405" alt="Screen Shot 2020-11-08 at 4 09 50 PM" src="https://user-images.githubusercontent.com/20104703/98465970-9ff42a00-21dd-11eb-8b7d-d65650b6bb22.png">

<img width="409" alt="Screen Shot 2020-11-08 at 4 11 00 PM" src="https://user-images.githubusercontent.com/20104703/98465971-a2ef1a80-21dd-11eb-821e-2e1923ab56d2.png">

## Support Info

- ST ver.: 4090
- Platform: osx
- Arch: x64
- Plugin ver.: 2.28.1
- Install via PC: True
- mdpopups ver.: 3.7.5
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by trongthanh** [comment]
Second this. Here same issue with HTML syntax:
![image](https://user-images.githubusercontent.com/234226/98505987-17cd5d80-228d-11eb-9f41-05758dbc2684.png)

And it's likely due to Sublime Text 4 compatibility. I've just seen this issue since I switched to ST4.

**Comment by facelessuser** [comment]
This is a Sublime Text glitch, not a BracketHighlighter glitch.

**Comment by trongthanh** [comment]
Here's how the same code snippet looks like if I disable this plugin on ST4.
![image](https://user-images.githubusercontent.com/234226/98519469-5ff77a80-22a3-11eb-94f8-5dda494f9039.png)

So I guess this plugin is not completely innocent.

**Comment by facelessuser** [comment]
> So I guess this plugin is not completely innocent.

I disagree, we are completely innocent. We use the Sublime API to draw the underlines. Sublime is messing up with the rendering. We do not control the rendering, we simply ask Sublime to draw the regions.

**Comment by facelessuser** [comment]
Additionally, it only happens on very few systems. I suspect it may be related to a combination of things, like specific fonts etc. I'm pretty sure they're is already a Sublime issue filled for this as I remember it being discussed on the discord server.

**Comment by trongthanh** [comment]
Thanks for the explanation. A quick search from issues tracker of ST resulted at this ticket: https://github.com/sublimehq/sublime_text/issues/3721 I'll mention it here so others can follow and get updated.

**Comment by ivanddm** [comment]
Thanks, @facelessuser, and @trongthanh for explaining this. Feel free to close this issue @facelessuser if you consider that this is an ST4 issue and not brackethighlighter's.

**Comment by facelessuser** [comment]
You may find that the style `thin_underline` doesn't have this issue. The default thick underline accomplishes this with an old method to create an underline that pre-dates the addition of Sublime's current ability to have underline regions with the thinner style. We kept around the old thick underline as some people prefer a more easy to see, thick underline style.

As this is currently an upstream issue, I will close.

@gir-bot remove S: triage
@gir-bot add S: wontfix
