### ISSUE TITLE
LaTex bracket style broken

### ISSUE THREAD

**Issue by LDAP** [facelessuser/BracketHighlighter#574]
## Description
Bracket style is broken
![grafik](https://user-images.githubusercontent.com/8215084/99154477-5bbacb00-26b0-11eb-84e3-58224bb37baf.png)
> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info
- ST ver.: 4090
- Platform: windows
- Arch: x64
- Plugin ver.: 2.28.1
- Install via PC: True
- mdpopups ver.: 3.7.5
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1
...

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

## Steps to Reproduce Issue

1. Install Bracket Highlighter 
2. Open Latex sheet

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
This is not a BracketHighlighter issue, but a Sublime issue. Please see duplicate for more info: https://github.com/facelessuser/BracketHighlighter/issues/573.
