### ISSUE TITLE
"matching bracket could not be found" when using PHP shorthand fn() notation

### ISSUE THREAD

**Issue by LennartHengstmengel** [facelessuser/BracketHighlighter#577]
## Description

I get an error "matching bracket could not be found" in PHP code for all brackets/parentheses enclosing a fragment that contains a shorthand `fn()` function notation. The suggestion to match without threshold has no effect. Bracket matching works fine in other cases, and with the traditional `function () {}` notation. 

## Support Info

- ST ver.: 4098
- Platform: osx
- Arch: x64
- Plugin ver.: 2.29.0
- Install via PC: True
- mdpopups ver.: 3.7.5
- backrefs ver.: 5.0
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

See this example code that reproduces the issue for me:

```php
// these square brackets give a "matching bracket not found" error
$array1 = [
    fn () => 1
];

// these brackets do not give an error
$array2 = [
    function () {
        return 1;
    }
];
```
Screenshot:

![Screenshot 2021-03-04 at 15 30 29](https://user-images.githubusercontent.com/1075085/109978829-8fbd0900-7cfe-11eb-808b-95ba5a148a7a.png)

**Comment by facelessuser** [comment]
People keep changing the PHP syntax, so they keep breaking it:

Consider the current angle rule (truncated). Notice how many times we've tried to exclude PHP accessor:

```js
        // Angle
        {
            "name": "angle",
            "open": "(<)(?=[^?%]|$)",
            "close": "(?:(?<=[^?%])|(?<=^))(>)",
            "style": "angle",
            "scope_exclude": [
                "string",
                "comment",
                "keyword.operator",
                "source.ruby.rails.embedded.html",
                "source.ruby.embedded.html",
                "storage.type.function.arrow.js",
                "punctuation.accessor.php",      //<---------------- Once
                "punctuation.accessor.arrow.php",//<---------------- Twice
                "source.php meta.embedded.html punctuation.section.embedded.begin.php",
                "source.php meta.embedded.js punctuation.section.embedded.begin.php",
                "source.php meta.embedded.css punctuation.section.embedded.begin.php"
            ],
```

So, this needs to be updated with yet another new scope:

```js
        // Angle
        {
            "name": "angle",
            "open": "(<)(?=[^?%]|$)",
            "close": "(?:(?<=[^?%])|(?<=^))(>)",
            "style": "angle",
            "scope_exclude": [
                "string",
                "comment",
                "keyword.operator",
                "source.ruby.rails.embedded.html",
                "source.ruby.embedded.html",
                "storage.type.function.arrow.js",
                "punctuation.accessor.php",
                "punctuation.accessor.arrow.php",
                "punctuation.definition.arrow-function.php", //<---------- Yet another added
                "source.php meta.embedded.html punctuation.section.embedded.begin.php",
                "source.php meta.embedded.js punctuation.section.embedded.begin.php",
                "source.php meta.embedded.css punctuation.section.embedded.begin.php"
            ],
```

<img width="331" alt="Screen Shot 2021-03-04 at 8 57 19 AM" src="https://user-images.githubusercontent.com/1055125/109991574-a98f2980-7cc7-11eb-8b55-02ef30f7d0cf.png">

@gir-bot remove S: triage
@gir-bot add T: bug

**Comment by facelessuser** [comment]
Fixed by https://github.com/facelessuser/BracketHighlighter/commit/fdc302255e0ebf87580e1d1e63193df3525fbb48
