### ISSUE TITLE
Matching issue in SCSS syntax inside a Vue file

### ISSUE THREAD

**Issue by h0rn3z0r** [facelessuser/BracketHighlighter#579]
## Description

I have enabled Vue syntax highlighting by extending the html syntax. But there is a problem with some specific SCSS code which is highlighted correctly inside plain .scss file, but fails inside Vue's style block (attachment below). Most likely some additional configuration is needed and here I am asking for help. 

![vue](https://user-images.githubusercontent.com/8987403/111083000-64b39000-851c-11eb-9190-bccff7902552.png)

<details>
  <summary>Copy paste</summary>

```scss
// Test.vue
<style lang="scss">
.child {
    :not(.parent) > & {
        margin-left: 0;
    }
}
</style>
```
</details>

## Support Info

- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 2.29.1
- Install via PC: True
- mdpopups ver.: 4.0.4
- backrefs ver.: 5.0
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

<details>
  <summary>bh_core.sublime-settings</summary>

```json
{
    "search_threshold": 15000,
    "user_brackets": [{
        "name": "angle",
        "language_list": [
            "HTML",
            "HTML 5",
            "XML",
            "PHP",
            "HTML (Rails)",
            "HTML (Jinja Templates)",
            "HTML (Jinja2)",
            "HTML (Twig)",
            "HTML (Django)",
            "HTML+CFML",
            "ColdFusion",
            "ColdFusionCFC",
            "laravel-blade",
            "blade",
            "Vue Component",
            "Handlebars",
            "AngularJS",
            "Java Server Pages (JSP)"
        ],
        "scope_exclude": [
            "string",
            "comment",
            "keyword.operator",
            "source.ruby.rails.embedded.html",
            "source.ruby.embedded.html",
            "storage.type.function.arrow.js",
            "storage.type.function.arrow.ts",
            "punctuation.accessor.php",
            "punctuation.accessor.arrow.php",
            "source.php meta.embedded.html punctuation.section.embedded.begin.php",
            "source.php meta.embedded.js punctuation.section.embedded.begin.php",
            "source.php meta.embedded.css punctuation.section.embedded.begin.php",
            "text.html.vue source.scss.embedded.html meta.selector.css punctuation.separator.combinator.css"
        ],
    }],
}
```
</details>

<details>
  <summary>bh_tag.sublime-settings</summary>

```json
{
    "tag_mode": [
        {
            "mode": "html",
            "syntax": [
                "HTML",
                "HTML 5",
                "PHP",
                "HTML (Jinja Templates)",
                "HTML (Jinja2)",
                "HTML (Rails)",
                "HTML (Twig)",
                "HTML (Django)",
                "laravel-blade",
                "blade",
                "Handlebars",
                "AngularJS",
                "Java Server Pages (JSP)",
                "Vue Component"
            ]
        }
    ],
    "self_closing_tag_patterns": {
        "html": "[\\w:\\.\\-]+",
    },
    "attributes": {
        "html": "[\\w:@#][-\\w()\\[\\]\\d:.]*(?:\\s*=\\s*(?:\"[^\"]*\"|'[^']*'|[^\\s\"'`=<>]+))?",
    },
}
```
</details>

**Comment by facelessuser** [comment]
@h0rn3z0r, you can probably ignore the embedded language in the script block. You can get the scope by placing the cursor between the script tags and pressing <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>.

That should get the full scope, you don't need to use the full scope, probably just the part that specifies `embedded.scss.blah.blah`. You can add that to the `scope_exclude` on the `angle` rule and that will probably ignore the `>` in your SCSS which is causing things to go south. I don't know what Vue package you are using exactly, but I'm pretty sure that is what your issue is.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by h0rn3z0r** [comment]
@facelessuser, thanks a lot, that was definitely the reason!
Basically, BH needs these two lines to treat CSS correctly inside Vue files:
```json
        "scope_exclude": [
            "...",
            "text.html.vue source.css.embedded.html",
            "text.html.vue source.scss.embedded.html",
        ],
```

**Comment by facelessuser** [comment]
I thought CSS scoped `>` as something that was already ignored, but if not, then yes, you have to exclude embedded CSS as well.

Glad you figured it out.
