### ISSUE TITLE
Doesn't work for Bikeshed files

### ISSUE THREAD

**Issue by kvark** [facelessuser/BracketHighlighter#580]
## Description

I'm not seeing any effect of the plugin on ".bs" files (see https://github.com/tabatkins/bikeshed).
Note: it contains both markdown-like brackets, and HTML-like brackets.

Unmatched brackets are not highlighted, even upon saving the file.

Example file: https://github.com/gpuweb/gpuweb/blob/main/spec/index.bs

Note: I do see the plugin working for other files (like ".rs"), so it's installed properly.
Using Sublime Text build 4099.

## Support Info

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

There is no "Support Info" under "BracketHighlighter". There are only options for changing settings in here.

## Steps to Reproduce Issue

1. Install "BracketHighlighter" on ST4
2. Open a bikeshed file with misplaced brackets

<img width="220" alt="Screen Shot 2021-03-26 at 12 09 10" src="https://user-images.githubusercontent.com/107301/112660700-195a8500-8e2c-11eb-98e9-8b7b860dbd91.png">

**Comment by facelessuser** [comment]
>There is no "Support Info" under "BracketHighlighter". There are only options for changing settings in here.

This is not True.

Here is mine:

```
- ST ver.: 4099
- Platform: osx
- Arch: x64
- Plugin ver.: 2.29.1
- Install via PC: True
- mdpopups ver.: 4.1.1
- backrefs ver.: 5.0
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1
```

As far as Bikeshed files:

1. I don't use bikeshed, so I know nothing about bikeshed. I would need someone familiar with bikeshed to spend some time adding support as I do not know the nuances of this language.
2. You're image is showing bracket highlighting. Is that built-in Sublime highlighting? I can't tell from your image.
3. BH doesn't highlight in plain text, so if you don't have a syntax highlighter for `.bs` files, it probably defaults to plain text, and no brackets are highlighted in plain text. If you do have a syntax highlighter, then basic brackets should work, but nothing beyond that.

**Comment by kvark** [comment]
Ok, interesting, I don't know how I got into this repository, but this isn't the plugin I'm interested in.
Sorry for bothering you!
