### ISSUE TITLE
Any chance of translating this for VSCode?

### ISSUE THREAD

**Issue by mscwilson** [facelessuser/BracketHighlighter#581]
I've started to use VSCode because I'm finding everything easier there than in Sublime. The only thing holding me back from switching over completely is this plugin! The closest available one there is [Bracket Pair Colorizer 2](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2) which doesn't handle the gutter icons well at all.  

Would you ever consider translating it for VSCode? Extensions there are in JavaScript.  

Thanks!

**Comment by facelessuser** [comment]
@mscwilson Thanks for your request! Unfortunately, I do not use VSCode, or rather, I rarely use it. My main editor is still Sublime, so there is little payoff for me personally to invest the time to create and then have to maintain such a package.

I'm flattered that some people miss BracketHighlighter when migrating to VSCode, or wish it existed on VSCode, but I simply haven't the time to invest porting over to other editors. If I ever switch to VSCode, you may see BH again, but I do not see that outcome in the foreseeable future.

**Comment by mscwilson** [comment]
That makes sense, fair enough. Thanks for taking the time to reply, and thanks again for the great plugin(s).
