### ISSUE TITLE
After installation, missing all packages in Sublime Text 3 

### ISSUE THREAD

**Issue by thistlillo** [facelessuser/BracketHighlighter#584]
I installed Sublime Text 3 version 3.2.2 Build 3211 on Windows 10 Pro and installed some packages, like Package Control, remote ssh, ...

Then I installed BracketHighlighter. After installing BracketHighlighter a dialog suggested to restart Sublime Text 3.
I did it and a new window came up, with some of the previous ones still open.

The new window has NO packages installed, not even package control.
The 'old' windows had all the packages previously installed.

After closing all the windows and re-opening Sublime Text there are no packages installed.

I don't know if this is a bug of BracketHighlighter or of ST3, but it did happened after installing BracketHighlighter.

**Comment by facelessuser** [comment]
> The new window has NO packages installed, not even package control.

Packages are not installed per window, so I don't understand what is being suggested here.

Additionally, BracketHighlighter doesn't control or affect package installation (Package Control does), so BracketHighlighter can't be responsible for any package changes. If anything happened during BracketHighlighter installation, it is purely coincidental.

I'd check your Package Control disabled packages and see if Package Control had disabled some packages during the upgrade and, for whatever reason, didn't re-enable them.

If Package Control isn't installed, I don't know what is going on :shrug:.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
Closing as there has been no communication since making suggestions.
