### ISSUE TITLE
Ctrl+Shift+B doesn’t work

### ISSUE THREAD

**Issue by stephen147** [facelessuser/BracketHighlighter#585]
I found this thread on the ST forum: https://forum.sublimetext.com/t/ctrl-shift-b-doesnt-working-on-ubuntu-12-10/8166/2

This was causing me an issue also and your reply in that thread helped.

After disabling [BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter)  the command worked again.

Has this gotten changed at all? That thread is old now.

Thanks.

ED:
This is strange. I disabled BracketHighlighter and renabled it and it appears to be working again.

I'll leave this open if you have any comments but for now, at least it seems like it working again.

**Comment by facelessuser** [comment]
That was a super long time ago. We no longer ship any default shortcuts. Users must define shortcuts if they wish to have one associated with BH.

@gir-bot remove S: triage
@gir-bot add S: wontfix
