### ISSUE TITLE
Unable to match the corresponding bracket if there is an inner arrow function using JavaScript in HTML

### ISSUE THREAD

**Issue by matcls** [facelessuser/BracketHighlighter#587]
## Description
Using JavaScript in HTML, if there is an arrow function between the brackets BH does not find the respective bracket.

The image shows first without the arrow function and then using the arrow function.

![BH Arrow Function Brackets](https://user-images.githubusercontent.com/60364655/123496749-3ea78c80-d5ef-11eb-9231-cdebdf345953.png)

- BH matches brackets correctly using JavaScript syntax and arrow functions
- Default matching in Sublime Text match the brackets correctly
## Support Info

...
- ST ver.: 4109
- Platform: windows
- Arch: x64
- Plugin ver.: 2.29.1
- Install via PC: True
- mdpopups ver.: 4.1.2
- backrefs ver.: 5.0
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. Copy/Paste the HTML snippet below
2. Place the caret in the first bracket.
3. BH does not find the matching bracket

```HTML
<html lang="en" dir="ltr">
<body>
    <script type="application/javascript">
        if (info.readyState === 4 && info.status === 200) {
            data.forEach((post) => {
                addPostRow(post);
            });
        }
    </script>
</body>
```

**Comment by facelessuser** [comment]
This was brought up recently and is due to a recurrent change in JavaScript scoping in the syntax highlighting.

I had a fix, but forgot to commit it 🙃. I will try and get the fix in the weekend.
