### ISSUE TITLE
LaTeX commands in HTML

### ISSUE THREAD

**Issue by benthien** [facelessuser/BracketHighlighter#588]
## Description

I have web pages that contain equations. The equations are entered into the html file using LaTeX commands that are later processed by MathJax. I wanted to be able to color highlight both the html and the LaTeX code. I created a syntax file HTML(MathJax).sublime-syntax shown below

%YAML 1.2
---
name: HTML (MathJax)
scope: text.html.mathjax

file_extensions:
  - html
  - htm
  - shtml
  - xhtml

contexts:
  main:
    - include: scope:text.html.basic
    - include: scope:text.tex.latex

Using this syntax I was able to modify the color scheme to color highlight both the html and the LaTeX code. However under this syntax BracketHighlighter no longer highlighted matching html tags. I tried adding HTML (MathJax) to the allowed syntaxes under html tag mode, but this didn't work. It is interesting that emmet was able to find matching tags in this syntax. I am very new at working with syntaxes, so any help would be appreciated.

## Support Info

- ST ver.: 4107
- Platform: windows
- Arch: x64
- Plugin ver.: 2.29.1
- Install via PC: True
- mdpopups ver.: 4.1.2
- backrefs ver.: 5.0
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. Place the syntax file HTML(MathJax).sublime-syntax described above in Packages/User
2. Add HTML (MathJax)  to syntax list under "mode": "html" under "user_tag_mode" in bh_tag.sublime-settings
3. Open html file containing equations in the HTML (MathJax) syntax
4. Place cursor on any html tag and observe that the tag and its matching closing tag are not highlighted

**Comment by benthien** [comment]
I should have mentioned that I am only interested in highlighting html tags. I don't need any highlighting in the Latex code.

**Comment by facelessuser** [comment]
Sorry that it took me a bit to get to this.

So, you probably need to add your custom syntax language to the tags rule: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L444.

You probably also need to add your syntax to the Tags extension's config as well: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_tag.sublime-settings#L31.

You may or may not have to tweak some other settings. I know nothing of incompatibilities that may or may not exist in your special `HTML (MathJax)` syntax.

**Comment by facelessuser** [comment]
You can access both the above settings files via the menu `Preferences -> Package Settings -> BracketHighlighter`. The [documentation](https://facelessuser.github.io/BracketHighlighter/) goes into detail as to what these settings do and how to properly override them in your User settings.

**Comment by benthien** [comment]
Thank you. Your suggestion worked. I ran into one problem when I first tried to make the changes. In the core settings I used user_brackets to only make changes to the angle settings. That worked fine. However, I tried using user_tag_mode in the user tag settings to only modify html mode. That didn't work, I needed to put the full tag_mode in the user settings and add my syntax to html mode.

**Comment by facelessuser** [comment]
Yeah, there is no specialized override logic for any of the BH plugins like tags.

**Comment by facelessuser** [comment]
As the original poster was we were able to steer the user on how to implement their custom requirement, closing issue.
