### ISSUE TITLE
The installation was successful, the BracketHighlighter folder and package could not be found

### ISSUE THREAD

**Issue by wangmings** [facelessuser/BracketHighlighter#596]
Why can't I find the BracketHighlighter folder or related files in the plugin management of sublime text after installing BracketHighlighter?

**Comment by facelessuser** [comment]
There's not a lot of information here.

1. Is BracketHighlighter not working? Or is it working fine?
2. Where did you look for the package. Package Control usually installs packages in Installed Packages as a zip instead of the Packages folder. The exceptions are dependencies and packages that explicitly tell Package Control not to.

**Comment by wangmings** [comment]
BracketHighlighter installed via sublime text works fine, but the related BracketHighlighter folder and package cannot be found in sublime's Packages folder. It exists like a ghost. Additional plugins installed through sublime can be found in the Packages folder. But I just can't find the BracketHighlighter folder, as if I can't see it or touch it, I'm so worried! It's worse than a virus, which makes me wonder how BracketHighlighter works. After installation it works, but the executable related to it cannot be found.

**Comment by facelessuser** [comment]
As I mentioned, the zip is installed in the `Installed Packages` directory, not the `Packages` directory. IIRC, it is right next to the `Packages` directory on your filesystem.

**Comment by wangmings** [comment]
Thank you for clearing my doubts! Turns out it zips the file and renames it! It's no wonder that the relevant files were not searched using the command before.

**Comment by wangmings** [comment]
Thank you for clearing my doubts! Turns out it zips the file and renames it! It's no wonder that the relevant files were not searched using the command before.
