### ISSUE TITLE
BracketHighlighter.sublime-package file cannot be used after decompression

### ISSUE THREAD

**Issue by wangmings** [facelessuser/BracketHighlighter#597]
After decompressing the BracketHighlighter.sublime-package file, recompress it into zip format, modify it into a file in sublime-package format, and put it in the Installed Packages directory. BracketHighlighter does not work after restarting sublime. Is it because the compression format is wrong?

**Comment by facelessuser** [comment]
I have no idea. Your change could be bad, compression could be bad, a number of things may or may not be wrong. I have no way to debug custom, user modifications.

**Comment by facelessuser** [comment]
As there has been no reply for over two months, closing this issue as stale.
