### ISSUE TITLE
Add Jinja to list of supported syntaxes

### ISSUE THREAD

**Issue by stfnx** [facelessuser/BracketHighlighter#605]
The package [Jinja2](https://packagecontrol.io/packages/Jinja2) provides the `Jinja` syntax. BracketHighlighter already has support for the following Jinja syntaxes:
- HTML (Jinja Templates)
- HTML (Jinja2)
- HTML (Django)

But "Jinja" is missing on this list so BracketHighlighter isn't active for this syntax. 

Since it already supports `HTML (Jinja2)`and `Jinja`is exactly the same syntax, the change would probably be as simple as adding Jinja to the above list in the package settings.

I have to admit though that I couldn't get it working while editing the package's tag settings. Probably I'm just too stupid.

**Comment by facelessuser** [comment]
Yeah, at this point, I don't often update the list with every supported language, I should probably just add a `and more` entry 🙃. I personally have only validated the Jinja2 package as that is the only one I use.

**Comment by stfnx** [comment]
I am talking about the Jinja2 package and tag highlighting doesn't work for me.
Should it work by default?

**Comment by facelessuser** [comment]
Hmm, let me check, it may be something I have locally...

**Comment by facelessuser** [comment]
Okay, I missed that this was requesting for the `Jinja` syntax support to be added, I thought you were requesting it to be mentioned in the docs...

This is an easy fix.

**Comment by facelessuser** [comment]
I have a fix in PR.

**Comment by stfnx** [comment]
Nice! Thank you. :)
