### ISSUE TITLE
PHP angle brackets bug

### ISSUE THREAD

**Issue by johntor** [facelessuser/BracketHighlighter#608]
When angle brackets are enabled in php and there is a n array assignment symbol '=>'  the BracketHighlighter is unable to match brackets...

**Comment by facelessuser** [comment]
Can you post a reproducible example?

**Comment by johntor** [comment]
You can try the following...
```

<?php
class Example {
	public function __construct() {
		$result = DB::getResult();
		foreach ($result as $row => $data) {
			echo($data)
		}
	}
}

```
Which gives:
![example](https://user-images.githubusercontent.com/478884/192134577-4061cade-9295-4a78-aefd-539b2cf42b54.png)

A quick and dirty solution I found is to disable 'angle' brackets for php from settings file, adding another "scope_exclude" for  'embedding.php'


![solution](https://user-images.githubusercontent.com/478884/192134970-40f1c584-f95e-41f6-8734-1a75d2d03178.png)

Keep on the great work!!!

J!

**Comment by facelessuser** [comment]
Yeah, the syntax keeps changing, that is why there are so many PHP exclusion rules. I don't use PHP very often, so I'm often not aware of the changes until a heavy PHP user brings it to my attention.

Thanks for the detailed info and the solution. I'll update the rule for the next release.

**Comment by johntor** [comment]
We thank you for your effort to make us more productive!!

J!

**Comment by facelessuser** [comment]
Okay, we are actually going to go with `embedding.php punctuation.separator.key-value.php` as `embedding.php` will break tag matching in PHP.
