### ISSUE TITLE
BH broken after last update (4142 and 4143)

### ISSUE THREAD

**Issue by rusproject** [facelessuser/BracketHighlighter#610]
## Description

The problem is on the screenshots. The package just doesn't work correctly anymore.

![image](https://user-images.githubusercontent.com/62891105/201425020-400364c2-77a0-43fc-9180-5f57e6e3c534.png)
![image](https://user-images.githubusercontent.com/62891105/201425066-c31d9c65-6784-4bc1-8ddd-3e4017ed87ff.png)
![image](https://user-images.githubusercontent.com/62891105/201425092-9797792c-d111-44f3-8da0-67d78ff25d68.png)

## Support Info

- ST ver.: 4143
- Platform: windows
- Arch: x64
- Plugin ver.: 2.30.1
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.0
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. Use BracketHighlighter with previous actual ST build
2. Update to the latest ST version (4142 and then 4143 next day, don't know which one broke BH)
3. Try, for example, PHP lang and multi-line array with square brackets.

**Comment by rusproject** [comment]
For those who stubmled against same problem:

Temporary fix is to uninstall ST and install previous version, here's link:
https://download.sublimetext.com/sublime_text_build_4126_x64_setup.exe

**Comment by facelessuser** [comment]
When you post examples, pictures are fine, but please always post examples in plain text as well. I cannot copy/paste and reproduce easily within image.

Now, on to the issue. I'm on the latest dev branch and am not experiencing this at all. I'm not sure if something went wrong after the update and you needed to re-install BH, but I cannot reproduce this issue.

<img width="341" alt="Screenshot 2022-11-11 at 5 39 50 PM" src="https://user-images.githubusercontent.com/1055125/201448107-ade69f12-e092-4712-8a04-7f11217c78e9.png">

Now, the latest stable is supposed to include everything that the last dev release had before the stable release, so there shouldn't be any difference at all.

**Comment by rusproject** [comment]
Thanks, I'll keep it in mind.

The reason for my problem was that I was modifiyngs "brackets" section in my user-settings file.
To make it work I copied whole "brackets" section from default `bh_core.sublime_settings` file to user settings file, and then edit some parts (I add 2 more lines to "php_angle" and "angle" brackets just to add one more syntax (Smarty) there). 

All worked fine untill last ST update, but that update broke it for some reason, causing that behaviour on screenshots.

Now I copied not whole "`brackets`" section, but instead of that, I created "`user_brackets`" section in user-settings file, and copied only "`php_angle`" and "`angle`" there, then made my edits.

All works fine now, thank you.

P.S. 
I suppose we need more documentation about `How to edit default settings?` somewhere. Maybe I just doesn't find it in official docs.

**Comment by facelessuser** [comment]
There is no need to copy the entire `brackets` section, just use `user_brackets` to override an existing rule or add additional rules.

We do have documentation on managing bracket rules: https://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management.

I am open to a PR if a better approach can be constructed.

**Comment by rusproject** [comment]
Yeah, already get it, thank you.
No new ideas about it right now, the mechanics is pretty straightforward, I just missed that section of the docs, my bad.
By the way, it would be great to have a link to the documentation on the very top of sublime-settings file in the comment.

**Comment by facelessuser** [comment]
I'd be open to a PR that adds links to specific sections of the documentation for relevant settings that are not clear.
