### ISSUE TITLE
Feature Request: turn down highlight loudness

### ISSUE THREAD

**Issue by RobLOlson** [facelessuser/BracketHighlighter#613]
I like the idea of the solid highlight option, but the colors it uses are distractingly "loud" and sometimes clash with the syntax highlighter.  These problems could be avoided if it were possible to turn down the "value" and/or "saturation" of the highlight color.

It seems non-trivial to implement this feature.  [The ColorHighlight](https://github.com/Kronuz/ColorHighlight) plugin managed to achieve a similar effect by, I think, creating and dynamically updating a color scheme that dynamically associates regions with colors... but I'm not familiar enough with the plugin API to be sure.

**Comment by facelessuser** [comment]
If you do not like the default colors, you can specify your own: https://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style. The documentation goes into detail showing how you can modify the colors that are used.

> It seems non-trivial to implement this feature. [The ColorHighlight](https://github.com/Kronuz/ColorHighlight) plugin managed to achieve a similar effect by, I think, creating and dynamically updating a color scheme that dynamically associates regions with colors... but I'm not familiar enough with the plugin API to be sure.

I am generally against plugins that dynamically update someone's color scheme in this manner. There are very few exceptions where I may find this acceptable. For this reason, I purposely do not use ColorHighlight and instead maintain my own color plugin called [ColorHelper](https://facelessuser.github.io/ColorHelper/) that uses an approach that I find more acceptable.

I realize others may have differing opinions, and I won't go into all the details as to why I feel this way, but my personal opinion is that a plugin should not take it upon itself to modify/override a user's color scheme. With that said, if a user wishes to manually create overrides, BracketHighlighter will let you change the settings to use whatever special scope you've created.

**Comment by RobLOlson** [comment]
Well, I'm embarrassed that I overlooked that part of your documentation.  Unfortunately, it seems this solution does not preserve syntax highlighting (see images).  I was hoping to just slightly adjust the background color to help focus the eye.  I'm beginning to think the limitations of the plugin API are prohibitively restrictive..  Still, thanks for taking the time.
![image](https://user-images.githubusercontent.com/4926816/212462320-a274291d-85ce-4065-b96a-2a5b19671605.png)
![image](https://user-images.githubusercontent.com/4926816/212462331-cc98ac54-0130-48a9-89eb-9e393c9627d3.png)

**Comment by facelessuser** [comment]
I'm not sure if that is a comment about BH or Sublime. Unfortunately, we have to use "regions" to color a bracket as there is no other approach available in the API for us to use. We provide as many different options to try and give people as much configurability as we can, but "regions" have certain limitations.

**Comment by facelessuser** [comment]
As this is configurable and there is no current action to take place, closing.
