### ISSUE TITLE
Inconsistent highlight with multple brackets in a row

### ISSUE THREAD

**Issue by dexusnl** [facelessuser/BracketHighlighter#629]
If a couple of successive brackets are used (like happens a lot in lisp) the highlight is inconsistent.
Below is the example 'code' that reads (((test)))

What happens when the cursor is moved over the brackets is shown below.
* is selected character, ^ is highlighted character in the following example:

```
(((test)))
*--------^
-*------^-
--*----^--
--^----*--
--^-----*- incorrect
-^-------* incorrect
```

The expected results is that in the last 3 examples the opposite should happen from the first 3 examples.

- ST ver.: 4169
- Platform: windows
- Arch: x64
- Plugin ver.: 2.31.3
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.5.1
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by facelessuser** [comment]
> If a couple of successive brackets are used (like happens a lot in lisp) the highlight is inconsistent.

On the contrary, the highlight is very consistent, it just isn't your preferred approach.

With `bracket_outside_adjacent` set to true (the default) BH will also highlight brackets when it is outside (not between) the bracket, and if between two brackets, it will favor the one on the left.

<img width="171" alt="Screenshot 2024-03-01 at 6 11 57 AM" src="https://github.com/facelessuser/BracketHighlighter/assets/1055125/fcfd40e8-a2f1-4152-a40f-d0ce1fa3e349">
<img width="193" alt="Screenshot 2024-03-01 at 6 15 04 AM" src="https://github.com/facelessuser/BracketHighlighter/assets/1055125/d1c9d697-88f1-4643-bdbd-6459bf1dbac6">

It sounds like you expect the behavior of when this feature is turned off. If so, it will only highlight the brackets it is between. Sorry, the first image didn't capture the cursor when it was blinking.

<img width="167" alt="Screenshot 2024-03-01 at 6 12 54 AM" src="https://github.com/facelessuser/BracketHighlighter/assets/1055125/5931d2f7-5a70-4690-8fb3-6cac0ba4737f">
<img width="179" alt="Screenshot 2024-03-01 at 6 15 26 AM" src="https://github.com/facelessuser/BracketHighlighter/assets/1055125/ebc18541-a33d-4c97-9b11-083da93df97c">

**Comment by dexusnl** [comment]
I see, thank you for the clarification. Works very well for me now.

Could be an idea to have this parameter set to false for formats like lisp, because there the default way doesn't make much sense.

**Comment by facelessuser** [comment]
I think it makes fine sense, but acknowledge that people will prefer one approach vs the other, hence the ability to set bracket style to a user's desired preference.

I think switching bracket convention per language would be confusing (to my brain at least), I much prefer consistency.

Currently, BH doesn't allow setting bracket conventions per language, I'm not saying I couldn't or wouldn't add such functionality, but if this is truly desired, a new issue should be opened with this request. If people seem to really want said feature, I would potentially consider it for the future.

I imagine most people just select the option that works well for their brain and never touch it again.
