### ISSUE TITLE
Bracket highlighting issue when semantic syntax highlighting in Sublime-LSP is enabled

### ISSUE THREAD

**Issue by SomedudeX** [facelessuser/BracketHighlighter#630]
## Description

When using the [Sublime-LSP](https://github.com/sublimelsp/LSP) Plugin with semantic highlighting, most of the bracket highlighting styles in BracketHighlighter will sometimes be partially or fully covered by the semantic highlighting background. 

Expected behavior:
![good](https://github.com/facelessuser/BracketHighlighter/assets/101906945/e8ec70c8-6e8f-4d1c-8fbd-764b116692d2)

Actual behavior:
![bad](https://github.com/facelessuser/BracketHighlighter/assets/101906945/8ce9d8e2-e68d-42d6-a736-eeeb8e47ce90)

Explanation:
In the expected behavior, every bracket is fully highlighted with a complete outline. In the actual behavior, either some part of the bracket highlight (e.g. the outline) or sometimes the entirety of the bracket is obscured.

## Steps to reproduce

 + **Expected behavior**
    1. Install the LSP plugin and [some language servers](https://lsp.sublimetext.io/language_servers/) through Package Control
    2. Enable [semantic highlighting](https://lsp.sublimetext.io/customization/#semantic-highlighting)
    3. Install BracketHighlighter through Package Control
    4. Observe highlighting behavior

+ **Actual behavior**
    1. Install the LSP plugin and [some language servers](https://lsp.sublimetext.io/language_servers/) through Package Control
    2. Enable [semantic highlighting](https://lsp.sublimetext.io/customization/#semantic-highlighting)
    3. Install BracketHighlighter through Package Control
    4. Restart Sublime Text
    5. Observe highlighting behavior

## Support Info

```
- ST ver.: 4169
- Platform: osx
- Arch: arm64
- Plugin ver.: 2.31.3
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.5.1
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1
```

**Comment by facelessuser** [comment]
Should BracketHighliter be working around LSP or LSP working around BracketHighlighter? Should special exceptions be be made for every plugin conflict? I'm not even sure how I can sequence these to not be broken by LSP.

**Comment by SomedudeX** [comment]
Since I was able to produce the expected behavior by installing and enabling BracketHighlighter after LSP has loaded, I was wondering whether BracketHighlighter could be loaded in later so that its visual effects won't get overridden by other plugins. However, I would understand if supporting other plugins is out of the scope of this repository.

**Comment by facelessuser** [comment]
You can really schedule when your plugin gets loaded. The only way is to change your name to be later in the alphabet, then I'm fighting with various plugins changing their name to load later. It isn't practical.

**Comment by SomedudeX** [comment]
I see, thanks for the info

I'll try something else to fix this issue then.
