### ISSUE TITLE
Support for PHP 7.4 arrow function syntax

### ISSUE THREAD

**Issue by fadrian06** [facelessuser/BracketHighlighter#631]
## Support for PHP 7.4 short function syntax

... I lost parentheses matching when I use PHP 7.4 arrow function syntax ?

![image](https://github.com/facelessuser/BracketHighlighter/assets/109766973/e7524194-3312-4f55-9daf-338b380844cf)

**Comment by facelessuser** [comment]
It is likely we just need to ignore the arrows. Please post in a code block an example in plain text (not an image) that we can test with. Also, please note what syntax you are using for PHP highlighting. Is it the built-in one? Or are you using a 3rd party library? If so, please link the 3rd party library.

**Comment by fadrian06** [comment]
oh thanks for reply it..

sure, the snippet is
```php
Route::get('/', fn () => view('welcome'));
```

The color scheme is Ayu variant Dark

**Comment by facelessuser** [comment]
We had this properly supported before IIRC, but syntax files get refactored all the time, changing scope names. Such changes can break us. So, thanks for reporting. A PR is up that should fix it.
