### ISSUE TITLE
Failing on IF...ENDIF in `SINUMERIK 840D SL RunMyHmi` scope

### ISSUE THREAD

**Issue by ramooon1** [facelessuser/BracketHighlighter#637]
## Description

For `SINUMERIK 840D SL RunMyHmi` scope BH is unable to match end tag if **`IF`**-condition is used in a code.

![image](https://github.com/user-attachments/assets/3b6e2e9e-1e05-42c1-84fb-3e56d6148a5f)
![image](https://github.com/user-attachments/assets/51330f5f-1f05-454e-9b7c-767052d3a744)
Working if it is out its scope.
![image](https://github.com/user-attachments/assets/333f3616-2ce6-461e-9918-9373c4b673e6)

**Without `IF` it is working fine:**
![image](https://github.com/user-attachments/assets/936478fc-2ecf-48a6-ba97-f1b6f25a01d1)

## Proposal
Regex for *open/close* for `SINUMERIK 840D SL RunMyHmi`:
There is no `END_IF` in this syntax. Therefore, the first thing I tried to do was to change that - unfortunately, no success. I also added some minor improvements.
``` js
{
            "name": "s840d_hmi",
            "open": "(?i)(?:^ *)(//[ABGMS]|ACTIVATE|CHANGE|FOCUS|IF|LOAD|UNLOAD|OUTPUT|PRESS|SUB)\\b",
            "close": "(?i)(?:^ *)(//END|\\bEND_(?:ACTIVATE|CHANGE|FOCUS|LOAD|UNLOAD|OUTPUT|PRESS|SUB)|ENDIF)\\b",
            "style": "tag",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.s840d_hmi",
            "language_filter": "allowlist",
            "language_list": ["s840d_hmi"],
            "enabled": true,
}
```

## Support Info
- ST ver.: 4180
- Platform: windows
- Arch: x64
- Plugin ver.: 2.31.5
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.5.1
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by facelessuser** [comment]
@ramooon1 It sounds like the IF rule should get fixed, not removed. Can you provide a copy/pastable code sample for testing? I do not use this language and I have no interested transcribing the example from a photo.

**Comment by ramooon1** [comment]
@facelessuser  I just removed *IF* from non-capturing group of close member and added *ENDIF* to the end of regex because of *END_*.

Here is a code for this language (with IF):
```
//M(WsW_or_WsRaus/"Move Z-Axis to Softlimit"/ /30,10///)
   DEF info    =(S///"","Werkstück wechseln oder Werkstück raus ?"," "/WR1,FS2/ /""/20,50,500/,,/)  
   DEF infoJa  =(S///"","Wechseln:    Werkstück gegebenenfalls entladen und aus Beladestation beladen"," "/WR1/ /""/80,180,500/,,/)  
   DEF infoNein=(S///"","Entladen:    Werkstück aus der Maschine zur Beladestation"                  ," ",/WR1/ /""/80,220,500/,,/)  

   vs7=("wechseln",,Se1) 
   vs8=("entladen",,Se1) 

   LOAD  
   END_LOAD

   PRESS(VS7)
      IF true
         DLGL("asdf")
      ENDIF
      wnp("$R[7]",1)
      exit 
   END_PRESS

   PRESS(VS8)
      wnp("$R[7]",2)
      exit 
   END_PRESS
//END
```

**Comment by facelessuser** [comment]
If you already have a solution, you can issue a pull request.

**Comment by ramooon1** [comment]
It's not a solution, with this regex I'm able to find every  ENDIF e.g. python. But it doesn't work with BH.--Mit freundlichen Grüßen / Best regardsRoman Bondarenko Von: Isaac Muse ***@***.***>Gesendet: Donnerstag, Oktober 24, 2024 6:28:23 PMAn: facelessuser/BracketHighlighter ***@***.***>Cc: ramooon1 ***@***.***>; Mention ***@***.***>Betreff: Re: [facelessuser/BracketHighlighter] Failing on IF...ENDIF in `SINUMERIK 840D SL RunMyHmi` scope (Issue #637)
If you already have a solution, you can issue a pull request.

**Comment by facelessuser** [comment]
Alright, I'll take a look sometime soon.

**Comment by facelessuser** [comment]
I took a look, the real issue is that SINUMERIK 840D HMI seems to not use `END_IF` like it does with `PRESS` and other blocks, but uses `ENDIF`.  I don't recall if this work was done via a pull request or by me, but if by me, that makes sense as I don't use this language. This is why it is better for those who use the language to provide such rules and fixes as they have better understanding of the underlying language, something I don't have time to learn.
