### ISSUE TITLE
No reaction to color change

### ISSUE THREAD

**Issue by RIS2000** [facelessuser/BracketHighlighter#639]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description
Hello!
Thanks for a great plugin!

"double_quote": {
            "icon": "double_quote",
            "color": "#FF0000" <-------------- no reaction to this, only to "region. ..ish"
            // "style": "underline"
        }

Sublime v3.2.2

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

---------------------------
Sublime Text
---------------------------
- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 2.31.5
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.5.1
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

## Steps to Reproduce Issue

1. First step...
2. Second step...
3. Third step...

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by RIS2000** [comment]
@facelessuser, thanks for quick reply!

I've read that documentation, but can't get this:
"To append your new rule (or override an existing rule) you can create a .sublime-color-scheme file in your Packages/User folder."

I use Windows 10 and don't have "Packages/User" folder. Also there is no ".sublime-color-scheme" file. And there is no way to create such file in Windows (only extension without name).

**Comment by facelessuser** [comment]
> I use Windows 10 and don't have "Packages/User" folder.

You do. Try going in your menu: `Preferences->Browse Packages...` and then select `User`.

> Also there is no ".sublime-color-scheme" file. And there is no way to create such file in Windows (only extension without name).

Please read Sublime's documentation on color scheme customization https://www.sublimetext.com/docs/color_schemes.html#customization.

> And there is no way to create such file in Windows (only extension without name).

This is not true. You do seem unfamiliar with how to create files in Windows. If you cannot view file extensions in Explorer, check this out: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/How-to-enable-hidden-file-extensions-in-Windows.html

Windows may limit you on what file extensions you can create by default, but you can always create a text document and then rename it. With the viewing of file extensions in Explorer enabled (as mentioned above), you can rename the extensions.
