### ISSUE TITLE
您好!

### ISSUE THREAD

**Issue by meihangbo** [facelessuser/BracketHighlighter#95]
使用您的插件,在HTML显示正常,但是在JSP中没有效果,不知怎么解决?谢谢!
![qq20130510133052](https://f.cloud.github.com/assets/4393475/486710/1507e06e-b933-11e2-83cd-c85972f9479e.png)
下边是JSP
![qq20130510133207](https://f.cloud.github.com/assets/4393475/486711/1c6684b4-b933-11e2-88f6-e3de18096b50.png)

**Comment by followgiant** [comment]
@princemaple 

It didn't work for my ST3 build 3065 in JSP, please help
When I copy you config to preferances/package settings/bracket highlighter/bracket setting - user, this plugin didn't work in all the other syntax

**Comment by yangsaipp** [comment]
@followgiant i hit the same problem with you，are you sovle ?
